### ISSUE TITLE
(5.0) Windows build problem with WSAPoll

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#101]
A Windows build error was reported in #100, something about poll.

**Comment by hongyue** [comment]
![image](https://user-images.githubusercontent.com/1144338/63319367-6b801e00-c34c-11e9-82cd-b787c0b7e323.png)

**Comment by bsergean** [comment]
@hongyue try again, I moved that header to a different spot, that include error should be gone.

My fear is that the build will still fail on Windows, with poll() not found. If that's the case we can try something else.

**Comment by hongyue** [comment]
I think the poll.h is *nix only, you should using Windows specific tech to implement it, I'll give you the feedback later.

**Comment by bsergean** [comment]
See this (c72b2db), I believe it should work now if you git pull again

**Comment by hongyue** [comment]
Ok, passed.
