### ISSUE TITLE
change ZLIB's find_package to be optional

### ISSUE THREAD

**Issue by Joonitoi** [machinezone/IXWebSocket#104]
Change ```
find_package(ZLIB REQUIRED) ```
to be optional as the build breaks when running it on Windows.

**Comment by bsergean** [comment]
There's a version that is bundled with the source, which can be used when zlib cannot be found (through conan or vcpkg).

```
find_package(ZLIB REQUIRED)
if (ZLIB_FOUND)
  include_directories(${ZLIB_INCLUDE_DIRS})
  target_link_libraries(ixwebsocket ${ZLIB_LIBRARIES})
else()
  add_subdirectory(third_party/zlib)
  include_directories(third_party/zlib ${CMAKE_CURRENT_BINARY_DIR}/third_party/zlib)
  target_link_libraries(ixwebsocket zlibstatic wsock32 ws2_32)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif()
```

Should REQUIRED be removed here ?
Can you try to remove that REQUIRED and see if this fixes it ?

**Comment by Joonitoi** [comment]
removed REQUIRED and was able to build on windows. Had to do some workarounds using CMAKE to actually get the static library and the header files, but got it working after a while :)

**Comment by bsergean** [comment]
Good for you, happy you got it to work.

Can you explain/post what you did for the extra static/header files bits ?

```
  add_subdirectory(third_party/zlib)
  include_directories(third_party/zlib ${CMAKE_CURRENT_BINARY_DIR}/third_party/zlib)
  target_link_libraries(ixwebsocket zlibstatic wsock32 ws2_32)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)
```

**Comment by Joonitoi** [comment]
- removed REQUIRED from find_package for ZLIB (that way if it did not find ZLIB, it added it manually)
- ```mkdir build```
- ```cd build```
- ```cmake -DCMAKE_INSTALL_PREFIX="PathToInstall" ..```
- ``` cmake --build . --target INSTALL ```
This is what I did to be able to build the header files and the static library, and from what I can tell it worked like it should. Tho, it tried to start building ZLIB which I don't think you want but it doesn't matter because that build faild haha.
