### ISSUE TITLE
Any support for configuring a client cert?

### ISSUE THREAD

**Issue by matt-deboer** [machinezone/IXWebSocket#113]
also, is it possible to configure a ca trust file?

**Comment by bsergean** [comment]
What I know of is the ca cert (Certificate Authority).

On mac/iOS the system cert is used.
With Linux/OpenSSL you can use the SSL_CERT_FILE environment variable and point it to a file (such as the one that curl is using).

What are you trying to do ?

**Comment by matt-deboer** [comment]
I'm actually looking to configure the cert/key combo that a client would present to the server under client cert authentication.

**Comment by bsergean** [comment]
Try to use the SSL_CERT_FILE environment variable. If you want to do it in C/C++ in code, you can use setenv.

**Comment by matt-deboer** [comment]
If I'm not mistaken (reading [the OpenSSL docs](https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html)) that variable sets the location of the cert bundle file that would be used to verify the cert presented by the server. I want to set the certificate and key files used by the client to present to the server....

**Comment by matt-deboer** [comment]
I guess I'm looking for the equivalent of whatever method you use to set the key and certificate on the WebSocketServer or HttpServer...but I can't seem to find how that is configured...

I'm considering implementing this in a PR, I just want to make sure I haven't missed something

**Comment by bsergean** [comment]
I actually haven't implemented SSL on the server classes, so this probably explains whey you can't find anything :)

**Comment by bsergean** [comment]
It might be a bit of a battle but if you want to give this a try feel free. I haven't thought too much about that a nice interface would look like, but if you want to experiment you can give it a try.

https://github.com/zaphoyd/websocketpp/blob/master/examples/echo_server_tls/echo_server_tls.cpp

**Comment by matt-deboer** [comment]
For general interface, I was looking at adding the following in `IXWebSocket.h` (and the same to WebSocketServer and HttpServer):
```
#ifdef IXWEBSOCKET_USE_TLS
        void setTLSOptions(const SocketTLSOptions& socketTLSOptions);
#endif
```
where the options looks like:
```
namespace ix
{
    struct SocketTLSOptions
    {
        // the certificate presented to peers
        std::string cert_file;
        // the key used for signing/encryption
        std::string key_file;
        // the ca certificate (or certificate bundle) file containing 
        // certificates to be trusted by peers; use 'SYSTEM' to
        // leverage the system defaults, use 'NONE' to disable peer verification
        std::string ca_file = "SYSTEM";
    };
} // namespace ix

(this would default to PEM format, at least at first)


```

**Comment by bsergean** [comment]
That sounds good. You might have to channel those options down to the SocketFactory thing which create the right socket for the right platform.

I have a big distaste for MACRO in general so I think I prefer if setTLSOptions is always defined / maybe we can put an assert in the implementation file if the interface is used but IXWEBSOCKET_USE_TLS isn't defined.

One aesthetic thing, for consistency member variables should be snakeCase: ca_file -> caFile, cert_file -> certFile etc...

If you can expose those args to the ws connect (and others too maybe, like ws curl, not sure we need it for all of them), that would be ideal for interactive testing.

**Comment by matt-deboer** [comment]
Ok, I took a stab at basic impl for OpenSSL here #114 .

I haven't applied your comments yet, since I just saw them while writing this : )

Once some of the basic details are ironed out, I can tackle the other implementations...

**Comment by mwinch2** [comment]
Can I just confirm the current status of IXWebSocket support for websocket over TLS on Windows? The limitations section of the docs says "On Windows TLS is not setup yet to validate certificates" and I have created a simple client which connects to wss://echo.websocket.org and I get the following error:

Error: Unable to connect to echo.websocket.org on port 443, error: error in handshake : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed

Is that expected? If not I will do some more investigation into the above.

Thanks

**Comment by mwinch2** [comment]
I think I answered my own question - it only works if you explicitly specify a CA file via SocketTLSOptions.

**Comment by bsergean** [comment]
Yep that's right. I just tried to improve the doc on that. Windows has builtin ssl support, through something called [SChannel](https://docs.microsoft.com/en-us/windows/win32/com/schannel) which we could try to use to discover existing system certificates.

**Comment by mwinch2** [comment]
Thanks. I can work with the current implementation as I only need to connect to a single URL, with the server also under my control, so only need to manage one certificate.

In the past when I was looking at doing a TLS connection from scratch on Windows, I found the "StreamSSL" example very helpful:  https://github.com/david-maw/StreamSSL

**Comment by ludekvodicka** [comment]
Hi, I just trying your lib (Win, VS2019) and receiving:

 `Unable to connect to echo.websocket.org on port 443, error: error in handshake : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed`.

Can I ask you for advice what exactly I have to do to connect to WS server?

If I understand, I have to download the certificate manually for every connection I want to create? Is there any way how to automatize it? 

Thank you

**Comment by bsergean** [comment]
That page is a good read on the topic -> https://curl.haxx.se/docs/sslcerts.html

At this point on Windows this is what you need to do:

1. Go read that page too / https://curl.haxx.se/docs/caextract.html
2. Download https://curl.haxx.se/ca/cacert.pem and save it somewhere on disk.
3. Pass that pass to the caFile field as you guessed. "NONE" is the option is you don't want to do peer verification, but it is not recommended unless you just want to do testing.

```
ix::SocketTLSOptions opt;
opt.caFile = "C:\Path\to\downloaded\cacert.pem";
webSocket.setTLSOptions(opt);
```

You will have to bundle that file with your application/code.

Please tell me if that doesn't work for you.

**Comment by ludekvodicka** [comment]
Thanks a lot for the perfect todo list. Everything works great now. 

Is there any way how to pass a memory buffer instead of a file path?  If not, I can save it to tmp file.

**Comment by bsergean** [comment]
Sure thing, glad it's working for you now !

For the memory buffer, no at this point you need to save to a tmp file. The library could do that for you. I thought about putting 'a version' of the cacert in a big static array that we compile with the project. We could have a new keyword 'BUNDLED' for that, and that way the default behavior would be 'working just fine'.

We could also generate a cacert using the Windows SChannel API, but I program on mac and linux usually and I'm not very good at adding those kind of features.

**Comment by ludekvodicka** [comment]
I believe BUNDLED version is good. Extracting it from SChannel could cause different behaviors based on OS version. Fixed array will be always same.

**Comment by moonbaseDelta** [comment]
Hi all, I found another nice way for that on Windows, it works for complete I-don't-know-what-TLS-even-stands-for: 

One just install OpenSSL on the machine and then goes into program's directory and search for "cacert.pem" and "cert.pem". Just copy those to your project's exe directory and that's it. In code just use:
```
    ix::SocketTLSOptions opts; 
    ...
    opts.certFile = "cert.pem";
    opts.caFile = "cacert.pem";
```
..or more complex paths if the files will be not in the same directory with an executable.

----
And also those certs should probably work on another Windows machines. In sequrity perspective it's of course not a good practice at all, but if you want it to be "just working" - it will be.

**Comment by bsergean** [comment]
I think we're all good now.

If someone here wants to have an implementation where we can embed a cert, please make a different ticket. Thanks !

**Comment by liz3** [comment]
> ix::SocketTLSOptions opt;
> opt.caFile = "C:\Path\to\downloaded\cacert.pem";

@bsergean this should be put in the docs

**Comment by bsergean** [comment]
It should be in there already in the tls section, but isn't necessary when using OpenSSL as system certificates are used on Windows.

**Comment by liz3** [comment]
@bsergean 
Let me know if this is out of scope of this issue and i can move it into a new issue, but since its semi related, will add it there.
Note i edited [my first comment](https://github.com/machinezone/IXWebSocket/issues/113#issuecomment-629729847) because it was referring the wrong comment answer first.

I build Tokio for windows. Since MinGW seamed non fitting(super abstracted, a lot of dependencies), i used the vcpkg package.
The package contains an outdated [package version](https://github.com/microsoft/vcpkg/blob/8a583e80da3b72141105da9003175679af2fcb92/ports/ixwebsocket/portfile.cmake#L4), further i think it explicitly defines to use mbdedtls [see here](https://github.com/microsoft/vcpkg/blob/8a583e80da3b72141105da9003175679af2fcb92/ports/ixwebsocket/portfile.cmake#L11).
So to get cmake to include/link properly on windows i had to do the following
```cmake
find_path(IXWEBSOCKET_INCLUDE_DIR ixwebsocket/IXWebSocket.h)
find_library(IXWEBSOCKET_LIBRARY ixwebsocket)
include_directories(${IXWEBSOCKET_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} PRIVATE ... ${IXWEBSOCKET_LIBRARY} ... )
```

So i think the solution would be to update the docs for people using mbedtls on windows and update the vcpkg versions.

**Comment by bsergean** [comment]
I am trying to load the system certificates on Windows as well with mbedtls, so that folks don't have to use a bundled cacert.pem and the library is less error-prone on Windows.

I am trying to update the vcpkg version right now but there are problem with uwp.

**Comment by liz3** [comment]
The reason i didnt build it myself is that simply i do not know how.
```
mkdir build # make a build dir so that you can build out of tree.
cd build
cmake -DUSE_TLS=1 ..
make -j
make install
```
upon the `cmake -DUSE_TLS=1 ..` it makes sense. but makefile are a unix system. how do i actually perform the build?

**Comment by bsergean** [comment]
appveyor.yml
.github/workflows/ccpp.yml

You can look at those CI files to see how to build things on Windows.

**Comment by liz3** [comment]
@bsergean i fixed it for now by manually patching the portfile within vcpkg to use the newest release and build with openssl
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO machinezone/IXWebSocket
    REF v9.6.2
    SHA512 22a97f0c74d5789fd265627bbadfce02116a41fca888d684b756cbb1c070d626517855e265c484870d02db7084b6c1107d500acc1c13e327ede0c23228a54f7b
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA # Disable this option if project cannot be built with Ninja
    OPTIONS -DUSE_OPEN_SSL=1 -DUSE_TLS=1
)```

But one thing i noticed is that i had to link two libraries to satisfy the linker: 
``` target_link_libraries(${PROJECT_NAME} PRIVATE ...

     ws2_32 
     shlwapi 
     crypt32 
...
```
I do not know how if this can be handled from within ixwebsocket or i need to link against them my self. But it does work for now.

P.S. I managed to build it on windows using `cmake --build .` but it didnt seam to generate a header folder like vcpkg did so im sticking with the vcpkg for now and hope the upstream pr gets merged in vcpkg soon

**Comment by bsergean** [comment]
if (WIN32)
  target_link_libraries(ixwebsocket PUBLIC wsock32 ws2_32 shlwapi)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)

  if (USE_TLS)
    target_link_libraries(ixwebsocket PUBLIC Crypt32)
  endif()
endif()

There's this block on cmake stuff that should handle it, but I don't understand why it doesn't kick in in your configuration.
