### ISSUE TITLE
Where are the labels for newer versions of the library?

### ISSUE THREAD

**Issue by LunarWatcher** [machinezone/IXWebSocket#120]
I'm not gonna lie - I've slightly dropped the ball on staying up to date with releases. I'm going through the versions now but I noticed a discrepancy between [the changelog](https://machinezone.github.io/IXWebSocket/CHANGELOG/) and [the tags](https://github.com/machinezone/IXWebSocket/tags): there's no new tags after 6.2.1. 

conan-IXWebSocket kinda needs labels or some other way of identifying specific versions. Branches are also fine, but requires some change to my code for it to build properly. I can't find any identifiers, which prevents me from properly updating the conan package. Am I missing something, or were they just not created?

**Comment by bsergean** [comment]
Eh the release process isn’t very consistent :)

I’ll make a tag with the latest version (and maybe something from the 6x branch).

What’s cool in the latest code is that there is a way to explicitely set a CA-CERT (typically people use the file from firefox) on all platform, especially Windows where this was lacking.

cf https://curl.haxx.se/docs/caextract.html <https://curl.haxx.se/docs/caextract.html>

**Comment by LunarWatcher** [comment]
I of course don't need a tag for every version - with 6.2.1 covered, you don't really need to add anything more from version 6. If you do though, that's fine - I'll just set up the job to build and distribute it. 

Not forcing you to do anything here of course, but could I suggest creating a tag at least (I need to emphasise "at least" - tags for every versioned release is fine too) every time the second digit changes? As in no tags required for i.e. 7.3.3, but a tag for 7.3.0 and at some point 7.4.0. That's enough to let me stay up to date.

The update does sound cool though - I'm still on 5.0.0 for some reason ^^"

**Comment by bsergean** [comment]
> On Nov 1, 2019, at 10:46 AM, Olivia Zoe <notifications@github.com> wrote:
> 
> I of course don't need a tag for every version - with 6.2.1 covered, you don't really need to add anything more from version 6. If you do though, that's fine - I'll just set up the job to build and distribute it.
> 
> Not forcing you to do anything here of course, but could I suggest creating a tag at least (I need to emphasise "at least" - tags for every versioned release is fine too) every time the second digit changes? As in no tags required for i.e. 7.3.3, but a tag for 7.3.0 and at some point 7.4.0. That's enough to let me stay up to date.
> 
Ok I'll try to remember it but don't quote me on it ... :)

I've just tagged 7.2.2

> The update does sound cool though - I'm still on 5.0.0 for some reason ^^"
> 

The old idiom is "If it aint' broke don't fix it." right.

BTW if there's anything that bugs you in the library or you'd like a new feature to be added please don't hesitate to tell me or make a feature request.
