### ISSUE TITLE
android error with ix::setThreadName()

### ISSUE THREAD

**Issue by kaizer1** [machinezone/IXWebSocket#121]
Hi , I'm trying to build on android and here is such an error : 
IXWebSocket-master/libixwebsocket.a(IXWebSocket.cpp.o): In function `ix::WebSocket::run()':
/Users/sergeiloskutnikov/Desktop/androidDev/SantaFight/app/.cxx/cmake/debug/arm64-v8a/../../../../IXWebSocket-master/ixwebsocket/IXWebSocket.cpp:320: undefined reference to `ix::setThreadName(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Everything is going without errors, but such a mistake when compiling

**Comment by bsergean** [comment]
Hi @kaizer1, thanks for using IXWebSocket. 

I think that this build failure is a simple problem in the CMakeFile, where one file is not picked up for some reason.

```
# Platform specific code
if (APPLE)
    list( APPEND IXWEBSOCKET_SOURCES ixwebsocket/apple/IXSetThreadName_apple.cpp)
elseif (WIN32)
    list( APPEND IXWEBSOCKET_SOURCES ixwebsocket/windows/IXSetThreadName_windows.cpp)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
    list( APPEND IXWEBSOCKET_SOURCES ixwebsocket/freebsd/IXSetThreadName_freebsd.cpp)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    list( APPEND IXWEBSOCKET_SOURCES ixwebsocket/linux/IXSetThreadName_linux.cpp)
    list( APPEND IXWEBSOCKET_SOURCES ixwebsocket/IXSelectInterruptEventFd.cpp)
    list( APPEND IXWEBSOCKET_HEADERS ixwebsocket/IXSelectInterruptEventFd.h)
endif()
```

That missing function that the linker cannot find is in ixwebsocket/linux/IXSetThreadName_linux.cpp.

I've just fixed that in 521286ae8825b4a5b2b9976e3093c7ff9ec301b2, which got released in 7.3.1 / please give it a try.

**Comment by kaizer1** [comment]
Everything works, thank you !

**Comment by bsergean** [comment]
Great. Let me know if you have issues or questions about using the library.

If you are using TLS/encrypted connections (connecting to wss:// endpoint), you should know that on Android you should set a ca cert. Search for TLS in this [page](https://machinezone.github.io/IXWebSocket/usage/) for more details.

**Comment by bsergean** [comment]
And there's a way to disable certificate verification, look in setTLSOptions, but this isn't recommended.
