### ISSUE TITLE
Avoiding the use of lambda functions

### ISSUE THREAD

**Issue by rhythmize** [machinezone/IXWebSocket#123]
Hi,
First of all, amazing library and great work.
Just one question though, Right now all the callbacks like `setOnConnectionCallback` and `setOnMessageCallback` are implemented using `lambda functions` in all the examples. I cannot find any examples where those callbacks are registered without lambda functions. Actually I'm using this library in my application for WebSocketServer. So, is there a way I can avoid the use of `lambda functions` for registering callbacks?
Thanks.

**Comment by bsergean** [comment]
1. It looks like you are trying to write a server, is that right ? Is the callback approach ok for writing clients. The nice things is that you can use almost the same code for clients and servers with the callback approach.

2. What do you suggest as an alternative to writing callback ? Overriding methods ? Do you have an example library that we could use as an example ?

If you are looking for a more serious example of a server, look at [ixsnake](https://github.com/machinezone/IXWebSocket/tree/master/ixsnake/ixsnake).

Each connection [state](https://github.com/machinezone/IXWebSocket/blob/master/ixsnake/ixsnake/IXSnakeConnectionState.h) is held by this object, which you can override.

**Comment by rhythmize** [comment]
Yeah, I'm writing a socket server. For this situation callback approach is the only way to go (As far as I know. Could be wrong as well). But my point was about the way callbacks are being registered through lambda functions. Which makes the code really cluttered at one point with lamba's within lanbda function.

Another cleaner approach would be registering callbacks like I have seen in socket libraries in python and other languages.
For example, 
In [Flask-Socketio](https://flask-socketio.readthedocs.io/en/latest/) there are provisions like `socketio.on_event('event-name', my_function_handler)` and the code structure looks more cleaner than nested lambda functions.
Likewise in [websocketpp](https://github.com/zaphoyd/websocketpp/blob/master/examples/broadcast_server/broadcast_server.cpp), we can do like `set_open_handler, set_connect_handler` and things to attach the callback methods.

Another thing I noticed is due to this lambda based callbacks, these are registered for every new connection, which can be avoided is a different approach (like the one I have shared) is used.

So my question was, Is there a way I can register these callbacks without using lambda functions?
Moreover the same approach can be used in socket clients as well, it's not only limited to server implementations.

**Comment by bsergean** [comment]
You are not forced to use lambda, you can declare your function beforehand (my_function_handler), and then pass it in. C++ should let you do that if the prototype are matching. You can look at std::bind too if you want to pass extra parameters.

**Comment by rhythmize** [comment]
Yeah, I understand, but I was facing issue with converting capture variables in lambda's scope to normal method. So I thought if there is some example written in such a way.

**Comment by bsergean** [comment]
https://en.cppreference.com/w/cpp/utility/functional/bind <https://en.cppreference.com/w/cpp/utility/functional/bind>

Maybe that example will be helpful for you. If you figure out your way, you can send a pull request to augment the doc (see doc/usage.md file).
Foo foo;
    auto f3 = std::bind(&Foo::print_sum, &foo, 95, _1);
    f3(5);

**Comment by rhythmize** [comment]
Okay, sure. Will do.
Thanks for sharing the reference.
