### ISSUE TITLE
Uninitialized bool in IXSocketTLSOptions.h

### ISSUE THREAD

**Issue by mox1** [machinezone/IXWebSocket#134]
Right around line 47 ` mutable bool _validated; `

This was causing my invalid TLS config to be seen as valid. Changing that line to 

` mutable bool _validated = false;`

fixed my problem.

Unfortunately pull request will be a bit more work, as I was installing through vcpkg.

**Comment by bsergean** [comment]
Thanks for the report !

Fixed in ba3b1c1a0fc3596c9ba0c3ce4840bcba49bb5fd6
