### ISSUE TITLE
Multiple endpoints in one ix::Websocket class?

### ISSUE THREAD

**Issue by ludekvodicka** [machinezone/IXWebSocket#145]
Is there any way how to open multiple endpoints from one Websocket class?

We're using WS for connecting ta price/candle/trade streams where every tradeable pair has its own stream. For example 

- wss://stream.binance.com:9443/ws/bnbbtc@aggTrade
- wss://stream.binance.com:9443/ws/btcusdt@aggTrade

Can I create multiple streams per object? There can be hundreds of opened streams so creating one Websocket class per stream isn't probably a good idea (because every class has it's own thread as far as I saw).

Thanks

**Comment by bsergean** [comment]
Hi @ludekvodicka,

This isn't supported now, and as you guessed you'll need one WebSocket class per connection. This is the case for most of the websocket classes I've seen.

Some options:
1. I would poke the binance.com folks and ask if they have an api for getting multiple streams through only one API.
2. Not all websocket classes use one thread per connection, they will give you a file descriptor but you'll have to poll manually and use an api like select or epoll, or libuv, or completion ports on Windows, but this work will be on you.

**Comment by ludekvodicka** [comment]
Thanks for the reply.

Binance have API for opening multiple streams at once, but we need to add/remove streams during runtime as necessary. So we're using some kind of "load balancing" for endpoints per WS class.

Currently, we're using libwebsockets where is possible to add/remove endpoints on the fly. But we have some problems there so I'm trying to find an alternative.

**Comment by bsergean** [comment]
Got it. Well good luck, I would poke the binance guys and ask that they let you publish/subscribe to different channel, by sending control messages through the one opened connection.

On their end maintaining many different connections might not be ideal either. But they probably know what they are doing :)

**Comment by ludekvodicka** [comment]
Thanks!

I just checked the documentation and it seems that they finally added it in 11-13-2019. 

I have to check also other exchanges but hopefully, I will be able to use your lib.

Have a nice day!

**Comment by bsergean** [comment]
I have no ideas on how many threads Windows will let you run.

On 64 bits it looks like it will be easier to handle many threads / https://blogs.technet.microsoft.com/markrussinovich/2009/07/05/pushing-the-limits-of-windows-processes-and-threads/ (that article is old though)

**Comment by bsergean** [comment]
Cool, tell me if you run into problems with my lib or if libwebsocket does it for you.
