### ISSUE TITLE
IPv6 support in SocketServer

### ISSUE THREAD

**Issue by ronen** [machinezone/IXWebSocket#148]
Unless I'm missing something, it doesn't seem possible to use `ix::WebsocketServer` to open an IPv6-compatible socket?

In particular, I see that the implementation of `ix::SocketServer` uses `inet_addr()` to look up the host name:
  
https://github.com/machinezone/IXWebSocket/blob/04c9985030a14f3c4be6c59c696b56ae4251bc10/ixwebsocket/IXSocketServer.cpp#L93

Unfortunately, `inet_addr()` is IPv4 only, it isn't compatible with IPv6, the solution seems to be to switch to `getaddrinfo()` as per https://stackoverflow.com/a/34383260/1056941 or https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html -- though unfortunately `getaddrinfo()` is not a drop-in replacement for `inet_addr()`, some recoding would be needed...

**Comment by bsergean** [comment]
Thanks for the report. I'm very unfamiliar with ipv6 so I'll have to research this. My goal is to keep this library multi-platform so I'm trying to avoid os specific code (unless there's no choice, like for SSL code).

Have you seen that one ?
http://man7.org/linux/man-pages/man3/inet_pton.3.html

```
       inet_pton - convert IPv4 and IPv6 addresses from text to binary form
```

**Comment by ronen** [comment]
I'm not super familiar with ipv6 either, to say the least. 

It seems both `inet_pton()` and `getaddrinfo()` are multiplatform:

* http://man7.org/linux/man-pages/man3/inet_pton.3.html
* https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/inet_pton.3.html
* https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_pton

and 

* http://man7.org/linux/man-pages/man3/getaddrinfo.3.html
* https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getaddrinfo.3.html
* https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo

It seemsthey do slightly different things, and getaddrinfo may be a bit higher level?  But I don't know enough to know when/why/where it makes sense to choose one over the other.  Or whether for this use case it makes any difference at all.

Out of curiosity I googled a bit and found this: https://www.winsocketdotnetworkprogramming.com/winsock2programming/winsock2advancedInternet3c.html which describes inet_pton() and also, under "Legacy Name Resolution Routines" it describes inet_addr() and says: "This section covers the legacy name resolution and is included only for the sake of code maintenance, because new applications should be using getaddrinfo() and getnameinfo()".   So that seems to imply that inet_addr() should be replaced with getaddrinfo() rather than inet_pton().

On the other hand, I found this page: https://blog.powerdns.com/2014/05/21/a-surprising-discovery-on-converting-ipv6-addresses-we-no-longer-prefer-getaddrinfo/ which says "So, as of 2014, we consider getaddrinfo() to be avoided for IPv6 address conversions... we have reverted to using inet_pton() whenever we can get away with it – which is almost always, except in the case of scoped addresses." 

 🙄

**Comment by bsergean** [comment]
Thanks / I've changed the code to use init_pton, and to specify an address family when creating a SocketServer. See 3c272285859ef8128d83dca9b2f038b222db4d09

I haven't tested it though ... I should add to one of the ws (echo_server ?) command an option to pass that.

**Comment by bsergean** [comment]
ws echo_server --host ::1 -6

this triggers a crash ... not sure why yet.

**Comment by bsergean** [comment]
I've put some work in progress code in feature/ipv6_server

If you want to explore this and help, please do :)

**Comment by ronen** [comment]
> I've put some work in progress code in feature/ipv6_server

Thanks for jumping right in!

>  If you want to explore this and help, please do :)

I took a very quick look at what you did... you're already way past my knowledge level...

**Comment by bsergean** [comment]
I think I figured it out! 

It works on mac now, I haven't had a chance to test it on other platforms yet. If you can report / test and report on your platform of choice that would be appreciated.

**Comment by bsergean** [comment]
@ronen if you have time to give this change a try that would be appreciated.

**Comment by ronen** [comment]
> It works on mac now, I haven't had a chance to test it on other platforms yet. If you can report / test and report on your platform of choice that would be appreciated.

> @ronen if you have time to give this change a try that would be appreciated.

I'm also on a mac (MacOS 10.15.2) so this won't tell you anything you don't know... but I tried out your 8.0.1 release -- works great!

Trickiest thing was to figure out that `inet_pton` wants the hostname as just "::1" rather than "[::1]".  I.e. this is what I did that worked:

```
ix::WebSocketServer(
     port,
     "::1",
     ix::SocketServer::kDefaultTcpBacklog,
     ix::SocketServer::kDefaultMaxConnections,
     ix::WebSocketServer::kDefaultHandShakeTimeoutSecs,
     AF_INET6);
```

Thanks for the quick response!

**Comment by ronen** [comment]
Oh, and using `"::"` instead of `"::1"` magically listens for both ipv4 and ipv6, which is also handy.

**Comment by bsergean** [comment]
Cool, thanks for the feedback.

I think that :: is equivalent to 0.0.0.0 / aka bind on everything. That config sometimes gives warning on macOS, popping up dialogs which is why I don't use it as the default (not to talk about security).

Binding on both ipv4 and ipv6 is interesting.

If you feel like adding making some documentation change and making a PR please do ;p / docs/usage.md could have a new session about this.
