### ISSUE TITLE
HttpServer: Expose body from request

### ISSUE THREAD

**Issue by david-s-svedberg** [machinezone/IXWebSocket#150]
Might be that I'm missing something obvious, but the ability to get the body of the requests when implementing a HttpServer would be appreciated.

I'm trying to use this library for a REST API since I already use it's WebSocket capabilities. But maybe I'm barking up the wrong tree?

**Comment by bsergean** [comment]
Hey David, you are correct that this is missing.

The callback takes a 'HttpRequestPtr request' / that object indeed does not have the body / that thing should become a new optional member variable.

Http::parseRequest is the function which parse the subject line + the headers ; it should be augmented to also parse the body. Http isn't simple so it will take a bit of time to code what it takes to extract the body. If you want to give this a try and make a PR that would be appreciated. I don't know if/when I'll be able to work on this.

**Comment by david-s-svedberg** [comment]
Ok, I figured as much. Being fairly new to c++ and just starting out on a
new job I won't have the time or experience to confidently take a stab at
making a PR. I'll continue using your library for WebSockets but will look
elsewhere for implementing the REST API.

Den tis 28 jan. 2020 kl 17:43 skrev Benjamin Sergeant <
notifications@github.com>:

**Comment by bsergean** [comment]
Sounds good. I don't think I'll find the time in the immediate future to add this support, but I'll try to add basic support one day.

This looks like a nice project -> http://pistache.io/ <http://pistache.io/>

Good luck !

**Comment by david-s-svedberg** [comment]
Setting up pistache as we speak :) Thanks again

Den ons 29 jan. 2020 kl 07:02 skrev Benjamin Sergeant <
notifications@github.com>:

> Sounds good. I don't think I'll find the time in the immediate future to
> add this support, but I'll try to add basic support one day.
>
> This looks like a nice project -> http://pistache.io/ <http://pistache.io/
> >
>
> Good luck !
>
> > On Jan 28, 2020, at 9:59 PM, david-s-svedberg <notifications@github.com
