### ISSUE TITLE
If a socket connection is interrupted, calling stop() on the IXWebSocket object blocks until the next retry.

### ISSUE THREAD

**Issue by maxweisel** [machinezone/IXWebSocket#151]
I'm using an IXWebSocket object. When my application is ready to shut down, I call stop() on the socket object. When the connection is open, this works perfectly. However, if the connection has been severed, IXWebSocket blocks until the next retry attempt which can be up to 10 seconds.

Steps to reproduce:
1. Create an IXWebSocket object, call setURL with any URL that is unreachable, and call start()
2. IXWebSocket will begin retrying with exponential backoff. Once it hits 10 seconds, call stop() immediately after a failed retry.
3. Observe that stop() will block for 10 seconds until a retry occurs.

I did some digging, and it seems stop() blocks on `_thread.join()`. Personally, I still want to keep stop() synchronous. I don't think that's the issue. It seems the issue is that the thread that IXWebSocket uses is blocked while waiting to try to reconnect.

Any recommendations here? I'm happy to create a fix and open a PR, but I'm not familiar enough with IXWebSocket to know what approach would be in-line with how you've designed the library.

Max

**Comment by bsergean** [comment]
Hi Max,

Which platform are you using ? There's a thing called 'selectInterrupt' to wake up the thread that blocks on select (or poll) / but it doesn't really work on Windows, and that's a lot of work to make that happen (the interrupting bit). What we could do maybe is break down the sleeping in small increments.

By 'severed' do you mean that the connection got disconnected by the server or similar ?
A good way to make progress is to code a unittest that reproduce the problem.

**Comment by maxweisel** [comment]
I'm using macOS at the moment, but I plan to ship on Linux and Windows as well.

It turns out you don't even need a severed connection. You can just try to connect to a URL that never responds, which triggers the retries. The connection itself seems to be unrelated other than the fact that you need the exponential backoff reconnect code to be running.

Max

**Comment by maxweisel** [comment]
Ok, I think I've sorted out the issue. When you create an IXWebSocket with start(), it spawns a thread. When you call stop(), it uses _thread.join() to block until the thread finishes execution. However, the connection retry logic is currently sleeping on that thread for the current retry delay, which can be up to 10 seconds.

I think the offending line is here: https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXWebSocket.cpp#L286

I'd expect we'd want a wait to stop the thread from sleeping in stop(). The best solution I can think of is to instead block on a mutex, and spin up a thread that releases the mutex after the retry time. That way, stop() can release the mutex early if needed. However, I still don't think that's a clean solution here.

Max

**Comment by maxweisel** [comment]
Possibly using something like std::timed_mutex might be the way to go. Any suggestions?

Max

**Comment by bsergean** [comment]
You're right that this sleep call will not be interruptible. A low tech but effective solution would be to sleep in small time increments using a loop, but that's close to busy looping. Maybe increments of 100ms ?

Or maybe use a condition variable ? / we have an atomic boolean set I believe when we want to 'stop'.

Would you be calling stop from the 'control' thread ? btw.

**Comment by maxweisel** [comment]
Yes at the moment, I have my application main thread, which is where I call start and stop from. 

Unfortunately, even sleeping for smaller increments here isn't an acceptable solution for my application. I think the solution for me is going to be to disable automatic retry and implement the retry code in my own application.

Is the timed_mutex approach not acceptable here? It seems like that would provide the ability to sleep, but also interrupt the sleep operation from an outside thread.

Max

**Comment by bsergean** [comment]
https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for <https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for> ?

**Comment by bsergean** [comment]
If you want to be unblocked, yeah you can try to disable the automatic reconnection, but re-implementing it might lead to bugs :)

I prefer not to have to create another thread. I believe that using a condition variable to sleep would give us what we want. I've never used a timed_mutex, I should read about it.

**Comment by bsergean** [comment]
I'm gonna give the condition variable based sleep a 'try' today.

**Comment by bsergean** [comment]
Coded something up -> 78af792f23bac50e1c7b524f378265e8d065416f

Can you give it a try ?

**Comment by maxweisel** [comment]
Ooooh, this looks like a nice solution. I'll try it now.

Max

**Comment by maxweisel** [comment]
This works perfectly! Thanks for the quick response and quick patch!

One small note is that it does cause a connection retry when you call stop(). It might be nice to add a `if (_stop) break;` after the `_sleepCondition.wait_for()` call.

Max

**Comment by bsergean** [comment]
I had prepared this fix but jumped in my train before pushing what extra `_stop break` thing :)

Can you see if this work as you expect it ?

**Comment by maxweisel** [comment]
implementation looks good to me. about to step out for some food, but I'll test it later today! thanks again for the incredibly quick response :)

**Comment by bsergean** [comment]
Sure thing. It's a websocket realtime library so supports needs to be real-time as well :)
I'm glad you brought this up because I had never thought about the problem caused by those long un-interruptible sleeps.

**Comment by maxweisel** [comment]
Just tested and it works perfectly!
