### ISSUE TITLE
gitmodules file is causing problems with cmake ExternalProject_Add

### ISSUE THREAD

**Issue by sethalves** [machinezone/IXWebSocket#154]
I'm trying to include IXWebSocket as a cmake external project with something like
```
    ExternalProject_Add(
        IXWebSocket
        GIT_REPOSITORY https://github.com/machinezone/IXWebSocket.git
        ...
    )
```

This fails because cmake runs `git submodule update --recursive --init` once the checkout is done, which fails like this:

```
$ git clone https://github.com/machinezone/IXWebSocket.git
  ...
$ cd IXWebSocket/
$ git submodule update --recursive --init
fatal: No url found for submodule path 'test/compatibility/C/uWebSockets/uSockets' in .gitmodules
```

and then cmake gives up.

**Comment by bsergean** [comment]
That thing is a subtree, which I experimented with but now I don't know how to kill that thing.

Do you know the git magic to do so ? If you can make a PR or something to remove this dependencies (not needed, was just an experiment to test compatibility with other websocket libraries) that would be much appreciated

**Comment by bsergean** [comment]
Can you try again ?

I typed some git voodoo and it feels like it's fixed.

**Comment by sethalves** [comment]
Yes, I think you've fixed it.  Thanks!
