### ISSUE TITLE
HTTP Client: Payload to short

### ISSUE THREAD

**Issue by Naruk-TUBK** [machinezone/IXWebSocket#155]
With HTTP Requests i always get to short response payloads for GET and PUT requests. The payload is about 1/3 of the expected payload. It is no server Problem because with libcurl it works.
This is my c++ code. Is something wrong with it?

`ix::HttpClient httpClient;
            ix::HttpRequestArgsPtr args = httpClient.createRequest();
            ix::WebSocketHttpHeaders headers;
            headers["Content-Type"] = "application/json";
            args->extraHeaders = headers;
            // Timeout options in seconds
            args->connectTimeout = 4;
            args->transferTimeout = 4;
            ix::HttpResponsePtr out;
            out = httpClient.get("http://localhost:8181/uri", args);
            std::cout << out->payload << std::endl;`

**Comment by bsergean** [comment]
Thanks for reporting this.

What is the server code ?
Could you write a unittest for it, or a minimal server ?
Can you run this against nginx for example, in the GET case ?

I reformatted your code comment:

```
ix::HttpClient httpClient; 
ix::HttpRequestArgsPtr args = httpClient.createRequest(); 
ix::WebSocketHttpHeaders headers; 
headers["Content-Type"] = "application/json"; 
args->extraHeaders = headers; // Timeout options in seconds 
args->connectTimeout = 4; 
args->transferTimeout = 4; 
ix::HttpResponsePtr out; 
out = httpClient.get("http://localhost:8181/uri", args); 
std::cout << out->payload << std::endl;
```

**Comment by Naruk-TUBK** [comment]
I want to access a smart home api from https://github.com/dresden-elektronik/deconz-rest-plugin. I just noticed that i encounter the problem only with there api, therefor it is hard for me to write a test. But i just printed out the response headers with:

    for(auto& header : out->headers) {
        std::cout << header.first << " " << header.second  << "\n";
     }

Header with IXWebsockets:

    Access-Control-Allow-Origin *
    Content-Encoding 
    Content-Length 906
    Content-Type application/json; charset=utf-8
    ETag e545399fd0d2c0a89ceb72c669380d87"

Header with curl (curl http://localhost:8181/uri -i)
     HTTP/1.1 200 OK
    Access-Control-Allow-Origin: *
    Content-Type: application/json; charset=utf-8
    Content-Length:4906
    ETag:"e545399fd0d2c0a89ceb72c669380d87"

It seems the error is that the first digit is missing of the content length. Does this somehow help you? I do not know why this is special to that api

**Comment by bsergean** [comment]
It could be an off by one error in the header parsing code. Ideally there would be a container / docker package I can run to run the server code.

Can you try to type this and tell me what is the output.

ws curl -v http://localhost:8181/uri <http://localhost:8181/uri>

To compile ws type make in the top-folder.

**Comment by bsergean** [comment]
Can you try to add this setting ? It will print more output.

`args->verbose = true;`

**Comment by Naruk-TUBK** [comment]
I have located the problem

Usually a space character is in the header between Content-Length: and the value. In my case the server delivers 

    Content-Length:4906

instead of

    Content-Length: 4906

This could be adjusted in "ixwebsocket/IXWebSocketHttpHeaders.cpp" on line 74. There could be a check if between the header name and the value exists an space character.

Should i write a pull request for it?

**Comment by bsergean** [comment]
Great finding. Sounds like we should fix this.

1. Do you know if the standard require the extra space, or is my code broken ?
2. Feel free to try to make a PR / if you don't have time I'll try to make one. As a test you could try to change the server to remove the extra space when it is writing headers.

**Comment by bsergean** [comment]
Function to patch is 

parseHttpHeaders

**Comment by bsergean** [comment]
// line is a single header entry. split by ':', and add it to our
            // header map. ignore lines with no colon.
            if (colon > 0)
            {
                line[i] = '\0';
                std::string lineStr(line);
                // colon is ':', colon+1 is ' ', colon+2 is the start of the value.
                // i is end of string (\0), i-colon is length of string minus key;
                // subtract 1 for '\0', 1 for '\n', 1 for '\r',
                // 1 for the ' ' after the ':', and total is -4
                std::string name(lineStr.substr(0, colon));
                std::string value(lineStr.substr(colon + 2, i - colon - 4));

                headers[name] = value;
            }

I believe you can replace colon + 2 with colon + 1 for your test case.
We should trim and eliminate spaces before the value.


(found this online, it looks like no space is valid, and that my library is buggy)
HTTP headers let the client and the server pass additional information with an HTTP request or response. An HTTP header consists of its case-insensitive name followed  by a colon (:), then by its value. Whitespace <https://developer.mozilla.org/en-US/docs/Glossary/Whitespace> before the value is ignored.

The most effective way is probably to have a little for loop that loop starting at colon+1, until lineStr[j] is not a space to find where the header starts.

**Comment by Naruk-TUBK** [comment]
1. Seem that the standard does not require an space character https://tools.ietf.org/html/rfc2616#page-32
2. I will write the fix at sunday if you have not fixed it before

**Comment by bsergean** [comment]
Sounds good. Thanks for reporting.

**Comment by bsergean** [comment]
I don't know if you noticed but I pushed a fix for your problem, tell me if it works for you.

**Comment by Naruk-TUBK** [comment]
Yep, i tested it already and it worked fine. Thanks!
