### ISSUE TITLE
A basic example like this isn't working for me

### ISSUE THREAD

**Issue by dexter4life** [machinezone/IXWebSocket#156]
After installing ixwindow from vcpkg, the installation was successful, but when i tried to build with this simple example, nothing happened. Any help?

```
#include <ixwebsocket/IXNetSystem.h>
#include <ixwebsocket/IXWebSocket.h>
#include <iostream>

int main()
{
	ix::initNetSystem();

	// Our websocket object
	ix::WebSocket webSocket;

	std::string url("wss://example.com");
	webSocket.setUrl(url);

	// Optional heart beat, sent every 45 seconds when there is not any traffic
	// to make sure that load balancers do not kill an idle connection.
	webSocket.setHeartBeatPeriod(45);

	// Per message deflate connection is enabled by default. You can tweak its parameters or disable it
	webSocket.disablePerMessageDeflate();

	// Setup a callback to be fired when a message or an event (open, close, error) is received
	webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
		{
			if (msg->type == ix::WebSocketMessageType::Message)
			{
				std::cout << msg->str << std::endl;
			}
		}
	);

	// Now that our callback is setup, we can start our background thread and receive messages
	webSocket.start();

	// Send a message to the server (default to TEXT mode)
	webSocket.send("hello world");

	// The message can be sent in BINARY mode (useful if you send MsgPack data for example)
	webSocket.sendBinary("some serialized binary data");

	// ... finally ...

	// Stop the connection
	webSocket.stop();

	ix::uninitNetSystem();
	return 0;
}
```

**Comment by bsergean** [comment]
This example should probably be improved, but as it is it won't do anything useful.

See the "Open and Close notifications" in the documentation -> https://machinezone.github.io/IXWebSocket/usage/

You can send a message maybe to the server once the connection has been opened, for example. What is it that your client is trying to do, when it connects to a server ?

**Comment by dexter4life** [comment]
Is to connect and then open the bi-directional streaming channel. But instead, it just terminated in a hurry, like some condition internally was tested and return false.

**Comment by dexter4life** [comment]
> The onMessage event will be fired when the connection is opened or closed.  
as stated on the usage documentation, but I tried to tinker around this, where I tested for the Open state but nothing happened. Is there something else I need to do to make it work?

**Comment by dexter4life** [comment]
And the sad part is that it not showing any error. not even an error message. maybe if the connection was wrong or not. It just went straight to this

> somewebsocket.exe (process 26808) exited with code 0.

**Comment by bsergean** [comment]
You need a while loop to wait for messages to be received in your main.

while (true) ;

look at ws_connect.cpp

**Comment by bsergean** [comment]
while (true)
        {
            // Read line
            std::string line;
            auto quit = linenoise::Readline("> ", line);

            if (quit)
            {
                break;
            }

            if (line == "/stop")
            {
                spdlog::info("Stopping connection...");
                webSocketChat.stop();
                continue;
            }

            if (line == "/start")
            {
                spdlog::info("Starting connection...");
                webSocketChat.start();
                continue;
            }

            webSocketChat.sendMessage(line);

            // Add text to history
            linenoise::AddHistory(line.c_str());
        }

This is what ws connect does for example. The main thread should not exit, or the program will just terminate as expected.

**Comment by bsergean** [comment]
@dexter4life I think I provided sufficient help, closing.
