### ISSUE TITLE
"Compressed bit must be 0 if no negotiated deflate-frame extension" in Safari

### ISSUE THREAD

**Issue by hd23408** [machinezone/IXWebSocket#160]
Hello!

We're getting an error when trying to make a WebSocket connection from JavaScript in Safari to a C++ server using the latest version of the IXWebSocket library. The error is as follows:

`Compressed bit must be 0 if no negotiated deflate-frame extension`

We don't get this error as of IXWebSocket's SHA 1bb847a51cc54fc6417831a5a6c8b4e245923b4a but we are getting it with master.

Our suspicion is that it may be related to the per-message deflate compression changes that were made recently. Specifically, it seems that Safari/WebKit does not support per-message deflate (they offer their own "deflate-frame" compression). So, we attempted to turn off per-message deflate in our IXWebSocket server, but we're still getting this error. We're not sure if that means that it's not related to per-message deflate after all, or if it means that we aren't correctly turning it off.

Either way, we thought you'd like to know. For now, we're going to keep using 1bb847a51cc54fc6417831a5a6c8b4e245923b4a. Please let us know if you have any questions or if we can provide any additional information!

**Comment by bsergean** [comment]
Hi Maia,

Thanks for the report. Sorry I broke something recently ... I'm pretty sure that the bad commit is this one:

```
commit 4c66a7561e225103efc9caf262d3224700ccb70b
Author: Benjamin Sergeant <bsergean@gmail.com>
Date:   Tue Feb 18 21:38:28 2020 -0800

    (WebSocketServer) add option to disable deflate compression, exposed with the -x option to ws echo_server
```

The commit right before is 111475e65c30e23bd215db9dff515f88e680895b / so that one should be safe. I'll try to fix that soon. We now have unittest hooked up to github actions btw.

**Comment by bsergean** [comment]
The unittest is green now, I believe that 4ef04b8 has fixed the problem.

**Comment by hd23408** [comment]
Confirmed! Looking good with 4ef04b8. Thanks very much for the amazingly quick turnaround, and for making such a great library! This ticket can be closed from our standpoint.

Cheers!
--maia

**Comment by bsergean** [comment]
Great, thanks for testing and using !
The 'fix' could be polished a bit, I don't know when I'll get to that.

**Comment by samcake** [comment]
Thanks Benjamin!

**Comment by bsergean** [comment]
My pleasure Sam, undoing my previous mistake was a piece of cake 🎂🎂🎂🎂 !
