### ISSUE TITLE
Openssl - Linking Problem

### ISSUE THREAD

**Issue by Naruk-TUBK** [machinezone/IXWebSocket#162]
I developed an application on my mac with LibreSSL 2.8.3 installed. Everything works fine. Now i want to deploy my app on an ubuntu 19.10 (OpenSSL version: OpenSSL 1.1.1c  28 May 2019)  and during linking i get the following error:

> /bin/ld: /usr/local/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): undefined reference to symbol 'SSL_write@@OPENSSL_1_1_0'
/bin/ld: /lib/x86_64-linux-gnu/libssl.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mqttDeconz.dir/build.make:159: bin/mqttDeconz] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/mqttDeconz.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Building IXWebSockets on the same ubuntu works fine (make file in main folder)

**Comment by Naruk-TUBK** [comment]
If i rebuilld ixwebsockets with -DUSE_TLS=1. My app throws following linking error

> /bin/ld: /usr/local/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): undefined reference to symbol 'TLS_server_method@@OPENSSL_1_1_0'
/bin/ld: /lib/x86_64-linux-gnu/libssl.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mqttDeconz.dir/build.make:159: bin/mqttDeconz] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/mqttDeconz.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by bsergean** [comment]
```
$ ls docker
Dockerfile.alpine		Dockerfile.ubuntu_bionic
Dockerfile.centos		Dockerfile.ubuntu_disco
Dockerfile.debian		Dockerfile.ubuntu_xenial
Dockerfile.fedora
```

The docker sub-folder has docker files for a bunch of linux distribution.

To build with docker, you only need to do this:
```
$ ln -sf docker/Dockerfile.centos Dockerfile 
$ make docker
```

Can you try to reproduce your problem like that, so that it is easy for me to figure out what goes wrong ? And post here the Dockerfile for your system.

I think that 19.10 is ubuntu disco, so you can only do

```
ln -sf docker/Dockerfile.ubuntu_disco Dockerfile
make docker
```

And tell me if you see the same problem.

**Comment by Naruk-TUBK** [comment]
Sorry i tracked down the problem to an misconfiguration of conan.io on my ubuntu machine. Thus the depenencies to openssl were not set up properly. But thanks for your help.

**Comment by bsergean** [comment]
Excellent. Glad it was a configuration problem.
