### ISSUE TITLE
Asynchronous version of IXWebSocket::stop()

### ISSUE THREAD

**Issue by maxweisel** [machinezone/IXWebSocket#168]
Heyo,

Still a huge fan of this library. I was curious if it would be possible to get an asynchronous version of IXWebSocket::stop(). At the moment, I create the IXWebSocket instance on my main thread and I use start() to run it. In order to ensure stop() runs as fast as possible, I call close(), wait a few seconds, then I call stop() before deallocating the instance.

However, regardless of what I do to ensure stop() executes as fast as possible, it always takes about 14ms (measured with steady_clock) for stop() to join the thread and terminate, which is too long for my main thread to block as I only have about 11ms of frame time.

I'd love an asynchronous stop() that I can call so that way when I deallocate my IXWebSocket instance and the destructor calls the synchronous version of stop(), it completes instantly.

I'm also open to other ways of architecting this. I'm tempted to run IXWebSocket in blocking mode on my own thread using connect(), but then I lose all of the auto-reconnect with exponential backoff logic.

Max

**Comment by bsergean** [comment]
Thanks for the good words:

When we call stop/close() we wait a little bit to receive the server response. Maybe that’s what can be simplified / disabled with a new option for your use case.

Can you try to change this:

            
        // If we are requesting a cancellation, pass in a positive and small timeout   
        // to never poll forever without a timeout.                                    
        if (_requestInitCancellation)                                                  
        {   
            lastingTimeoutDelayInMs = 100;
        }                                                                              
            
to be lastingTimeoutDelayInMs = 1;

I’m not very keen on making stop asynchronous, as it will make the code harder to reason about. Right now I like to be able to call start and stop in sequences.

But making stop complete as fast as possible is a good goal. Do you have a sample program I could run to simulate your behavior. Maybe as a new ws command (ws bench ?). I can make ws connect report the time it took to close/call stop.

**Comment by bsergean** [comment]
[2020-03-24 20:27:15.228] [info] ws_connect: stop connection completed in 109 ms
[2020-03-24 20:27:15.228] [info] Received 39 bytes
[2020-03-24 20:27:15.229] [info] Sent 12 bytes

[2020-03-24 20:27:02.755] [info] ws_connect: stop connection completed in 108 ms
[2020-03-24 20:27:02.755] [info] Received 39 bytes
[2020-03-24 20:27:02.755] [info] Sent 12 bytes

Added a way to display how much time it takes to disconnect, and it is often just above 100ms for me. Not sure how you manage to get the connection to close in 14ms. (is it for client or server ?).

**Comment by maxweisel** [comment]
I think you're misunderstanding the problem I'm having. My problem isn't with stop() on a live connection it's with stop() on a connection that has already closed successfully.

I believe in your test, stop is calling close() and then waiting for the thread to complete after the close operation completes. It makes sense why your test takes 100ms or longer. In my case however, I'm preemptively calling close() and waiting one second so when I call stop() it should complete immediately as there should be no close() message that needs to go out.

I don't believe the latency I'm seeing with stop() (the 14ms) is from the connection closing, it's from the following steps completing:
1. Set _stop to true and block on _thread to complete.
2. Wait for the OS to schedule the web socket thread.
3. Web socket thread notices _stop is set to true and terminates
4. Wait for the OS to reschedule the main thread so it can be unblocked.

I'd like an asynchronous stop() so my main thread doesn't have to block while waiting for the web socket thread to be scheduled in order to perform its clean-up. Essentially just a version of stop() that sets `_stop` to true so that way the web socket thread exits and any future calls to the synchronous stop() complete immediately (eg when the IXWebSocket destructor runs).

Max

**Comment by maxweisel** [comment]
Hmm, now that I think about it, the thread switch shouldn't be anywhere near that slow. I've definitely confirmed that my connection was successfully closed before calling stop(), but I'm not sure where the slowness is coming from then. Maybe the IXWebSocket::run thread loop is performing more logic than I thought when _stop gets set to true?

**Comment by bsergean** [comment]
Thanks for the clarifications.

I'd like to get a stop sequence run into a profiler like Apple Instruments to trace this.
Maybe littering the run function with printf to see where time is spent is the best next move.

I have other things cooking right now, but I'll try to get to this asap.

**Comment by maxweisel** [comment]
Sounds good. I'll see if I can do some more digging tomorrow too.

Max

**Comment by maxweisel** [comment]
Heyo, digging into this a little bit today. Here's a quick test program I put together that demonstrates the bug.

```
//
//  main.cpp
//  PerformanceTest
//
//  Created by Max Weisel on 3/30/20.
//

#include <iostream>
#include <memory>
#include <chrono>

// IXWebSocket
#include "ixwebsocket/IXWebSocket.h"
#include "ixwebsocket/IXNetSystem.h"

using namespace std;
using namespace std::chrono;
using namespace ix;

int main(int argc, const char * argv[]) {
    ix::initNetSystem();
    
    printf("Start websocket\n");
    unique_ptr<WebSocket> webSocket = make_unique<WebSocket>();
    webSocket->setPingInterval(5);
    webSocket->setOnMessageCallback([](const shared_ptr<WebSocketMessage>& message) { });
    webSocket->setUrl("ws://echo.websocket.org");
    webSocket->start();
    
    // Wait a little bit so the connection can settle.
    printf("Waiting...\n\n");
    usleep(5 * 1000000);

    // Call close
    printf("Close websocket\n");
    webSocket->close();
    
    // Wait a little so the connection can properly close.
    printf("Waiting...\n\n");
    usleep(5 * 1000000);
    
    // Stop the connection and measure execution time
    printf("Stop websocket\n");
    auto start = steady_clock::now();
    webSocket->stop();
    auto end   = steady_clock::now();
    printf("Time: %fms\n", duration<double>(end - start).count() * 1000.0);
    
    // Wait a little so the profiler can profile stop();
    printf("Waiting...\n\n");
    usleep(5 * 1000000);
    
    ix::uninitNetSystem();
    return 0;
}
```

The results on my Mac look like this:
```
Start websocket
Waiting...

Close websocket
Waiting...

Stop websocket
Time: 18.197884ms
Waiting...

Program ended with exit code: 0
```

I tried profiling with instruments, but the stop() symbol doesn't even show up on the radar. I'm going to dive in with steady_clock and see if I can isolate the area that's slow.

Max

**Comment by maxweisel** [comment]
I've modified, IXWebSocket::stop() to look like this:

```
    void WebSocket::stop(uint16_t code, const std::string& reason)
    {
        auto time1 = steady_clock::now();
        close(code, reason);
        auto time2 = steady_clock::now();

        if (_thread.joinable())
        {
            // wait until working thread will exit
            // it will exit after close operation is finished
            _stop = true;
            _sleepCondition.notify_one();
            _thread.join();
            _stop = false;
        }
        auto time3 = steady_clock::now();
        
        printf("Time: %fms %fms %fms\n",
               duration<double>(time2 - time1).count() * 1000.0,
               duration<double>(time3 - time2).count() * 1000.0,
               duration<double>(time3 - time1).count() * 1000.0);
    }
```

And the results I get are:
```
Time: 0.103636ms 11.265504ms 11.369140ms
```

Which leads me to believe my original assumption was correct. The bug is stop() waiting on _thread to join and complete execution. That said, I don't really know why that would take 11ms.

Still digging.

Max

**Comment by bsergean** [comment]
(venv) IXWebSocket$ ws bench             
Start websocket
Waiting...

Close websocket
Waiting...

Stop websocket
Time: 108.319624ms
Waiting...

This is what it reports for me, on my lousy connection.

**Comment by maxweisel** [comment]
I added a few more samples and I can confirm the slowness is the _thread.join() call (as opposed to .joinable() or the sleep condition).

It's always between 11ms and 18ms which is an entire frame of render time for me.

I'm not entirely sure how to solve this one short of making an asynchronous version of stop() that doesn't block on the websocket thread to complete. I'd love to be able to call stop(), and then wait a few seconds before calling the IXWebSocket destructor (which would then call the synchronous stop and complete immediately)

Max

**Comment by maxweisel** [comment]
@bsergean Are you sure that's related to your connection? I'm successfully closing the connection and waiting 5 seconds before calling stop(). The socket should be completely closed before stop() is called. I can also confirm that inside of the stop() call that when it calls close() that close() completes immediately.

Max

**Comment by bsergean** [comment]
I'm adding some printf. I can see that after stop is called, I still get called 3 times in checkConnection. Maybe _stop has not been set yet ...

        // Try to connect perpertually
        while (true)
        {
            std::cerr << "in checkConnection" << std::endl;



in checkConnection
in checkConnection
in checkConnection
in checkConnection
in checkConnection
Stop websocket
in checkConnection
in checkConnection
in checkConnection
Time: 111.128510ms
Waiting...

**Comment by maxweisel** [comment]
Hmm, I wonder if _stop needs synchronization around it to ensure it's not being cached.

Max

**Comment by bsergean** [comment]
I think this is the thing that is bugging you.

            // We can avoid to poll if we want to stop and are not closing
            if (_stop && !isClosing()) break;

**Comment by maxweisel** [comment]
So the bug is that I call close(), the connection is technically closed, but the readyState isn't updated until the connection is polled a few more times?

I don't understand why that part doesn't happen during the 5 second period between close() and stop().

Max

**Comment by bsergean** [comment]
You can look at this too -> closingDelayExceeded()

I tried to set one constnat to 1ms but it didn't make too much difference.

The closing sequence has a timeout to be able to try to retrieve a code from the server. Maybe we could optimize this if close has been sent already.

**Comment by bsergean** [comment]
If I do this:

#if 0
            // We can avoid to poll if we want to stop and are not closing
            if (_stop && !isClosing()) break;
#else
            if (_stop) break;
#endif

Stop websocket
in WebSocket::run() stop: 1
in checkConnection stop: 1
Time: 0.306722ms
Waiting...

Now it take 0.30 ms to close (with a debug build)

**Comment by maxweisel** [comment]
I'd imagine 5 seconds would be enough time for any connection to close. I don't think the issue is that the connection isn't closed, it's that IXWebSocketTransport doesn't update the readyState to mark the connection closed properly.

It looks like the only segment that can mark the stream as closed is this one:
https://github.com/machinezone/IXWebSocket/blob/0fffb1e89472954cb8b71e05c1a6ea5cea287732/ixwebsocket/IXWebSocketTransport.cpp#L310

Which will only mark the connection closed if the closingDelayExceeded() is true which seems like a bug. I imagine if the connection closes cleanly we shouldn't need to check a delay at all?

Max

**Comment by maxweisel** [comment]
@bsergean that fix would work for me. Is it possible for it to introduce any other bugs? that fix means the thread would complete and IXWebSocket() could be deallocated before IXWebSocketTransport fully marks the connection as CLOSED. I'm not sure if that could be an issue.

Max

**Comment by bsergean** [comment]
I'm not proposing any fix yet, I'm just experimenting to see how the close code behaves :)

**Comment by maxweisel** [comment]
Sounds good. I'll let you play around with it. I think I'm in over my head on this one now =P

Let me know if there's anything you'd like me to test out on my end.

Max

**Comment by bsergean** [comment]
in WebSocket::run() stop: 0 OPEN
in checkConnection stop: 0
Close websocket
Waiting...

in WebSocket::run() stop: 0 CLOSING
in checkConnection stop: 0
in WebSocket::run() stop: 0 CLOSED
in checkConnection stop: 0
Stop websocket
Time: 0.020777ms
Waiting...



        // Call close
        printf("Close websocket\n");
        webSocket->disableAutomaticReconnection();
        webSocket->close();

Can you try to disable the automatic reconnection thing, before closing ?

I'm printing the connection state and I think you get reconnected after you call close().

**Comment by maxweisel** [comment]
Yeah, let me test that out real quick.

Max

**Comment by maxweisel** [comment]
That did it!! Nice!!

Max

**Comment by bsergean** [comment]
I think the confusion could be eliminated if #172 is fixed.

For now the workaround is to call disableAutomaticReconnection before calling close.

**Comment by maxweisel** [comment]
Sounds good!
