### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#17]
It would be cool/great to be able to install ws with homebrew.

https://github.com/Homebrew/homebrew-core/pull/37464

**Comment by dhruvkakadiya** [comment]
Below commands(as per README file) worked for me so this looks like resolved now. It's installing `1.3.0` version.
```
brew tap bsergean/IXWebSocket
brew install IXWebSocket
```

**Comment by bsergean** [comment]
Yes I think we're good here. I should update to the latest code so, in a different ticket I think.
