### ISSUE TITLE
MingW build failed

### ISSUE THREAD

**Issue by zzzz-qq** [machinezone/IXWebSocket#171]
It seems some Win32 headers(`<WS2tcpip.h>` , `<BaseTsd.h>`) should be lower case in MingW.
Is MingW supposed to be supported by IXWebSocket?
If MingW is supported, its trival to fix these include errors. But MingW do NOT support std::thread, [mingw-std-threads](https://www.github.com/meganz/mingw-std-threads) may be needed.

MingW compile logs:
```
In file included from /home/ubuntu/ws/IXWebSocket/ixwebsocket/IXNetSystem.cpp:7:0:
/home/ubuntu/ws/IXWebSocket/ixwebsocket/IXNetSystem.h:10:22: fatal error: WS2tcpip.h: No such file or directory
compilation terminated.
IXWebSocket/CMakeFiles/ixwebsocket.dir/build.make:192: recipe for target 'IXWebSocket/CMakeFiles/ixwebsocket.dir/ixwebsocket/IXNetSystem.cpp.obj' failed
make[2]: *** [IXWebSocket/CMakeFiles/ixwebsocket.dir/ixwebsocket/IXNetSystem.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 71%] Built target zlib
In file included from /home/ubuntu/ws/IXWebSocket/ixwebsocket/IXDNSLookup.cpp:9:0:
/home/ubuntu/ws/IXWebSocket/ixwebsocket/IXNetSystem.h:10:22: fatal error: WS2tcpip.h: No such file or directory
compilation terminated.
IXWebSocket/CMakeFiles/ixwebsocket.dir/build.make:122: recipe for target 'IXWebSocket/CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.obj' failed
make[2]: *** [IXWebSocket/CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.obj] Error 1
In file included from /home/ubuntu/ws/IXWebSocket/ixwebsocket/IXSocket.cpp:7:0:
/home/ubuntu/ws/IXWebSocket/ixwebsocket/IXSocket.h:17:21: fatal error: BaseTsd.h: No such file or directory
```

**Comment by bsergean** [comment]
If it's trivial to add MingW support I'm not against it. 

I clicked on your link and they say that: "It seems that recent versions of MinGW-w64 include a Win32 port of pthreads"

That part looks ok to integrate the project, we can add a small blob for that in the CMakeList.
option(MINGW_STDTHREADS_GENERATE_STDHEADERS "" ON)
add_subdirectory(mingw_stdthreads)
target_link_libraries(${TARGET} PRIVATE mingw_stdthreads)
If you want to make a pull request for it please do. Worst case I can reference your fork as a way to get MingW support if merging is too complicated.

On requirement is that I don't want to have ifdef around mutex, thread etc.. includes.

**Comment by bsergean** [comment]
The Windows page reference those headers as mixed case, I'm not sure I want to deviate from the normal expected windows way.

https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types

I'm gonna close this to keep the number of issues low, I don't think that supporting mingw is very high on my radar or will ever be, sorry ...
