### ISSUE TITLE
vcpkg version is still 7.9.2. Can it be updated to the latest?

### ISSUE THREAD

**Issue by bigbang1976** [machinezone/IXWebSocket#173]
Great project. Finally have it working for my use case. Would be great to be able to get the latest through vcpkg. I currently only see 7.9.2.

Thanks 
Ferry

**Comment by bsergean** [comment]
Thanks !
Just make a request to update to the latest version.

**Comment by bigbang1976** [comment]
Got it working.

**Comment by bigbang1976** [comment]
although my git pull provides version 8.0.5. I am new to this. Any pointers? Thanks.

**Comment by bsergean** [comment]
When #10633 is merged you will be good.

If you can checkout a branch of vcpkg, you can maybe pull my branch.

**Comment by bsergean** [comment]
#10633 is the ticket on the vcpkg page. It usually take a bit of time for such tickets to be merged.

If you want you can try to use the vcpkg I used to make the PR.
https://github.com/bsergean/vcpkg/tree/feature/ixwebsocket_9.1.9

**Comment by bsergean** [comment]
Hey @bigbang1976 the latest version is now 9.1.9, which is more current.

Please give it a try and tell me if it works for you.

**Comment by bigbang1976** [comment]
I got 9.1.9 working. Many thanks. One question on auto reconnect. Is it normal that this takes 5 to 7 retries? I use ix to connect to an AWS backend and at the two hour mark (max connection duration on AWS) it seems there are quite a few attempts before a new connection is successful. Connection gets a close msg on these first attempts.

**Comment by bsergean** [comment]
It is normal behavior.

If you want to stay connected, you should enable the heartbeat/ping-pong system, and send ping at a given frequency (45 seconds for example).

webSocket.setPingInterval(45);

Load balancers, such as the amazon ones (ELB) usually disconnects inactive/idle connections after a certain time (5 minutes but it can be lower).
