### ISSUE TITLE
Add support for supplying SSL CA from memory

### ISSUE THREAD

**Issue by maxweisel** [machinezone/IXWebSocket#174]
Heyo,

I'm using IXWebSocket with a websocket service that's over HTTPS. The service uses letsencrypt, and on platforms like macOS and iOS, it works perfectly. The system Security.framework can verify the certificate using the system's trusted CAs.

However, on Windows, it fails to verify the chain. As far as I know, mbedtls and openssl do not have the ability to automatically load system trusted CAs on Windows. My project already compiles a static version of openssl, so on non-Apple platforms, I'm using USE_OPENSSL instead of mbed_tls.

I'd love to implement an API on IXSocketTLSOptions that allows you to specify a CA or cert/key pair from memory. I'm happy to write the implementation for this. I figured I'd write up a github issue in case you have any opinions on how I should go about implementing it.

Max

**Comment by maxweisel** [comment]
While digging into this, I found that I can implement manual loading of the Windows system CA chain into memory, which I can then load into OpenSSL. Unfortunately though, they're not nice PEM files on disk, so I'd still need an API to be able to pass certificates from memory into IXWebSocket.

**Comment by bsergean** [comment]
(A)
The simplest way at this point is to bundle a 'ca-cert' with the app (the one from firefox, 're-bundled' by curl).

https://curl.haxx.se/docs/caextract.html

And then pass a tls-option on windows.

This is what we do on Android. At app start you can copy the file somewhere if needed, or just set the path to the file.

This is documented here -> https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration


(B)
If A is not an option, there's a way to use the windows API to help load the system certs. I've seen code like that but I'm not sure on what is the best way to do it, and I'like to keep the platform specific code clean, like having the windows only things in their own file etc... 

https://github.com/satori-com/satori-rtm-sdk-c/blob/master/core/src/ssl/rtm_openssl.c

I think this code has good stuff to get in the openssl_load_windows_certificates function. I would have to think about the best way to expose it. We already have a 'SYSTEM' special value for the ca-cert.

**Comment by bsergean** [comment]
Actually we could pretty much use openssl_load_windows_certificates as is. It just load the certs using the windows api, and populate the openssl cert store.

I can look into that or you can if you want.

What I'd really like to have is the unitest enabled on windows, with GitHub actions. If you could help with that that would be great ; I'd like to use vcpkg to install dependencies, I think I'm pretty close.

**Comment by maxweisel** [comment]
openssl_load_windows_certificates sounds amazing for Windows. However, on Android, I'd still need the ability to load the CA from memory. I'm not actually distributing an app, but a plugin that is a single shared library. I'm unable to bundle any files on disk with it, and in many cases where it's used, I cannot write files to disk either.

Max

**Comment by bsergean** [comment]
Can you execute java / access JNI code on Android ?

If you are focusing on OpenSSL, and cannot write to a temp file (are you sure about that ?).

https://jayrambhia.com/blog/android-fileprovider-ecosystem

You might need to look at the guts of  SSL_load_client_CA_file, and see how you can produce the same output it does (STACK_OF(X509_NAME) * rootCAs) from memory.

**Comment by bsergean** [comment]
Before digging too hard, I would check if your plugin/dso can execute this code early on. All the Android doc I found says that no permissions are required for those API, since this is writing to the internal storage.

Do you have docs on the restrictions, with your plugin ?

            // getPath() - java
        JNIEnv *jni_env = Core::HAZEOS::GetJNIEnv();
        jclass cls_Env = jni_env->FindClass("android/app/NativeActivity");
        jmethodID mid_getExtStorage = jni_env->GetMethodID(cls_Env, "getFilesDir","()Ljava/io/File;");
        jobject obj_File = jni_env->CallObjectMethod( gstate->activity->clazz, mid_getExtStorage);
        jclass cls_File = jni_env->FindClass("java/io/File");
        jmethodID mid_getPath = jni_env->GetMethodID(cls_File, "getPath","()Ljava/lang/String;");
        jstring obj_Path = (jstring) jni_env->CallObjectMethod(obj_File, mid_getPath);
        const char* path = jni_env->GetStringUTFChars(obj_Path, NULL);
        FHZ_PRINTF("INTERNAL PATH = %s\n", path);
        jni_env->ReleaseStringUTFChars(obj_Path, path);


Or the cache dir


        mid_getExtStorage = jni_env->GetMethodID( cls_Env,"getCacheDir", "()Ljava/io/File;");
        obj_File = jni_env->CallObjectMethod(gstate->activity->clazz, mid_getExtStorage, NULL);
        cls_File = jni_env->FindClass("java/io/File");
        mid_getPath = jni_env->GetMethodID(cls_File, "getAbsolutePath", "()Ljava/lang/String;");
        obj_Path = (jstring) jni_env->CallObjectMethod(obj_File, mid_getPath);
        path = jni_env->GetStringUTFChars(obj_Path, NULL);
        FHZ_PRINTF("CACHE DIR = %s\n", path); 
        jni_env->ReleaseStringUTFChars(obj_Path, path);

**Comment by maxweisel** [comment]
My apologies, I should've been clearer. We support other platforms besides Android too where we have no filesystem write access. My thinking is that if I need to write a method that loads a cert from memory for those platforms, I might as well just use that implementation for Android as well. We don't gain anything by adding a special case like this if we already have the other implementation working.

**Comment by maxweisel** [comment]
Both mbedtls and openssl have methods for loading certs from memory. I would love to write an implementation for ixwebsocket that exposes that feature.

**Comment by bsergean** [comment]
It would be much appreciated to have such a feature. The first place to look at for how we're gonna pass that is

IXSocketTLSOptions.h

I wonder if we need a new boolean, something like 'in-memory', or if we replicate the 3 settings (caFile, certFile, keyFile).

or if we _just_ support loading ca-cert from memory, and forget about certFile and keyFile.

We will want a unitest for this, exposing the option to the command line tool, and making sure this works for server + client.

ps:
I still think we should add openssl_load_windows_certificates code, because some users only care about one platform. People who only work on Windows would benefit from this. I might start coding this.

**Comment by maxweisel** [comment]
Sounds good! I can take a crack at drafting up an API for IXSocketTLSOptions and if it looks good I can start on an implementation.

**Comment by maxweisel** [comment]
Something else that might be worth thinking about is updating these certs while the server is running. Node's ws api only allows loading cert/key from memory, and they support swapping the cert/key on a live server for new connections. This has been useful for our servers that use letsencrypt where your cert/key needs to be updated every two months and you don't want to experience any downtime during the update process.

Max

**Comment by bsergean** [comment]
You can also work 'bottom up' and start by coding things in the OpenSSL/mbedtls files directly.

I don't really mind :)

I might refactor your code a bit so that it fits my mental model well ultimately, but I'll make sure things works just fine.

In your case, would you make the certs data a big static array, that will be passed to the api ?
That static array would be a file that is built into the app ; I've seen that pattern before.

**Comment by bsergean** [comment]
That would be a nice to have, but the server code doesn't have a 'reload' tls option yet.

I think that restarting the server would make things easier from a code standpoint / clients should auto-reconnect in any case during any forms of server updates.

**Comment by maxweisel** [comment]
Awesome, I'll start by modifying the OpenSSL wrapper directly and work my way back up through the stack.

afaik you can combine multiple CAs in a single file. My API would be the equivalent but the file is just stored in a std::string. I'm figure I'm just doing the file load portion that OpenSSL does on your behalf.

As far as changing the cert goes, on our services we have 1000s of connections live at all times and breaking those to update our cert/key every two months would be unacceptable as our sessions aren't as easily resumed. I don't think we need to implement this feature now, but it was something I wanted to take into account when making modifications to IXSocketTLSOptions.

Max

**Comment by maxweisel** [comment]
Boooooom. I got a sec and was able to get OpenSSL working with root CAs from memory. I'll plan to clean it up and throw up a branch tomorrow for feedback before I implement the IXSocketTLSOptions part.

**Comment by bsergean** [comment]
Excellent !

**Comment by bsergean** [comment]
I implemented the Windows default store thing in the meantime -> f9d75c937408b80aa4f5ff0551582d016298eda4

If you can / want to give it a try that would be great.

**Comment by maxweisel** [comment]
Apologies for the delay, I wasn't able to work on this last week.

I cleaned up my loading implementation and opened a PR here: https://github.com/machinezone/IXWebSocket/pull/178

It works great, but the API for specifying a set of root CAs via a string feels really awkward. That said, the only ways I can think to fix would break previous builds.

Let me know what you think I should do API-wise on SocketTLSOptions and I'll finish up this PR.

Max
