### ISSUE TITLE
Add support for local statically linked openssl

### ISSUE THREAD

**Issue by maxweisel** [machinezone/IXWebSocket#175]
At the moment CMakeLists.txt uses find_package() to find OpenSSL. Which works great if it's installed on your system. However, in my project, I already compile and link against a static library copy of openssl, so I'd like to just use those symbols for IXWebSocket.

find_package(OpenSSL) does support searching for static libraries, but this has to be done at cmake generate time which means even if my cmake project builds openssl, the static library needs to be present before I can even run `make` which is before I'd be able to compile openssl myself and so find_package(OpenSSL) will always fail.

I'd love to be able to specify something like OPENSSL_INCLUDE myself. I'm compiling a static library version of ixwebsocket, so I don't even really need the project to do any linking for me. All it really needs are the headers for the openssl library I'm using in my project.

I'm happy to implement this and open a PR, I figured I'd file a github issue in case you had any opinions on how you'd like to integrate this into the project.

Max

**Comment by maxweisel** [comment]
I'm thinking I might just switch from add_subdirectory to ExternalProject_Add. This would allow me to save all IXWebSocket cmake configuration until build time. I'll experiment with that, but I think add_subdirectory is most likely still the correct way for me be using ixwebsocket in a cmake project, so I'd love to be able to continue with that direction if possible.

Max

**Comment by bsergean** [comment]
I'm not a cmake expert so I'm open to suggestions on changing this, but I'd like to follow existing patterns from 'grown ups' packages like curl.

There are existing users so we should find a way not to break them as well. One users do use ExternalProject_Add I believe, but I don't know much about it.

Here is how curl is doing it, and they have lots of similarity with this project
https://github.com/curl/curl/blob/master/CMakeLists.txt

**Comment by bsergean** [comment]
Another assumption I have is that people can just 'include' the ixwebsocket folder, and thing should work.

**Comment by maxweisel** [comment]
afaik curl uses autoconf / make, which supports specifying an openssl path with `--with-ssl`: https://curl.haxx.se/docs/install.html. I believe their CMake implementation was more for people who wanted to easily include it in their own repo, but it's not a complete reimplementation of their main build system.

I think the simple approach would be to look for a variable like STATIC_OPENSSL_INCLUDE if it's not present, default back to the find_package() approach.

Another small change that would help would be to split the ixwebsocket and CLI targets into separate CMakeList.txt files that are all included in a root CMakeLists.txt via add_subdirectory(). Then you can use find_package() in the CLI where you need to link against system openssl, and IXWebSocket will only need to reference headers. It also means I could use add_subdirectory() on just the library instead of the whole project.

Max

**Comment by bsergean** [comment]
It turns out that this should already be possible.

1. set OPENSSL_FOUND to 1.

2. Manually set those values:
* OPENSSL_DEFINITIONS
* OPENSSL_INCLUDE_DIR
* OPENSSL_LIBRARIES

the block that deals with openssl has a way not to trigger find_package

```
    # This OPENSSL_FOUND check is to help find a cmake manually configured OpenSSL
    if (NOT OPENSSL_FOUND)
      find_package(OpenSSL REQUIRED)
    endif()
    message(STATUS "OpenSSL: " ${OPENSSL_VERSION})

    add_definitions(${OPENSSL_DEFINITIONS})
    target_include_directories(ixwebsocket PUBLIC ${OPENSSL_INCLUDE_DIR})
    target_link_libraries(ixwebsocket ${OPENSSL_LIBRARIES})
```
