### ISSUE TITLE
leaks using openssl 1.1.1 

### ISSUE THREAD

**Issue by amc723** [machinezone/IXWebSocket#176]
First, thanks for this project. We don't use boost, and I ported over from easyws, and the interface for ixwebsocket is super easy to use!

I'm compiling with VS2017, and have linked a couple different versions of OpenSSL (1.1.1d, 1.1.1e, 1.1.1f). Previously using 1.1.0i. I was able to duct tape CMakeLists.txt to allow static linkage (looks like someone here who knows CMake better than me is already looking into easier openssl static linkage)... 

After the 1.1.0 to 1.1.1 update, with TLS enabled, CRT is finding memory leaks:

```
{71604} normal block at 0x00000202A5736F80, 520 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{71524} normal block at 0x00000202B1642F10, 12 bytes long.
 Data: <            > 00 00 00 00 01 00 00 00 00 00 00 00 
{71523} normal block at 0x00000202A5738B40, 520 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{26175} normal block at 0x00000202A3E809F0, 12 bytes long.
 Data: <            > 00 00 00 00 01 00 00 00 00 00 00 00 
{26174} normal block at 0x00000202A0EFEA00, 520 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
minkernel\crts\ucrt\src\appcrt\locale\setlocale.cpp(64) : {14607} crt block at 0x00000202A0EB9E40, subtype 0, 6 bytes long.
 Data: <    C > 01 00 00 00 43 00 
minkernel\crts\ucrt\src\appcrt\locale\wsetlocale.cpp(473) : {14605} crt block at 0x00000202A0EEDA10, subtype 0, 344 bytes long.
 Data: <                > D0 F3 FB 0E F6 7F 00 00 01 00 00 00 00 00 00 00 
{14353} normal block at 0x00000202A0ECD6A0, 264 bytes long.
 Data: <    3 ]YAIr ^"(2> E4 E8 88 91 33 91 5D 59 41 49 72 11 5E 22 28 32 
{14096} normal block at 0x00000202A0ECD2B0, 264 bytes long.
 Data: < u          yV E> 1F 75 D5 A2 C5 E8 81 8D 9B E6 14 BC 79 56 14 45 
{11582} normal block at 0x00000202A0E566C0, 48 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{11581} normal block at 0x00000202A0CCEC60, 64 bytes long.
 Data: < f              > C0 66 E5 A0 02 02 00 00 00 00 00 00 00 00 00 00 
{11572} normal block at 0x00000202A0C950B0, 264 bytes long.
 Data: <                > 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 
{11571} normal block at 0x00000202A0EC9220, 160 bytes long.
 Data: <                > 90 FC FF 0E F6 7F 00 00 00 00 00 00 00 00 00 00 
{11570} normal block at 0x00000202A0EC9920, 160 bytes long.
 Data: <                > 90 FC FF 0E F6 7F 00 00 00 00 00 00 00 00 00 00 
{11569} normal block at 0x00000202A0E63F50, 360 bytes long.
 Data: <         a      > 00 00 00 00 00 00 00 00 80 61 C6 A0 02 02 00 00 
{11565} normal block at 0x00000202A0E563B0, 48 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{11564} normal block at 0x00000202A0CCE460, 64 bytes long.
 Data: < c              > B0 63 E5 A0 02 02 00 00 00 00 00 00 00 00 00 00 
{11555} normal block at 0x00000202A0C94E10, 264 bytes long.
 Data: <                > 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 
{11554} normal block at 0x0000020298831240, 160 bytes long.
 Data: <                > 90 FC FF 0E F6 7F 00 00 00 00 00 00 00 00 00 00 
{11553} normal block at 0x00000202A0C6F880, 160 bytes long.
 Data: <                > 90 FC FF 0E F6 7F 00 00 00 00 00 00 00 00 00 00 
{11552} normal block at 0x00000202A0D64100, 360 bytes long.
 Data: <         a      > 00 00 00 00 00 00 00 00 80 61 C6 A0 02 02 00 00 
{6516} normal block at 0x00000202A0D5C890, 12 bytes long.
 Data: <            > 00 00 00 00 01 00 00 00 01 00 00 00 
{6515} normal block at 0x00000202A0E02AF0, 520 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

CRT blocks are false positives.

This was a relatively short run, but over time more 520 byte followed by 12 byte allocs will appear like these:

```
{71524} normal block at 0x00000202B1642F10, 12 bytes long.
 Data: <            > 00 00 00 00 01 00 00 00 00 00 00 00 
{71523} normal block at 0x00000202A5738B40, 520 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

If I recompile with openssl 1.1.0i or mbedtls, there are no leaks.

Possibly related to #91? But I would expect to see leaks in openssl 1.1.0 and 1.1.1 in that case.

I'm not terribly familiar with the openssl api but may be able to take a look at this. Would it be around `IXSocketOpenSSL.cpp`?

**Comment by bsergean** [comment]
Thanks for the good words. We also started with easyws (what a great project, very simple with one file) but then modified things a lot over the last 3 years now ...

Back to the leak … I’m not sure where to start, maybe making a debug build of OpenSSL with symbols would help CRT tools ?
All of that takes place indeed in IXSocketOpenSSL.cpp

There are a couple of ifdef for some version of OpenSSL, so I would look there first.

#if OPENSSL_VERSION_NUMBER >= 0x10002000L
            // Support for server name verification
            // (The docs say that this should work from 1.0.2, and is the default from
            // 1.1.0, but it does not. To be on the safe side, the manual test
            // below is enabled for all versions prior to 1.1.0.)
            X509_VERIFY_PARAM* param = SSL_get0_param(_ssl_connection);
            X509_VERIFY_PARAM_set1_host(param, host.c_str(), 0);
#endif

That one for example. Btw that version check does not make sense to me … it’s hard to read those hex bytes and make sense of them.

I think the other ‘leak’ ticket is unrelated.

There is a ‘leak sanitizer’ clang tool, which we could try to enable on Linux/macOS to help here.

**Comment by amc723** [comment]
ahh good idea... I'll see if I can make a debug ossl build with CRT enabled. That would definitely help track it down.

I don't have easy access to a linux or mac dev env at the moment, but I'll see what I can find on Windows.

Thanks for the quick response!

**Comment by bsergean** [comment]
Good luck. I don’t have easy access to a Windows machine myself so it’s hard to help here. You could try to run the unittest (see the makefile, it has to be run from the test folder, and use USE_TLS=1 USE_TEST=1 when ‘cmaking’.

Something I could do too is run the unittest through valgrind, which is good at reporting memory errors.

**Comment by bsergean** [comment]
I just compiled the library with openssl 1.1.1d on macOS, and ran the 'leaks' tool.

```
make test_openssl
cd tests
leaks --atExit -- ../build/test/ixwebsocket_unittest http_client
```

This outputs:

```
Process:         ixwebsocket_unittest [96119]
Path:            /Users/USER/*/ixwebsocket_unittest
Load Address:    0x10d7ca000
Identifier:      ixwebsocket_unittest
Version:         ???
Code Type:       X86-64
Parent Process:  leaks [96118]

Date/Time:       2020-04-13 18:13:39.734 -0700
Launch Time:     2020-04-13 18:13:36.656 -0700
OS Version:      Mac OS X 10.15.3 (19D76)
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         2652K
Physical footprint (peak):  2668K
----

leaks Report Version: 4.0
Process 96119: 655 nodes malloced for 74 KB
Process 96119: 0 leaks for 0 total leaked bytes.
```

**Comment by amc723** [comment]
Thanks! I'm still sorting through this on my end - I have an idea of what's happening but haven't been able to confirm.

I was able to use [VLD](https://kinddragon.github.io/vld/) which pointed straight to the leak in some unexpected places around ixwebsocket using openssl. I realized a dll I'm linking statically links openssl, so I have two statically linked openssl versions in my final executable. The dll is using openssl 1.1.0, and I'm linking openssl 1.1.1 to the exe.

When I stub out my dll or don't load it, I don't see leaks, so I think it's safe to assume this isn't a bug in ixwebsocket, and those statically linked openssl libs might be conflicting with each other...

Apologies for the red herring... I think it's safe to close this as a non-issue.

**Comment by bsergean** [comment]
Ah that's interesting. I've seen odd behaviors like that in the past with 'double linking'.

I just looked up how to work with find_library, and this might help find the openssl of the 'dll' your using.

```
list(APPEND CMAKE_PREFIX_PATH "/tmp/test" "/another/library/path")
```

If everything still break, one hacky option might be to use mbedtls with ixwebsocket, so that you leave the other runtime your using alone.
