### ISSUE TITLE
Compiling on Ubuntu 

### ISSUE THREAD

**Issue by sathaadj** [machinezone/IXWebSocket#177]
I am compiling the repo in Ubuntu 16.04 and i get the following error, please help me resolve it:

mkdir build
cd build
cmake -DUSE_TLS=1 ..
-- OpenSSL: 1.0.2g
-- OpenSSL: 1.0.2g
-- Could NOT find jsoncpp (missing:  JSONCPP_LIBRARY JSONCPP_INCLUDE_DIRS) 
-- Could NOT find jsoncpp (missing:  JSONCPP_LIBRARY JSONCPP_INCLUDE_DIRS) 
-- Could NOT find jsoncpp (missing:  JSONCPP_LIBRARY JSONCPP_INCLUDE_DIRS) 
-- Could NOT find spdlog (missing:  SPDLOG_LIBRARY SPDLOG_INCLUDE_DIRS) 
-- Build spdlog: 1.5.0
-- Build type: Debug
CMake Error at third_party/spdlog/cmake/utils.cmake:33 (if):
  if given arguments:

    "MSVC_VERSION" "GREATER_EQUAL" "1910"

  Unknown arguments specified
Call Stack (most recent call first):
  third_party/spdlog/CMakeLists.txt:120 (spdlog_enable_warnings)

-- Configuring incomplete, errors occurred!

**Comment by bsergean** [comment]
ln -sf docker/Dockerfile.ubuntu_xenial Dockerfile
make docker

I'm trying to repro your problem like that, with docker. The error is in a third-party library, spdlog. Maybe updating spdlog would help, you can try it. Download the latest spdlog version and put it in third_party. Will try that.

**Comment by bsergean** [comment]
I think that the default CMake for Ubuntu 16.04 might be too old.

My Dockerfile download a more recent CMake and everything works fine

RUN apt-get update
RUN apt-get -y install wget
RUN mkdir -p /tmp/cmake
WORKDIR /tmp/cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz
RUN tar zxf cmake-3.14.0-Linux-x86_64.tar.gz

RUN apt-get -y install g++
RUN apt-get -y install libssl-dev
RUN apt-get -y install libz-dev
RUN apt-get -y install make
RUN apt-get -y install python

COPY . .

ARG CMAKE_BIN_PATH=/tmp/cmake/cmake-3.14.0-Linux-x86_64/bin
ENV PATH="${CMAKE_BIN_PATH}:${PATH}"

**Comment by bsergean** [comment]
Can you report the cmake version you're using  ?

**Comment by sathaadj** [comment]
@bsergean  thanks for your reply.
I have commented that section of CMakeLists.txt under spdlog under thirdparty to get it compiling.
I am using  CMake version 3.5.1
Can you help me with a minimal "wss://url" client.... I am struggling to see why the below code would not work 

#include <ixwebsocket/IXWebSocket.h>

...

// Our websocket object
ix::WebSocket webSocket;

std::string url("ws://localhost:8080/");
webSocket.setUrl(url);

// Optional heart beat, sent every 45 seconds when there is not any traffic
// to make sure that load balancers do not kill an idle connection.
webSocket.setPingInterval(45);

// Per message deflate connection is enabled by default. You can tweak its parameters or disable it
webSocket.disablePerMessageDeflate();

// Setup a callback to be fired when a message or an event (open, close, error) is received
webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
    {
        if (msg->type == ix::WebSocketMessageType::Message)
        {
            std::cout << msg->str << std::endl;
        }
    }
);

// Now that our callback is setup, we can start our background thread and receive messages
webSocket.start();

// Send a message to the server (default to TEXT mode)
webSocket.send("hello world");

// The message can be sent in BINARY mode (useful if you send MsgPack data for example)
webSocket.sendBinary("some serialized binary data");

// ... finally ...

// Stop the connection
webSocket.stop()

I am able to see that all the functions are executed without issues but the WSS on the server is not receiving anything

**Comment by bsergean** [comment]
Can you make a different ticket, since this is a different problem ?

Try to connect to your server with 

ws connect 'wss://example.com' 

And replace your url in there. Have you setup SSL correctly on your server ?
Is the server public, can I access the url ?

**Comment by sathaadj** [comment]
@bsergean 
Just thought to update on this issue,  have compiled the following code using
cmake -H. -Bbuild -DUSE_TLS=1 -DUSE_OPEN_SSL=1
cmake --build build -- -j3

Client code looks like below:
#include <ixwebsocket/IXWebSocket.h>
#include <iostream>
#include <unistd.h>

int main(void)
{

    // Our websocket object
    ix::WebSocket webSocket;

   std::string url("wss://echo.websocket.org");
    std::cout<<"Connecting to the WSS"<<std::endl;
    webSocket.setUrl(url);

    // Optional heart beat, sent every 45 seconds when there is not any traffic
    // to make sure that load balancers do not kill an idle connection.
    webSocket.setPingInterval(45);

    // Per message deflate connection is enabled by default. You can tweak its parameters or disable it
    webSocket.disablePerMessageDeflate();

    // Setup a callback to be fired when a message or an event (open, close, error) is received
    webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
        {
            if (msg->type == ix::WebSocketMessageType::Message)
            {
                std::cout << msg->str << std::endl;
            }
        }
    );

    std::cout<<"WSS start"<<std::endl;
    // Now that our callback is setup, we can start our background thread and receive messages
    webSocket.start();

    std::cout<<"Sending Hello"<<std::endl;
    // Send a message to the server (default to TEXT mode)
    webSocket.send("hello world");

    while(1)
    {
        sleep(1);
        std::cout<<"Sending Hello"<<std::endl;
        // Send a message to the server (default to TEXT mode)
        webSocket.send("hello world");
    }

    // ... finally ...

    std::cout<<"Stopping"<<std::endl;
    // Stop the connection
    webSocket.stop();
}

compiled using
c++ Test.cpp -std=c++11 -I~/IXWebSocket -lixwebsocket -L~/IXWebSocket -lssl -lcrypto -lz -lpthread

Now i can get the message sent from this client on server.

**Comment by bsergean** [comment]
Cool, thanks for the update.
