### ISSUE TITLE
Add clang-format pre-commit-hook

### ISSUE THREAD

**Issue by pocc** [machinezone/IXWebSocket#179]
This is something you expressed interest in in https://github.com/pocc/pre-commit-hooks/issues/13. 

PR incoming.

**Comment by bsergean** [comment]
Excellent. I gave your hook a quick try but was too lazy to troubleshoot what wasn't working.

This is the pre-commit I have out of curiosity.
```
$ pre-commit --version
pre-commit 2.1.0
```

What's important for me is that my .clang-format get picked up, so that the style is the one I've been using for a while.

**Comment by pocc** [comment]
Side note:  Your YAML checker, `check-yaml`, throws an error when reading `third_party/spdlog/.travis.yml`, complaining about duplicate `addons` keys.

Are you running pre-commit on commits?

To run pre-commit outside of a normal commit, use `pre-commit run -a`

**Comment by bsergean** [comment]
If you want to kill that yaml checker please go ahead.

I think I uninstalled the pre-commit hook for the repo. I run clang-format manually by typing `make format`

I use pre-commit with other python repos and really likes it.

**Comment by pocc** [comment]
Already submitted PR. Let me know if you run into any issues.
