### ISSUE TITLE
Add clang-tidy to pre-commit

### ISSUE THREAD

**Issue by pocc** [machinezone/IXWebSocket#181]
It's possible to run clang-tidy, which is a static-code analyzer, over this code. There are a bunch of errors about missing header files, but I don't know how relevant they are because the code compiles.

There are also many more warnings, which may be helpful. I've gone ahead and run this over the project (`for i in $(find test ixwebsocket ws -type file | grep -E '\.cp?p?$|\.h$'); do echo $i; clang-tidy -p compile_commands.json -checks=* "$i" 2>/dev/null >> clang-tidy.info; done`). Partial results for just the test folder are at this paste https://pastebin.com/32T5pRNM so you can see an example of it and whether it's worth it to add.

**Comment by bsergean** [comment]
<img width="824" alt="Screen Shot 2020-04-22 at 1 47 53 PM" src="https://user-images.githubusercontent.com/11857745/80032356-e8493600-849f-11ea-8992-433ed245f2d7.png">

**Comment by bsergean** [comment]
Very cool, I'd love to make the code better, and it's likely I can specify an exception list if I don't want to bother about some warnings, right ?

My problem right now is that the steps to install clang-tidy on macOS aren't super clear, can't find it on homebrew, or MacPort. macOS is my primary dev environment.

**Comment by bsergean** [comment]
Actually I had installed iwyu (include what you use) through homebrew, which installed llvm, which installed clang-tidy.

```
 $(brew --prefix llvm)/bin/clang-tidy
```

**Comment by bsergean** [comment]
Tried your command but got:

```
$ for i in $(find test ixwebsocket ws -type file | grep -E '\.cp?p?$|\.h$'); do echo $i; clang-tidy -p compile_commands.json -checks=* "$i" 2>/dev/null >> clang-tidy.info; done
test/IXCobraToSentryBotTest.cpp
zsh: no matches found: -checks=*
test/test_runner.cpp
zsh: no matches found: -checks=*
test/IXDNSLookupTest.cpp
zsh: no matches found: -checks=*
test/IXWebSocketTestConnectionDisconnection.cpp
zsh: no matches found: -checks=*
test/IXGetFreePort.cpp
zsh: no matches found: -checks=*
```

**Comment by pocc** [comment]
1. I have verified that the link works on multiple browsers. You may want to try a different browser/machine.
2. Warnings don't normally error and the clang-tidy pre-commit-hook will obey this behavior. You can change this with `-warnings-as-errors=*`, or specify warnings that you care about instead of `*`. You can also choose to only check for specific errors by specifying those errors in `-checks=`.
3.  Yeah - clang-format and clang-tidy and other utils come installed with `llvm` when you install that package on brew or chocolatey. 
4. zsh is expanding `*` in unexpected ways? `-checks=*` is a clang-tidy argument, so maybe call bash in a subshell?

**Comment by bsergean** [comment]
I got it to run when building with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

**Comment by pocc** [comment]
Yeah you need to add a compilation database. You can create one with `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .` The `-p compile_commands.json` in the command above specifies this file.

**Comment by bsergean** [comment]
I checked this and I was lost in too many warnings ... are there some that you find super important which I could just enable for now.

I saw some 'performance' ones. If there are easy things like missing headers, or something to make compilation faster that would be great too.

**Comment by pocc** [comment]
Why not take a look at the classes of errors/warnings that are available? https://clang.llvm.org/extra/clang-tidy/
