### ISSUE TITLE
HelloWorld example program

### ISSUE THREAD

**Issue by belarusrulez** [machinezone/IXWebSocket#183]
Hello, Hope you are doing good :) I am very new in C++. 
Actually Day 1 is today so plz forgive me stupid questions.

![image](https://user-images.githubusercontent.com/1071191/80164150-10629300-858d-11ea-8169-0ca439e8d711.png)

Trying to replicate hello world project. 
installed using:
I tried to install it using CMake ui for windows and vcpkg install ixwebsocket 
This namespace doesn't have this object.

![image](https://user-images.githubusercontent.com/1071191/80164336-8961ea80-858d-11ea-8ddb-336929b1e8ce.png)

Thanks for responds 👍

**Comment by bsergean** [comment]
I'm happy that you're spending your first day coding C++ using my project ... but I'm not sure I'll have the time to help you learn C++, maybe you can find a C++ learning forum ?

This looks like a basic CMake error. Maybe you can check on the vcpkg page ? Did you tell cmake about vcpkg location.

-DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake

#     - run: |
#         vcpkg install zlib:x64-windows
#         vcpkg install openssl:x64-windows
#     - run: |
#         mkdir build
#         cd build
#         cmake -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=cl.exe -DUSE_OPEN_SSL=1 -DUSE_TLS=1 -DUSE_WS=1 -DUSE_TEST=1 ..
#     - run: cmake --build build

This is what the unittest does.

**Comment by bsergean** [comment]
Did you figure it out @belarusrulez ?

**Comment by belarusrulez** [comment]
Thank you for quick respond.
I was able to install IXWebSocket using
`vcpkg install ixwebsocket`
I am trying to replicate hello world example that you have and facing ssl issue.
![image](https://user-images.githubusercontent.com/1071191/80264337-b45d4480-8648-11ea-9f78-0aaddef8b2b5.png)
I uninstalled ixwebsocket and installed 
`vcpkg install ixwebsocket[mbedtls]`
Could you please give me an advice what I am doing worng? Thank you.

**Comment by bsergean** [comment]
This is documented, you need to specify a cacert file.

https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration <https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration>

You can download such a file from 
https://curl.haxx.se/docs/caextract.html

**Comment by bsergean** [comment]
@belarusrulez the next version which will be available on vcpkg will have this cacert problem fixed.

cc https://github.com/microsoft/vcpkg/pull/11030
