### ISSUE TITLE
Https request returns `cancellation requested` on macOS

### ISSUE THREAD

**Issue by liz3** [machinezone/IXWebSocket#185]
Note that im by no means experienced with C++ OR the library.
here the implementation(mostly taken from the Http Client example of the docs):
```cpp
static discord_simple_response discord_get_gateway_endpoint(std::string& token) {
  discord_simple_response return_target;
  HttpClient httpClient;
  HttpRequestArgsPtr args = httpClient.createRequest();
  HttpResponsePtr out;
  std::string url = "https://www.google.com";
  out = httpClient.get(url, args);
  auto errorCode = out->errorCode;
  if(errorCode != HttpErrorCode::Ok) {
    return_target.success = false;
    return_target.value = std::string(out->errorMsg);
    return return_target;
  }
  auto payload = out->payload;

  return_target.success = true;
  return_target.value = std::string(payload);

  return return_target;
}
```
`out->errorCode` is set to the value 
`Cannot connect to url: https://www.google.com / error : cancellation requested`

os: MacOS 10.15.4
kernel: `Darwin Kernel Version 19.4.0`
Build flags: `-DUSE_TLS=1`
version(latest commit at tim of reporting): `20294841b333638b05d44312ed1be767332be3ee`

Kind regards,
Liz3

**Comment by liz3** [comment]
The solution is: 
Okay figured it out, the defaults need to set for `connectTimeout` and `transferTimeout`.

Feel free to close this though i would like to suggest it might maybe a possibility to give these params default value if not overridden by the the caller

**Comment by bsergean** [comment]
Thanks for reporting the bug, can you give the latest version a try to make sure that the new default values I have set work for you ?

(9.5.1 ?) = latest commit on master

**Comment by liz3** [comment]
@bsergean Yes. works as expected. thanks a lot for the fast reaction!
