### ISSUE TITLE
vcpkg package isn't given a configuration file.

### ISSUE THREAD

**Issue by SeanOMik** [machinezone/IXWebSocket#186]
I installed IXWebSocket how you would with any other vcpkg package `vcpkg install ixwebsocket:x64-windows` and after trying to add it to my cmake like this: 
```cmake
find_package(ixwebsocket EQUIRED)

#...

target_link_libraries(discpp PUBLIC ixwebsocket)
```
I get an error: 
```
  By not providing "Findixwebsocket.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ixwebsocket", but CMake did not find one.

  Could not find a package configuration file provided by "ixwebsocket" with
  any of the following names:

    ixwebsocketConfig.cmake
    ixwebsocket-config.cmake

  Add the installation prefix of "ixwebsocket" to CMAKE_PREFIX_PATH or set
  "ixwebsocket_DIR" to a directory containing one of the above files.  If
  "ixwebsocket" provides a separate development package or SDK, be sure it
  has been installed.
```
I checked in `vcpkg\installed\x64-windows\share\ixwebsocket` and saw its empty besides a `copyright` and `vcpkg_abi_info.txt` file. Am I not adding IXWebsocket correctly or is there something wrong with vcpkg?

**Comment by bsergean** [comment]
1. I am not an expert with vcpkg. You can probably ask a question on their page as well
2. When you generate your project by running cmake, you need to specify where to find things
3. If you need to write your own ‘FindPackage for ixwebsocket, you can look in the CMake folder there are examples.

**Comment by SeanOMik** [comment]
Yeah, I think I'm gonna have to make a find package. Thanks

**Comment by bsergean** [comment]
ps: I'm sure it's a typo but your example says:

```
find_package(ixwebsocket EQUIRED)
```

Should be REQUIRED.

**Comment by bsergean** [comment]
`cmake -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake`

Also to get cmake to find 'things' you should do something like that. It's in the vcpkg doc somewhere.

**Comment by SeanOMik** [comment]
Yeah I did have the cmake toolchain thing. I was able to get ixwebsocket added by using a submodule. However I'm getting a different error: `TLS support is not enabled on this platform.` I'll create another issue for it though.
