### ISSUE TITLE
Issue with message data compression from web socket message event.

### ISSUE THREAD

**Issue by liz3** [machinezone/IXWebSocket#187]
This isnt as easy to explain because it might also be a issue with my implementation but it might also be within the message handling of IXWebSocket.

Starting note:
I am implementing the [Discord Gateway Protocol](https://discordapp.com/developers/docs/topics/gateway#encoding-and-compression).
The Discord gateway websocket supports both non compressed and compressed(zlib-stream) transmission.
The non compressed transmission seams to work as expected with IXWebSocket.
During the compressed transmission, the discord gateway actual messages might be send using **more** then one websocket message.

The Problem:
Messages from the discord gateway websocket which are the end of a actual message are terminated with the zlib-suffix `0x00, 0x00, 0xff, 0xff`.

Now while IXWebsocket does pass `binary = true`.
The suffix is not present, in non of the messages.
Ive tried with `this->webSocket.disablePerMessageDeflate()` and `this->webSocket.enablePerMessageDeflate()`.
So might the library do something else before passing the message to the handler?
The checking happens in a pretty trivial way, taken from [here, (aegis by zeroxs)](https://github.com/zeroxs/aegis.cpp/blob/master/include/aegis/shards/impl/shard_mgr.cpp#L141):
```cpp
if(std::strcmp((msg->str.data() + msg->str.size() - 4), "\x00\x00\xff\xff"))
    return;
```
As mentioned this condition is always false.
Does IXWebsocket do internal decompression by default which i have to explicitly disable.
Or is IXWebSocket not doing anything internal, which means theres a flaw in my implementation.

Thanks for reading, helping and this library!
Regards,
Liz3

**Comment by liz3** [comment]
Sorry. it was my bad. issue in my implementation. Closing this since not related to the repo.
I was not passing the query parameters to the discord gateway websocket url.

**Comment by bsergean** [comment]
Well I'm glad you figured it out.

There is a compliance test for websocket called autobahn, and IXWebSocket is compliant in client mode, but I never tested it fully in server mode.

But there's always room for improvement. Are you using the lib as a client library ?

**Comment by liz3** [comment]
@bsergean yes. im writing a client side only project communicating with the discord services:
https://gitlab.com/HCInk/dis-light

**Comment by bsergean** [comment]
Cool. Do you mind if I add a reference to your project in the IXWebSocket readme page ?

**Comment by liz3** [comment]
@bsergean no sure i would be happy
