### ISSUE TITLE
Error trying to connect to a gateway `TLS support is not enabled on this platform.`

### ISSUE THREAD

**Issue by SeanOMik** [machinezone/IXWebSocket#188]
I was trying to connect to a websocket but after connecting I get this error: `TLS support is not enabled on this platform.` This is my code: 
```cpp
#ifdef _WIN32
if (!reconnecting) {
    ix::initNetSystem();
}
#endif

websocket.setUrl(gateway_endpoint);
websocket.disableAutomaticReconnection();

websocket.setOnMessageCallback([this](const ix::WebSocketMessagePtr& msg) {
    OnWebSocketListen(msg);
});

websocket.start();
```
And the `ix::initNetSystem()` is running, I checked with breakpoints. I am also running on Windows. If it matters I'm connecting to a secure websocket (WSS). If you have any questions you can of course ask.

**Comment by bsergean** [comment]
See this section in the doc -> https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration <https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration>

You will have to manually specify a cacert pem file to configure TLS. This will be done automatically for you once the latest version of ixwebsocket is available on vcpkg -> https://github.com/microsoft/vcpkg/pull/11030

https://curl.haxx.se/docs/caextract.html <https://curl.haxx.se/docs/caextract.html>

**Comment by SeanOMik** [comment]
Awesome, I'll try this out tomorrow for now I'm off to bed. Thanks for answering!

**Comment by SeanOMik** [comment]
Okay, got it working, thanks for your help!
