### ISSUE TITLE
ix::HttpClient cannot be shutdown while active requests are pending response

### ISSUE THREAD

**Issue by morty346** [machinezone/IXWebSocket#189]
Calling 
bool performRequest(HttpRequestArgsPtr request,
                            const OnResponseCallback& onResponseCallback);

the destructor appears to block and never return

will lock up the application if the user tries to close the application before onResponseCallback has been called

**Comment by bsergean** [comment]
Can you provide a standalone repro file ?
Are you using the async mode ?
What are you doing in the callback ?

**Comment by morty346** [comment]
I can try and build a standalone

async = true

```
            hc->performRequest(GenerateRequest(hc, headers, body, url, RequestType),
                std::bind(MsgHandler, std::placeholders::_1, im));

```
 ```
void MsgHandler (const HttpResponsePtr& response, std::shared_ptr<InterpreterMessage> im)
    {
        auto statusCode = response->statusCode;

        if (statusCode != 200)
        {
            printf("%s %s - %i %i\n", response->payload.c_str(), response->errorMsg.c_str(), statusCode, response->errorCode);
            std::vector<std::string> items = { __FILE__, __func__ ,
                LINE_STRING,  "SEND FAILURE", std::to_string(statusCode),
                response->payload.c_str() ,response->errorMsg.c_str(),std::to_string((int)response->errorCode) };
            CErrorLogger::instance().log(items, CErrorLogger::kLogLevelError);

            if (im->_httpClientMsgCallback != NULL)
            {
                im->str = "";
                im->_httpClientMsgCallback(*im);
            }
        }
        else
        {
            if(im->_httpClientMsgCallback != NULL)
            {
				im->str = response->payload;
				im->_httpClientMsgCallback(*im);
            }
        }
    }
```

**Comment by bsergean** [comment]
Can you try this ?


$ git diff ixwebsocket/IXHttpClient.cpp 
diff --git a/ixwebsocket/IXHttpClient.cpp b/ixwebsocket/IXHttpClient.cpp
index b04c69d..1a2666b 100644
--- a/ixwebsocket/IXHttpClient.cpp
+++ b/ixwebsocket/IXHttpClient.cpp
@@ -220,11 +220,10 @@ namespace ix
 
         std::string req(ss.str());
         std::string errMsg;
-        std::atomic<bool> requestInitCancellation(false);
 
         // Make a cancellation object dealing with connection timeout
         auto isCancellationRequested =
-            makeCancellationRequestWithTimeout(args->connectTimeout, requestInitCancellation);
+            makeCancellationRequestWithTimeout(args->connectTimeout, _stop);
 
         bool success = _socket->connect(host, port, errMsg, isCancellationRequested);
         if (!success)
@@ -243,7 +242,7 @@ namespace ix
 
         // Make a new cancellation object dealing with transfer timeout
         isCancellationRequested =
-            makeCancellationRequestWithTimeout(args->transferTimeout, requestInitCancellation);
+            makeCancellationRequestWithTimeout(args->transferTimeout, _stop);
 
         if (args->verbose)
         {

**Comment by bsergean** [comment]
@morty346 I believe this is fixed so I'm going to close this. Please reopen if I'm lying :)
