### ISSUE TITLE
CMake export regression

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#191]
cf #190

@ebenali do you know what we can do about this windows error ?

https://pipelines.actions.githubusercontent.com/SYUiO8aHxb4LIyZgymGkvgwhJRrl1FTnKw8Q829qRwtlbSK3Tg/_apis/pipelines/1/runs/273/signedlogcontent/12?urlExpires=2020-05-03T03%3A59%3A43.8936693Z&urlSigningMethod=HMACV1&urlSignature=FPNAHaDaUlpuVdo6oibovpRGGUVFcg7ElapeXiT5rEM%3D

**Comment by ebenali** [comment]
pull-req #192 should fix this issue.

**Comment by bsergean** [comment]
I think it did. Thanks @ebenali !
