### ISSUE TITLE
Access to connectionState for all clients

### ISSUE THREAD

**Issue by flagarde** [machinezone/IXWebSocket#196]
Hello,
First at all, thank you for your great library.
I'm wondering if there is an easy way to access the connectionState for a given client in the websocketserver class ?

For my project i need to give a name to each client and forbid connection an clients with the same name.
I planned to implement my own ConnectionState using the ConnectionStateFactory but then it seems it's not possible to access to the ConnectionState of the clients (a bit like getClients())

**Comment by bsergean** [comment]
Thanks for the good words.

If I understand correctly, you don't want to have 2 connections on the server with the same id/name ? From the same client host ? Or for the same authenticated user, on 2 different machines ?

You could have a set of all the connection ids, where you add entries (id/names) when a connection state object is created, and remove entry when the connection state is deleted.

Is the name going to be client generated or server generated ?

**Comment by flagarde** [comment]
Hi,
I would like to have one and only one client with particular id.
What I did is the create a map with the id as key containing the ptr of the socket. But I wondered if there was a better alternative.
Thx

**Comment by flagarde** [comment]
For example there is a way to access a client by its Id using your library?
