### ISSUE TITLE
Add project as a `user` in readme

### ISSUE THREAD

**Issue by SeanOMik** [machinezone/IXWebSocket#198]
I've been working on a simple but feature rich Discord API wrapper for a while now and think it would be a good idea to start showing it off. Here's the GitHub: https://github.com/DisCPP/DisCPP. Maybe you could add it to the [readme's user section](https://github.com/machinezone/IXWebSocket#users). Thanks! Its actual name is DisC++ but the pluses aren't allowed in repos so I had to use `pp` instead. 

Currently the development branch is using ixwebsocket since we recently switched to it and still want to do some testing to make sure we didn't break anything in the process.

**Comment by bsergean** [comment]
Cool, just referenced your project in the README.

There is an HTTP class as part of IXWebsocket, if you'd like to give it a try.

**Comment by SeanOMik** [comment]
Awesome! I did take a look at that and its cool, but I couldn't find multipart stuff to send files and also the patch HTTP method.

**Comment by bsergean** [comment]
The PATCH verb is now supported in master.

For multi-part I do something similar for uploading things to sentry.

See this example block:
If you have multiple files you can add several entries for them like I do for upload_file_minidump.

If you can give that a try that would be appreciated.

```
        std::string multipartBoundary = _httpClient->generateMultipartBoundary();

        auto args = _httpClient->createRequest();
        args->verb = HttpClient::kPost;
        args->connectTimeout = 60;
        args->transferTimeout = 5 * 60;
        args->followRedirects = true;
        args->verbose = verbose;
        args->multipartBoundary = multipartBoundary;
        args->logger = [](const std::string& msg) { CoreLogger::log(msg.c_str()); };

        HttpFormDataParameters httpFormDataParameters;
        httpFormDataParameters["upload_file_minidump"] = minidumpBytes;

        HttpParameters httpParameters;
        httpParameters["sentry"] = sentryMetadata;

        args->url = computeUrl(project, key);
        args->body = _httpClient->serializeHttpFormDataParameters(
            multipartBoundary, httpFormDataParameters, httpParameters);

        _httpClient->performRequest(args, onResponseCallback);

```

**Comment by SeanOMik** [comment]
Okay I'll try that when I can, it may be a while though since we're converting to rapidjson from nlohmann because its faster. I'll try that as soon as I can though, thanks!
