### ISSUE TITLE
Unable to install on Alpine docker

### ISSUE THREAD

**Issue by ArielFrischer** [machinezone/IXWebSocket#199]
I'm using image: `FROM mhart/alpine-node:12.16.3`
I need ws because our puppeteer package has ws as a dependency. The puppeteer installation using yarn seems to install without any errors, but during runtime I get `ws TCP.onReadStream error` which crashes my server and is difficult to catch(). 
 ```
Step 13/21 : RUN time apk add --no-cache jsoncpp libcrypto1.1 libgcc libssl1.1 libstdc++ musl zlib ws
  ---> Running in 00480d78aa62
 fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
 fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
 ERROR: unsatisfiable constraints:
   ws (missing):
     required by: world[ws]
```

My yarn.lock 
```
ws@^3.0.0:
  version "3.3.3"
  resolved "https://registry.yarnpkg.com/ws/-/ws-3.3.3.tgz#f1cf84fe2d5e901ebce94efaece785f187a228f2"
  integrity sha512-nnWLa/NwZSt4KQJu51MYlCcSQ5g7INpOrOMt4XV8j4dqTXdmlUmSHQ8/oLC069ckre0fRsgfvsKwbTdtKLCDkA==
  dependencies:
    async-limiter "~1.0.0"
    safe-buffer "~5.1.0"
    ultron "~1.1.0"

ws@^5.2.0:
  version "5.2.2"
  resolved "https://registry.yarnpkg.com/ws/-/ws-5.2.2.tgz#dffef14866b8e8dc9133582514d1befaf96e980f"
  integrity sha512-jaHFD6PFv6UgoIVda6qZllptQsMlDEJkTQcybzzXDYM1XO9Y8em691FGMPmM46WGyLU4z9KMgQN+qrux/nhlHA==
  dependencies:
    async-limiter "~1.0.0"

ws@^7.0.0, ws@^7.2.5:
  version "7.2.5"
  resolved "https://registry.yarnpkg.com/ws/-/ws-7.2.5.tgz#abb1370d4626a5a9cd79d8de404aa18b3465d10d"
  integrity sha512-C34cIU4+DB2vMyAbmEKossWq2ZQDr6QEyuuCzWrM9zfw1sGc0mYiJ0UnG9zzNykt49C2Fi34hvr2vssFQRS6EA==
```

I've checked out: https://pkgs.alpinelinux.org/package/v3.11/community/x86_64/ws and tried to install all dependencies, that didn't seem to work.

**Comment by bsergean** [comment]
Hey Ariel, is this the node.js ws command line tool ?

ws is a C++ command line tool, only available in alpine 3.11.

**Comment by ArielFrischer** [comment]
@bsergean the puppeteer package installs: https://yarnpkg.com/package/ws which doesn't look like a command line tool. But the apk add ws might be.

**Comment by ArielFrischer** [comment]
Here is more info on the ws error:
`events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on WebSocket instance at:
    at WebSocket.finalize (/backend/node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:182:41)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
error Command failed with exit code 1.`

**Comment by ArielFrischer** [comment]
Just realized I'm on the incorrect github page 🥇 it should be https://github.com/websockets/ws. I'll post there.
