### ISSUE TITLE
How do you use the HTTPClient to download files?

### ISSUE THREAD

**Issue by SeanOMik** [machinezone/IXWebSocket#200]
I tried this:
```cpp
ix::HttpClient client;
ix::HttpRequestArgsPtr args = client.createRequest(url);
args->verbose = true;
args->compress = false;
args->logger = [](const std::string& msg) { discpp::globals::client_instance->logger->Debug(msg); };
args->onProgressCallback = [&](int current, int total) -> bool {
    discpp::globals::client_instance->logger->Debug("Downloaded " + std::to_string(current) + " bytes out of " + std::to_string(total));

    return true;
};

ix::HttpResponsePtr response = client.get(url, args);
```
And it seems like it downloads the file but where does it download the files? I thought it may be in the same folder as the executable but I don't see it. Its supposed to be a png.

**Comment by bsergean** [comment]
The bytes are available in the **payload** field of the **response** (or the png itself).

Here's an example on how to save that disk with C++ like fstream code.
https://github.com/machinezone/IXWebSocket/blob/master/ws/ws_http_client.cpp#L160

**Comment by SeanOMik** [comment]
That worked, thanks!
