### ISSUE TITLE
Uploading files through multipart.

### ISSUE THREAD

**Issue by SeanOMik** [machinezone/IXWebSocket#209]
I'm working on my DisC++ lib and I think I got all the basic http methods done. I just need to work on uploading files. Discord does this via a multipart form. 

You did give me an example in an earlier issue, which I was able to [track down](https://github.com/machinezone/IXWebSocket/blob/4f17cd5e7498bdca4cf1089eb1d33765981bf913/ixsentry/ixsentry/IXSentryClient.cpp#L261). But it doesn't really help me much. 

In that method you use `miniDumpBytes` which is a string, how would I get the minidump bytes for the files from an ifstream? And what about sending multiple files in one request? If you want to look at the documentation on sending files, its [here](https://discord.com/developers/docs/resources/channel#create-message).

Thanks for reading!

**Comment by bsergean** [comment]
```
        HttpFormDataParameters httpFormDataParameters;
        httpFormDataParameters["file_1"] = bytesA;
        httpFormDataParameters["file_2"] = bytesB;
```

For the other question you can look at this link
https://stackoverflow.com/questions/2602013/read-whole-ascii-file-into-c-stdstring

**Comment by SeanOMik** [comment]
That makes so much more sense, I'll try it later today, thanks.

**Comment by bsergean** [comment]
For what it's worth, I have this in one my files, which should work if your file contains NULL bytes.

```
    // Assume the file exists
    std::string readBytes(const std::string& path)
    {
        std::vector<uint8_t> memblock;
        std::ifstream file(path);

        file.seekg(0, file.end);
        std::streamoff size = file.tellg();
        file.seekg(0, file.beg);

        memblock.resize(size);

        file.read((char*) &memblock.front(), static_cast<std::streamsize>(size));

        std::string bytes(memblock.begin(), memblock.end());
        return bytes;
    }
```

**Comment by SeanOMik** [comment]
I tried this: 
```cpp
ix::HttpClient* client = new ix::HttpClient(true);


ix::HttpRequestArgsPtr args = client->createRequest();
args->logger = [](const std::string& msg) { globals::client_instance->logger->Debug(msg); };
args->extraHeaders = DefaultHeaders({ {"Content-Type", "multipart/form-data"} });

ix::HttpFormDataParameters data_parameters;
for (int i = 0; i < files.size(); i++) {
    std::vector<uint8_t> memblock;
    std::ifstream file(files[i].file_path);

    file.seekg(0, file.end);
    std::streamoff size = file.tellg();
    file.seekg(0, file.beg);

    memblock.resize(size);

    file.read((char*) &memblock.front(), static_cast<std::streamsize>(size));

    std::string file_bytes(memblock.begin(), memblock.end());

    data_parameters["file" + std::to_string(i)] = file_bytes;
}
data_parameters["payload_json"] = "{\"content\": \"" + escaped_text + (tts ? "\",\"tts\":\"true\"" : "\"") + "\"}";

std::string multipart_bound = client->generateMultipartBoundary();
args->multipartBoundary = multipart_bound;
args->body = client->serializeHttpFormDataParameters(multipart_bound, data_parameters);

WaitForRateLimits(id, RateLimitBucketType::CHANNEL);
globals::client_instance->logger->Debug("Sending patch request, URL: " + Endpoint("/channels/" + std::to_string(id) + "/messages") + ", body: " + args->body);

ix::HttpResponsePtr result = client->post(Endpoint("/channels/" + std::to_string(id) + "/messages"), data_parameters, args);
```
But discord thinks the message is empty for some reason. I am printing out the body contents:
```
--dwob2ateVD9yk6ENcUzqs83C5JI1WPmKZfLvGHBO04SiuTRhxYrQFXngMljpA7

Content-Disposition: form-data; name="file0"; filename="file0"

Content-Type: application/octet-stream



# DexunBot
A Complex Discord bot written in C++ using my DiscordPP api wrapper.

All rights reserved
    

--dwob2ateVD9yk6ENcUzqs83C5JI1WPmKZfLvGHBO04SiuTRhxYrQFXngMljpA7--```
I also did try to set the name to `file_0` instead of `file0` and that doesn't change anything.

**Comment by bsergean** [comment]
Can you try to test with a different http server / I would make a standalone program to test (nginx, apache, python etc..)

What is the exact error message.

Can you try to just send 'one' file ?

**Comment by SeanOMik** [comment]
I used droopy (python) to see the request and this is the error I got in droopy: 
```
127.0.0.1 - - [27/May/2020 15:41:49] Started file transfer
127.0.0.1 - - [27/May/2020 15:41:49] ValueError("Invalid boundary in multipart form: b''")
127.0.0.1 - - [27/May/2020 15:41:49] "POST / HTTP/1.1" 200 -```
The exact error from Discord: `{"message": "Cannot send an empty message", "code": 50006}`

**Comment by bsergean** [comment]
looks like the 'boundary' is messed up for some reason.

1. have you tried sending just one file ?

**Comment by SeanOMik** [comment]
I am sending just one file.

**Comment by bsergean** [comment]
can you do args->verbose = true ?
that will display the request payload if you have setup a logging callback, which you did apparently

**Comment by SeanOMik** [comment]
This is the request payload when trying to send to droopy: ```
[15:52:59] [DEBUG] Sending POST request to localhost:8000
request size: 566 bytes
=============
POST / HTTP/1.1

Host: localhost

Accept-Encoding: gzip

Authorization: Bot CORRECT DISCORD TOKEN BUT CENSORED

Content-Type: multipart/form-data

User-Agent: DiscordBot (https://github.com/seanomik/DisCPP, v0.0.0)

X-RateLimit-Precision: millisecond

Accept: */*

User-Agent: ixwebsocket/9.6.4 windows ssl/OpenSSL OpenSSL 1.1.1d  10 Sep 2019 zlib 1.2.11

Content-Length: 162



file_0=%23%20DexunBot%0AA%20Complex%20Discord%20bot%20written%20in%20C%2B%2B%20using%20my%20DiscordPP%20api%20wrapper.%0A%0AAll%20rights%20reserved%0A%00%00%00%00=============


[15:52:59] [DEBUG] Status line HTTP/1.0 200 OK


[15:52:59] [DEBUG] Received requested payload: 
Assertion failed: false, file D:\vcpkg\installed\x64-windows\include\rapidjson/document.h, line 1137

Process finished with exit code 3

```

**Comment by bsergean** [comment]
I don't know what's happening, maybe you should trace it and run it through a debugger.

I know it works well for us in production code on iOS + Android, so this could be a windows bug maybe ?

I'm gonna add a C++ unittest to try to exercise this code in automation.

**Comment by SeanOMik** [comment]
Its running in CLion but I'm not sure what I should be looking for when I trace the request. It may be better if I leave this part to you tbh.

**Comment by bsergean** [comment]
It's open-source code so I can't make any guarantee on when I'll have time to investigate this.

**Comment by SeanOMik** [comment]
Okay, that's fine.

**Comment by bsergean** [comment]
If you want to make progress on your own, you can try to run your code on Linux in docker, or put breakpoints in IXHttpClient.cpp and trace through the program to see why the message boundary thing is empty.

See code below. I think that the problem might be that you are overriding the Content-Type. Try to not do that.


        if (verb == kPost || verb == kPut || verb == kPatch || _forceBody)
        {
            ss << "Content-Length: " << body.size() << "\r\n";

            // Set default Content-Type if unspecified
            if (args->extraHeaders.find("Content-Type") == args->extraHeaders.end())
            {
                if (args->multipartBoundary.empty())
                {
                    ss << "Content-Type: application/x-www-form-urlencoded"
                       << "\r\n";
                }
                else
                {
                    ss << "Content-Type: multipart/form-data; boundary=" << args->multipartBoundary
                       << "\r\n";
                }
            }
            ss << "\r\n";
            ss << body;
        }

**Comment by bsergean** [comment]
```
args->extraHeaders = DefaultHeaders({ {"Content-Type", "multipart/form-data"} });
```

I think it will work if you remove that line.

**Comment by SeanOMik** [comment]
Okay so I removed that line and I'm no longer getting that error when I try to upload to Droopy it just sits on: `127.0.0.1 - - [27/May/2020 18:19:44] Started file transfer`. I am still getting the same error from Discord though.

**Comment by bsergean** [comment]
You probably gave up on this, but if you can attach/display your 'droopy' python server example program that would help / and also a standalone C++ file that try to upload multiple files.

**Comment by SeanOMik** [comment]
I'll try it again when I have time.
