### ISSUE TITLE
Sending binary data

### ISSUE THREAD

**Issue by aosterthun** [machinezone/IXWebSocket#212]
Hi,

I would like to send binary data with your websocket library. I've seen that there is a binary flag in the send method as well as a sendBinary method, but both seem to only accept std::strings as data. I would like to send std::vectors. is that possible with your library ? I don't want to parse the vector to a json array or something, I want to send the raw array data of the vector so I don't have to parse the data on the other side.

**Comment by bsergean** [comment]
You can definitely send through the websocket in Binary mode, but there is no std::vector interface, so you'll have to find a way to cast your std::vector content to an std::string, or make a temp std::string at this point.

**Comment by aosterthun** [comment]
I haven’t look at the backend code for send binary, but it should be possible to support std::vector. How would you estimate the effort of implementing it ? I would be up to contribute if it’s relatively straightforward.

**Comment by bsergean** [comment]
There is ton of internal code which would have to change (for zlib extension handling), and the api would stop being symetrical between send and receive, which I don't like, so it wouldn't be easy.

We 'could' have a new method that accept a std::vector<uint8_t>. An std::string can represent a binary buffer (search for the msgpack used code in the ws folder, for ws transfer / send receive).

The whole api could change to use std::vector, and we would just keep a send string for convenience, but I would break a ton of existing code with that change.

However this is open-source, so if you want you can fork the code and play with this idea. If the changes are too extensive it's unlikely I will merge it.

**Comment by bsergean** [comment]
This is an example of using sendBinary.  -> https://github.com/machinezone/IXWebSocket/blob/master/ws/ws_send.cpp

This is where a lot of low level code happens -> 
https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXWebSocketTransport.cpp

**Comment by bsergean** [comment]
```
vector<uint8_t> vec;
std::string str(vec.begin(), vec.end());
webSocket.sendBinary(str);
```

This should work. We could have a helper method in websocket class.
