### ISSUE TITLE
IXSocketServer is declared as final 

### ISSUE THREAD

**Issue by flagarde** [machinezone/IXWebSocket#215]
IXSocketServer is declared as final forbidding to use it as mother class. Does it's make on purpose ?

**Comment by bsergean** [comment]
I'm using it as a derived class for http server, websocket server, and redis server. Do you want to write your own server too ? Can you see on those other classes work ?

**Comment by bsergean** [comment]
SocketServer is not declared as final. However HttpServer is declared that way.

    class HttpServer final : public SocketServer

**Comment by flagarde** [comment]
Hello, sorry it's WebSocketServer which is declared final. Do you want to force the us of WebSocketServer only as member of a class forbidding it's use as mother class. I would like to use this class as a Base one and add other member function. Maybe you have very good reasons to make it private :) If so it would be great if you had time to explain this design choice.

**Comment by bsergean** [comment]
Hey @flagarde did this work for you ?
