### ISSUE TITLE
mbedTLS keyfile empty password

### ISSUE THREAD

**Issue by tostc** [machinezone/IXWebSocket#216]
I working currently with the IXHttpServer and mbedTLS to encrypt the connection. Now I have generated a self-signed certificate with password and I get following error

```
SocketServer::run() tls accept failed: Cannot parse key file 'key.pem'
```

I've inspect the code and found that [here](https://github.com/machinezone/IXWebSocket/blob/c9854be1c43f6824c8c2c01ff4bdb21203063c46/ixwebsocket/IXSocketMbedTLS.cpp#L130) following error occurred: [MBEDTLS_ERR_PK_PASSWORD_REQUIRED](https://tls.mbed.org/api/pk_8h.html#a9c1de7ccb4e18a3ea74b35c4e2cb7527). This error occur if the password is empty. And the password seems empty because an empty string is passed to the [password parameter](https://tls.mbed.org/api/pk_8h.html#a935d710e542409462d0209f2381da83e).

**Comment by bsergean** [comment]
Thanks for the bug report. There is no support as of now for adding passwords to custom certificates.

To improve here we would need to add a new field to the socket tls option to store that parameter, and handle it in OpenSSL + mbedtls code paths.

If you want to give it a try please do, I don't know when I'll have the time to do that. For now I suggest that you don't set a password ... but maybe it's not good for you.

**Comment by tostc** [comment]
Ok thanks for that information. I will remove the password. Thanks for your response :D
