### ISSUE TITLE
LINK2019 error

### ISSUE THREAD

**Issue by amishjain831** [machinezone/IXWebSocket#217]
I am using Visual Studio 2017, and used vcpkg to install the ixwebsocket library but I am getting the following errors while building the project.

Error	LNK2019	unresolved external symbol __imp__CertOpenStore@20 referenced in function "private: bool __thiscall ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AAE_NAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	testdemo	C:\Users\h403470\source\repos\testdemo\ixwebsocket.lib(IXSocketMbedTLS.cpp.obj)	1
	
Error	LNK2019	unresolved external symbol __imp__CertCloseStore@8 referenced in function "private: bool __thiscall ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AAE_NAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	testdemo	C:\Users\h403470\source\repos\testdemo\ixwebsocket.lib(IXSocketMbedTLS.cpp.obj)	1	

Error	LNK2019	unresolved external symbol __imp__CertEnumCertificatesInStore@8 referenced in function "private: bool __thiscall ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AAE_NAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	testdemo	C:\Users\h403470\source\repos\testdemo\ixwebsocket.lib(IXSocketMbedTLS.cpp.obj)	1	

Error	LNK2019	unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function "private: bool __thiscall ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AAE_NAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	testdemo	C:\Users\h403470\source\repos\testdemo\ixwebsocket.lib(IXSocketMbedTLS.cpp.obj)	1

**Comment by bsergean** [comment]
if (WIN32)
  target_link_libraries(ixwebsocket wsock32 ws2_32 shlwapi)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)

  if (USE_TLS)
    target_link_libraries(ixwebsocket Crypt32)
  endif()
endif()

You need to link with those libraries.

**Comment by amishjain831** [comment]
Thanks a lot, it worked :)
