### ISSUE TITLE
Heartbeart not sent in the configured interval (on Windows)

### ISSUE THREAD

**Issue by xhh** [machinezone/IXWebSocket#218]
With `webSocket.setPingInterval(45)`, heartbeart messages are sent to the server every 45 ~ 90 seconds, while expecting *exactly* 45 seconds.

FYI I'm running it on Windows 10.

**Comment by bsergean** [comment]
Hum that's quite strange, on Linux and macOS I have a heartbeat setup to send every 30s and it works quite well.

Can you try handle the Pong event, and printf its value on your client ? Something like that:

            else if (event->type == ix::CobraEventType::Pong)
            {
                CoreLogger::info("Received websocket pong: " + event->errMsg);

**Comment by xhh** [comment]
The following is the code and logging output with the ping interval set to 5:

```cpp
webSocket.setPingInterval(5);
webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg) {
    if (msg->type == ix::WebSocketMessageType::Pong) {
        logger->info("got pong. msg={}", msg->str);
    }
});

![ws](https://user-images.githubusercontent.com/159740/85098083-1ba00b00-b22c-11ea-9092-e5f261451a02.png)

Would it be related to the websocket server instead? I believe not, but I'll test against another server later.

**Comment by xhh** [comment]
Tried with a new websocker server written with the `ws` npm package, still got the same results (5~10s intervals).

**Comment by bsergean** [comment]
The unittest has some disabled ping/pong tests ... trying to re-enable them now.

**Comment by bsergean** [comment]
@xhh I just fixed a bug related to this (check the master branch), if you can test it that would be great.
