### ISSUE TITLE
Check if message is sent or not

### ISSUE THREAD

**Issue by amishjain831** [machinezone/IXWebSocket#219]
I am doing something like:
auto temp = webSocket.send("some message");
if(temp.success){
//do something
}
So if I run this, the if condition is not satisfied, I don't want to sleep explicitly for any duration, Is there any way in which I can get any notification that message was sent? The third argument(onProgressCallback), how do I use it?

**Comment by bsergean** [comment]
That function is synchronous, there is no callback. When the function is complete your buffer ("send message") is in the 'kernel' buffers, and ready to be sent through the network card. If the kernel buffers are full and tcp flow control has kicked in, the message will be kept around by the library, and delivered on ixwebsocket background thread the next time that thread wakes up.

I encourage you to run this code in a debugger to understand what's happening in your case. The code base is not that large it will be a good learning experience.
