### ISSUE TITLE
IXWebSocket sendBinary() function takes std::string as input?

### ISSUE THREAD

**Issue by rafalsk** [machinezone/IXWebSocket#220]
now that does not feel professional at all?

**Comment by bsergean** [comment]
What do you propose to make this better ? The internals use std::string heavily. 

Every users will have its own internal representation, so it will be hard to make something good for everyone.

**Comment by rafalsk** [comment]
it all depends on what we consider as a 'proper' way of doing things.
 
std::vector<uint8_t> is a natural first-choice for multi platform binary-data representation in C++;

std::string as the name suggests is catered for representation of string, human-readable literals.

Even though std:string as a container, wrapping sequenced elements whose size is equal 1-byte is perfectly valid for storing any binary information => external applications often might expect '\0' termination null-characters at the end when dealing with std::string.

Also, as library creators we might expect other software to use the 'proper' and not 'hacky' way of doing things. In The current situation we force 3rd party developers to wrap their 'proper' containers with std::string.

**Comment by bsergean** [comment]
Another thing. When you use 'hacky' or 'non professional' to refer to my code, I am really not inclined to respond to this issue even if you make a good point.

This library is used by a couple of company, so it is 'professional', and it is validating the full Autobahn test suite which is quite some work, so it is not a hack.

**Comment by bsergean** [comment]
With C++ template it might be possible to achieve what you want. I'm giving this a try.

**Comment by bsergean** [comment]
Playing with this in that branch feature/send_binary_vector

**Comment by rafalsk** [comment]
First of all, my intention was not to offend you but rather to provide a constructive rationalization. I hope you've found my point and rationalization sound.

Second, it's is really nice to see this library implemented, I would be more than happy to contribute. We're implementing a security/crypto project where things related to types/security are of an utmost priority (https://twitter.com/gridnetproject). We have chosen to try to integrate your library instead of websocketpp, as the latter's documentation is lacking to say the least (especially if one does not want to use ASIO and  the RAW 'transport' mechanism, which seems non-existent/non-documented).

Is there a way to get in IP address of an incoming connection, or to retrieve it from a WebSocket?

**Comment by bsergean** [comment]
hey @rafalsk did you get a chance to test the code change that makes the ip address available in the server callback ?

**Comment by rafalsk** [comment]
@bsergean  we've just integrate the functionality into our project;  it works;thank you; I am yet to test IPv6; IPv4 is fine; I may contribute in a few, a thing or two; such as an enum indicating the type of an internal address(IPv4/IPv6), represented internally as a string.

**Comment by bsergean** [comment]
Cool thanks for testing. I'm not sure that ipv6 will work, there are extra changes in SocketServer required (like using an ipv6 addr type in a few place. Do you need ipv6 support ?

**Comment by rafalsk** [comment]
Actually currently it's better for us not to allow for IPv6 so that we are able to thwart abuse (excessive connections from multiple addresses). We're investigating another case, in which connectToSocket()  throws at the line
`     _onMessageCallback(
            std::make_unique<WebSocketMessage>(WebSocketMessageType::Open,
                                               "",
                                               0,
                                               WebSocketErrorInfo(),
                                               WebSocketOpenInfo(status.uri, status.headers),
                                               WebSocketCloseInfo()));
`
socket is null. I'll get back with more information.
