### ISSUE TITLE
Default integration using VCPKG and unresolved-symbol errors  (crypt32.lib)

### ISSUE THREAD

**Issue by rafalsk** [machinezone/IXWebSocket#221]
`1>ixwebsocket.lib(IXSocketMbedTLS.cpp.obj) : error LNK2019: unresolved external symbol __imp_CertOpenStore referenced in function "private: bool __cdecl ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ixwebsocket.lib(IXSocketMbedTLS.cpp.obj) : error LNK2019: unresolved external symbol __imp_CertCloseStore referenced in function "private: bool __cdecl ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ixwebsocket.lib(IXSocketMbedTLS.cpp.obj) : error LNK2019: unresolved external symbol __imp_CertEnumCertificatesInStore referenced in function "private: bool __cdecl ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ixwebsocket.lib(IXSocketMbedTLS.cpp.obj) : error LNK2019: unresolved external symbol __imp_CertFreeCertificateContext referenced in function "private: bool __cdecl ix::SocketMbedTLS::loadSystemCertificates(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?loadSystemCertificates@SocketMbedTLS@ix@@AEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>C:\Users\rafal\Documents\Visual Studio 2017\GRIDNET\x64\Debug\GRIDNET Core.exe : fatal error LNK1120: 4 unresolved externals`

What's the proper way of coping with this when using VCPKG in case

- one does want TLS support

- one does not

I recall these are crypt32.lib dependencies (which I recall OpenSSL does require). So now, crypt32.dll/lib is available by default on Windows. What's the case on other operating systems? We might want to give a hint in docs of such a dependency, or give user an ability to disable the support of Certficates traversal etc, at all if he/she does not intend to be using TLS.

**Comment by bsergean** [comment]
if (WIN32)
  target_link_libraries(ixwebsocket wsock32 ws2_32 shlwapi)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)

  if (USE_TLS)
    target_link_libraries(ixwebsocket Crypt32)
  endif()
endif()

I think you're missing Cryp32 on your linker line.
