### ISSUE TITLE
IPv4/IPv6 address of an incoming connection

### ISSUE THREAD

**Issue by rafalsk** [machinezone/IXWebSocket#222]
Is there a way to get an IP address of an incoming connection, or to retrieve it from a WebSocket? We've looked into both WebSocket object and ConnectionState to no avail.

**Comment by bsergean** [comment]
Are you are talking about client or server mode ?

It's possible to go from an addr something to an ip address, we could try to expose it, but you should know that load balancers and nat make it so that you rarely get the ip address you were expecting.

**Comment by bsergean** [comment]
$ git diff
diff --git a/ixwebsocket/IXSocketServer.cpp b/ixwebsocket/IXSocketServer.cpp
index f1d34e4..8b2a542 100644
--- a/ixwebsocket/IXSocketServer.cpp
+++ b/ixwebsocket/IXSocketServer.cpp
@@ -307,6 +307,9 @@ namespace ix
                 continue;
             }
 
+            char *ip = inet_ntoa(client.sin_addr);
+            logInfo(ip);
+
             std::shared_ptr<ConnectionState> connectionState;
             if (_connectionStateFactory)
             {

We would have to propagate this (and handle ivp6 properly too) + the port number. Calling this remoteAddress, and exposing it through the onOpen callback probably, or just though the connection callback.

**Comment by bsergean** [comment]
This should be fixed now in the mainline, please give it a try.

**Comment by rafalsk** [comment]
@bsergean I have verified this to work (haven't had an opportunity to test IPv6 addresses) but as far as IPv4 it works just fine. Thank you.
