### ISSUE TITLE
Possible deadlock at connection close when running a parallel thread on the same websocket

### ISSUE THREAD

**Issue by marcelkauf** [machinezone/IXWebSocket#223]
We have the requirement to start a parallel worker thread when a connection is established to the server in order to periodically send data to the client. So the websocket is used by a thread in the ixwebsocket lib and a thread on our side. When the client closes the connection, there currently does not seem to be a proper way of ending the worker thread, at least we cannot join the thread without running into a deadlock.

The first image shows the stacktrace of the library thread when the close message of the client is received. The lib calls `setReadyState(close)`, locks `_closeDataMutex`, calls our close handler that sets a stop flag in the worker thread and joins the worker thread. But if the worker thread is currently sending data, a deadlock occurs because the send method also calls `setReadyState(close)` and tries to lock the mutex that is already locked by the websocket thread (second image).

We can solve the situation by just detaching the worker thread, but this feels more like a workaround and has other effects (see next issue). Do you have any advice for this situation?

![WebsocketThread](https://user-images.githubusercontent.com/31201841/87016753-67145c00-c1cf-11ea-8187-d5a00dd24960.png)
![WorkerThread](https://user-images.githubusercontent.com/31201841/87016771-6da2d380-c1cf-11ea-8a61-f1d7c9c4c332.png)

**Comment by bsergean** [comment]
I think that this commit (22dffd5b7e5b4938a89c7182b9fc50515e95f42a) should fix this ; it eliminates the  _closeDataMutex.

I ran into a very similar dead-lock which went away after that commit.
