### ISSUE TITLE
Websocket destructor is not called after closing the connection

### ISSUE THREAD

**Issue by marcelkauf** [machinezone/IXWebSocket#224]
The WebSocket destructor is not called when closing a connection because the callback
`webSocket->setOnMessageCallback([webSocket, connectionState](const ix::WebSocketMessagePtr& msg){}` that is stored in `WebSocket::_onMessageCallback` is never reset. Thus we have a cyclic reference websocket -> onMessageCallback -> websocket and thus a memory leak. See #225  with the corresponding testcase.

It is not mentioned in the docs that resetting the callback is something the user has to do. And in my opinion that would not feel right since the websocket is created in the server code. I tried to reset the callback at the end of ` WebSocketServer::handleConnection` via `websocket->setOnMessageCallback(nullptr)` so that the websocket is correctly destroyed. But since this callback is also stored in `_ws.setOnCloseCallback`, this results in a segmentation fault with the workaround mentioned in #223 when a parallel worker thread tries to call the OnCloseCallback.

**Comment by bsergean** [comment]
Thanks for the report and unittest @marcelkauf.

We could reset the callback in the destructor. I can't quite remember why it isn't done. One thing is that we want to invoke a callback with a 'about to destroy' or 'closing' equivalent in the destructor.

Maybe the behavior should be different for a websocket client and server object in that case. Or we would stop to manually call the close in the websocket server handle connection case.

**Comment by bsergean** [comment]
Hey something to know about ; the connectionState object which is a shared pointer is passed down in a lamdbda capture, that doesn't always work well.

A good reading on it -> https://eklitzke.org/notes-on-std-shared-ptr-and-std-weak-ptr

If you have suggestions on how to fix this please bring it up.

Another thing to know: we have a set of connected clients, which might be a problem (this is helpful when implementing chat like applications to broadcast messages to all the connected clients). Maybe we could get rid of it, and leave it to the application level to handle this.

**Comment by rafalsk** [comment]
What's the best workaround to handle this case? Top-notch stability an utmost priority over here.

**Comment by bsergean** [comment]
I think this is fixed now @marcelkauf

**Comment by marcelkauf** [comment]
Yes it is. Thanks for the fix.
