### ISSUE TITLE
Building Tips

### ISSUE THREAD

**Issue by jakemumu** [machinezone/IXWebSocket#229]
Hey, 

I'm a cpp developer who uses JUCE & Xcode. Most projects I build are fairly inclusive (all files contained in the project), and when I've linked to external libraries in the past they've been mostly header only. I've been able to get away in the past by simple pointing the project to the extra header search paths. I'm having a bit of trouble linking to this library because Xcode isn't picking up & compiling the .cpp files although it's finding the headers fine. 

Are there any setup steps or tips on how to integrate this into an Xcode project? 

Thanks, 

Jake

**Comment by bsergean** [comment]
You're going to have to include the .cpp files when you build for Xcode. They are all in the ixwebsocket folder.

You should read about CMake and look at the top level CMakeList.txt files. It will display the extra frameworks (Security and CoreFoundation) that you'll have to link with.

**Comment by rossum2** [comment]
Hello,

I have a similar problem: having some hard time in linking the code. One would expect to build & link the library like

`g++ -lixwebsockets -lzlib -o executable mycode.cpp`

This however gives linking errors. What was the intended way of building code using this library? How should one link it? Is someone not using cmake supposed to burn in linker-error hell :-)  ?

Thanks,
Jan

**Comment by bsergean** [comment]
Short answer, (1) send your linker error + (2) try to add -lpthread
> g++ -lixwebsockets -lzlib -lpthread -o executable mycode.cpp
> 


You will burn a bit in hell indeed ; the good news is that you don't need to use cmake but what you can do is just learn enough cmake to navigate your way through.

target_link_libraries is the directive to drive the linker. Here are the sort of the things I find when I grep for it.

(venv) IXWebSocket$ grep target_link_libraries CMakeLists.txt
    target_link_libraries(ixwebsocket ${OPENSSL_LIBRARIES})
    target_link_libraries(ixwebsocket ${MBEDTLS_LIBRARIES})
    target_link_libraries(ixwebsocket "-framework foundation" "-framework security")
target_link_libraries(ixwebsocket ${ZLIB_LIBRARIES})
  target_link_libraries(ixwebsocket wsock32 ws2_32 shlwapi)
    target_link_libraries(ixwebsocket Crypt32)
  target_link_libraries(ixwebsocket ${CMAKE_THREAD_LIBS_INIT})

What I recommend is to build and link with CMake as a test, with make VERBOSE=1, this will display everything.

**Comment by jakemumu** [comment]
Heya, yea I've still bring struggling with this in XCode. I use header mapping in Xcode so the relative nature of the includes makes it a no go of adding directly to the project. I added the headers as from extra header paths, and then compiled the library using the cmake commands at added it to the Xcode dependency, along with the various libraries listed here. 

Still was having a struggle with it : / 

Let me take another look tonight and I'll try to get it building and share the steps for people that let Xcode handle 100% of their compilation.

Best,

Jake

**Comment by jakemumu** [comment]
I believe it was something with the OpenSSL library which was complaining, all this socket / network stuff in C++ land is new to me, so I'm still trying to wrap my head around how everything comes together

**Comment by bsergean** [comment]
If you build for macOS you don't need OpenSSL, take a look at the CMake files.
