### ISSUE TITLE
(Build warning) IXSocketOpenSSL.cpp:293:67: warning: unused parameter ‘hostname’ [-Wunused-parameter]

### ISSUE THREAD

**Issue by pseigo** [machinezone/IXWebSocket#230]
I pull IXWebSocket into my project with cmake's FetchContent. Each time I build the library, I get:

```c++
[ 81%] Building CXX object _deps/ixwebsocket-build/CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketOpenSSL.cpp.o
_deps/ixwebsocket-src/ixwebsocket/IXSocketOpenSSL.cpp: In member function ‘bool ix::SocketOpenSSL::openSSLCheckServerCert(SSL*, const string&, std::__cxx11::string&)’:
_deps/ixwebsocket-src/ixwebsocket/IXSocketOpenSSL.cpp:293:67: warning: unused parameter ‘hostname’ [-Wunused-parameter]
                                                const std::string& hostname,
                                                                   ^~~~~~~~
```

It looks like `hostname` is only used when `OPENSSL_VERSION_NUMBER < 0x10100000L`, otherwise g++ thinks `hostname` is unused.

https://github.com/machinezone/IXWebSocket/blob/847fc142d19479ff30df891156e7c25670dd4b6b/ixwebsocket/IXSocketOpenSSL.cpp#L292-L359

A quick fix might be to disable `-Wunused-parameter` for that parameter.

Thanks!

**Comment by bsergean** [comment]
I agree that this warning is annoying, but I can't remember if the code is properly validating the peer or not

const std::string& /*hostname*/,

This would fix the warning, but I prefer to keep it until I (or you if you are interested in investigating) make sure we are validating properly.
