### ISSUE TITLE
bind for port 0

### ISSUE THREAD

**Issue by asmirnov69** [machinezone/IXWebSocket#231]
Is it possible to have port value zero handled? 
bind() to zero port should force system to use any available port which can be later found using getsockname()
If I didn't overlook something there is no way to accomplish that using IXWebSocket.

**Comment by bsergean** [comment]
There is a getFreePort() function that used port 0 internally, which is now available (it was in the unittest).

https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXGetFreePort.cpp
