### ISSUE TITLE
Is it safe to send in background thread after some receive?

### ISSUE THREAD

**Issue by tesla1060** [machinezone/IXWebSocket#234]
Hi,

I checked all the example seems to mention the background thread is used to receive. Just would like to check will the below code be safe?

```
webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
    {
       if (msg->type == ix::WebSocketMessageType::Open)
        {
            web_socket.send(request);
        }
    }
);
```

**Comment by bsergean** [comment]
Yes this will work just fine. 

There would be a problem if you were updating one of your own data structure on the background thread (the one that execute the callback), and what I would call the control thread, the one where you have instantiated your websocket object. You would have to use mutex etc... to handle this if you need concurrent access.

**Comment by tesla1060** [comment]
thanks. got it.
