### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by SunHxiao** [machinezone/IXWebSocket#237]
Hi, I am very interested in this IXWebsocket.
I would like to use this.
By the way, I am a beginner on the c++.
I don't know how to run it.
Would you possibly inform me about that?
I will wait for your favorable reply.
Thanks.

**Comment by bsergean** [comment]
The README file has a simple example, you should start by compiling it.

You will need to learn C++, using CMake, basic compilation tricks etc... you can find this on the web and lookup your error messages. I cannot teach you all of this on my own :)

/*
 *  main.cpp
 *  Author: Benjamin Sergeant
 *  Copyright (c) 2020 Machine Zone, Inc. All rights reserved.
 *
 *  Super simple standalone example. See ws folder, unittest and doc/usage.md for more.
 *
 *  On macOS
 *  $ mkdir -p build ; cd build ; cmake -DUSE_TLS=1 .. ; make -j ; make install
 *  $ clang++ --std=c++14 --stdlib=libc++ main.cpp -lixwebsocket -lz -framework Security -framework Foundation
 *  $ ./a.out
 */

#include <ixwebsocket/IXNetSystem.h>
#include <ixwebsocket/IXWebSocket.h>
#include <iostream>

int main()
{
    // Required on Windows
    ix::initNetSystem();

    // Our websocket object
    ix::WebSocket webSocket;

    std::string url("wss://echo.websocket.org");
    webSocket.setUrl(url);

    std::cout << "Connecting to " << url << "..." << std::endl;

    // Setup a callback to be fired (in a background thread, watch out for race conditions !)
    // when a message or an event (open, close, error) is received
    webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
        {
            if (msg->type == ix::WebSocketMessageType::Message)
            {
                std::cout << "received message: " << msg->str << std::endl;
            }
            else if (msg->type == ix::WebSocketMessageType::Open)
            {
                std::cout << "Connection established" << std::endl;
            }
        }
    );

    // Now that our callback is setup, we can start our background thread and receive messages
    webSocket.start();

    // Send a message to the server (default to TEXT mode)
    webSocket.send("hello world");

    while (true)
    {
        std::string text;
        std::cout << "> " << std::flush;
        std::getline(std::cin, text);

        webSocket.send(text);
    }

    return 0;
}

**Comment by SunHxiao** [comment]
HI.
Thanks for your reply.
Would you please make a tutorial video for me?
Or
https://github.com/mikha-dev/mt4-websockets
Would you please compile this?
Thanks for your favorable reply.
Thanks.

**Comment by bsergean** [comment]
I don't have the time to make a video recording teaching C++ :) / the web is full of it you need to learn to use Google :) !
