### ISSUE TITLE
Reconsider the new API

### ISSUE THREAD

**Issue by rafalsk** [machinezone/IXWebSocket#238]
This relates to this , too early closed 
[Issue](https://github.com/machinezone/IXWebSocket/issues/227)

The 'new API' forces us to handle events on per-server basis, rather than per socket basis. Even more, the server's setOnClientMessageCallback does not even take a callback anymore but provides immediate values from what I can see. That is very counter-intuitive and against widely proclaimed  object-oriented guidelines. The message-event should be connection/socket specific rather than server-specific (like it used to be). Registering for a new callback on connection-basis does not hurt anyone. 

Better to have good design rather than 1-less line of code. You basically got rid of the connection/server decoupling.

Anyway; if you insist on the 'new API' which in fact gets rid of per-connection-specific callbacks. Still, in any well designed software one will want to have these two concept separate - the connection and server. Then, how are we supposed to be associating our internal 'connection-specfic'-objects with with the single server.setOnClientMessageCallback your library fires. Then I suppose the function name needs to be changed as there's no callback being registered.

We need good design as bad-design decisions have long-lasting effects. Consider the previous case with the lack of registering for onMessagecallback an improper use of the library. What if the server decided that it does not want to handle the connection at all? It is still required to register for the onMessagecallback for the connection which he is already shutting down according to what you've said.  Thus besided the event fired for closed sockets, we're getting improper handling for when the connection was decided not to be handled by the server i.e. based on the IP. 

Going futher the very simple as might be believed fact of forcing one to register for a callback forces as to create an entire Conversation object, spawn a new Controller thread responsible for managment of that specific Conversation, which in turn registers for the callback. Now to cope with the situation we need to set a flag even before the object is 'activated' that it will need to shutdown right away. Of course, we might integrate more tightly around the library but what's the point if not supporting a situation when user did not register for a callback is indeed an invalid behavior at all rationality.

The new API might be an attempt to get rid of all the pointers/events-related problematics but at a **very high-cost.**

All of our issues are gone IF we postpone deletion of objects containing event-handers UNTILL the library does not decide to fire them up anymore. Let us keep in mind that this is a work-around. Also, we got rid of the issue caused by the fact that the library does not support a situation in which server decided to end the conversation on-sight due to excessive incoming connections WITHOUT registering for onMessageCallbacks, we did that by spawning the entire Conversation (per connection)machinery and setting telling the connection to transit to an 'ending' state right away. Thus we accomplished that at a very high overhead, making DOS attacks even more effective. Of course we might integrate more tightly into the behavior of the library. Still let us reconsider, while maintaining proper design-rationality .

**Comment by bsergean** [comment]
The 2 apis are available right now, so you can use the old one if you prefer. I will likely keep it given that it's not too much code to retain both.

You could use a boolean to know whether the connection just got established or not, and store that in the ConnectionState.
