### ISSUE TITLE
OnProgressCallback Documentation?

### ISSUE THREAD

**Issue by davewhipps** [machinezone/IXWebSocket#239]
This library is amazing, and exactly what I needed! I have a question or two, specifically about the OnProgressCallback class. It's not clear what the return value should be? true to cancel? What exactly do the parameters "current" and "total" refer to? Is there some documentation that I missed? Sorry and thanks!

**Comment by bsergean** [comment]
Thanks for the good words Dave. I just made a change to the doc to document the callbacks and answer your questions. Feel free to keep asking questions in this ticket if this isn't clear enough.

**Comment by bsergean** [comment]
Also if it's ok/possible you can make a PR explaining how you are using the library (scroll down to the bottom of the README page, or just explain it here.
