### ISSUE TITLE
Interface of OnMessageCallback

### ISSUE THREAD

**Issue by akapur** [machinezone/IXWebSocket#24]
Great library. Very useful. Very easy to use. Thank you for your hard work. 

Having gotten into the weeds as a library user for the past 2 days, I would however suggest one major improvement from a user's perspective. If you'd like some help with this, I'd be happy to volunteer. Basically I'm happy to send you a pull request IF this is something you think you want in your library. If there is a reason you don't think this should happen, I'd love to know what it is before I start.

The callback function called when there is a message is passed a const reference to a string. I would suggest that there should also be an option to be called back with a pointer (possibly a standard library safe pointer) to a null terminated char* instead and possibly even a view to the relevant part of _rxbuf.

The reason is that in many cases what's being passed around in messages sent over websockets is JSON. If JSON (this also applies to various other text based message formats) is what is being passed it turns out that you can either allocate a bunch of memory to parse it or parse it in situ, ie by modifying the character buffer passed to the parser to create various tokens. The in situ methods are much faster, they avoid the allocation overhead, avoid most of the copying, and are guaranteed to be safe because they never go past the null pointer at the end, though they may add one or more in the middle which could cause strlen problems. By creating the relevant tokens in place you ALWAYS end up using less space than the length of the original JSON string.

It turns out that the library currently copies the relevant data into a string, and then passes a const reference to that. When the callback function returns the string is discarded, so there is no real reason for it to be const or for it to be a std::string which by convention makes the underlying char pointer opaque. Based on my examination of the code I've actually started const casting what I get from the string's c_str method and using that for in situ parsing and it all works. For a high volume of small messages this halved the cpu usage and memory usage of my initial implementation which copied the string into a char buffer before parsing in situ.

You are essentially telling the library user who doesn't get into the library implementation that they can't use the memory allocated to hold the data. This is sub-optimal because you are allocating memory to have something to pass and then immediately throwing it away so what happens to it doesn't really matter. If you do in fact start returning char buffers, I would suggest that this the buffer should be null terminated. The null makes JSON (and other text formats) parsing (potentially much) faster because you don't have to check your index against the length after each character. I would also suggest providing a length (as you already do) for parsing formats where that is better since you already have the length.

Even better would be if you simply provided a view into the appropriate portion of the (already unmasked) _rxbuf directly. Even if the callee modified this part of _rxbuf it doesn't really make a difference because once the callback returns you discard this portion of _rxbuf anyway. A good JSON in situ parser is not going to modify anything beyond the end of the part of the _rxbuf passed to it. And it would save the allocations and copying necessary to create the string that you are passing now and is potentially a huge performance win for a user of the library, essentially as large as the win from my using the c_str pointer from the string. Even after doing that, a program I wrote that user your library to receive a high volume of small JSON messages, parse them into a binary format, do light processing and then pass on the much smaller binary data onto multiple destinations spends a large percentage of it's time copying the relevant sections of the _rxbuf into a std::string before calling the callback.

**Comment by bsergean** [comment]
Hey Ashwin, thanks a lot for trying this out and explaining your improvement suggestion in great details. 

I like the std::string interface as it makes it a no brainer to use this code. Whenever I work with a new library and the interface is more complicated than a string I need to think twice... but indeed it isn't the most efficient solution. This library needs to work with MsgPack as well as JSON, and MsgPack might contains NULL chars, so I don't know if we'll be able to use char* and put null characters in there. However we might be able to return some const iterators to the beginning and the end of the std::vector<uint8_t> which holds the data.

Another idea, not unlike how some graphics API such as OpenGL work, would be to have the client supply a buffer (std::vector) to receive the data. With that approach, we would memcpy data from the _rcv buffer into that _userBuffer, and we wouldn't create as many temporary strings.

My feat with exposing an external buffer, or some guts of the api is that the app using the lib could 'mess up'. Can you say which JSON library you are using, out of curiosity ? We are using https://github.com/open-source-parsers/jsoncpp which I think can also work with raw char* pointers.

**Comment by bsergean** [comment]
The other things that needs to be sorted how is how to deal with large messages (cf getMergedChunks / and _chunks usage in IXWebSocketTransport.cpp).

**Comment by bsergean** [comment]
Yet another idea is to emit a small wrapper class (MessageData ?) which holds something low level (pointer + size or STL iterators on the backing std::vector), but has convenience methods to convert to std::string, which is something that will be handy for many simple cases, or get to the 'real data' when we want to write to a file for example (as done by [ws receive](https://github.com/machinezone/IXWebSocket/blob/master/ws/ws_receive.cpp)).

**Comment by akapur** [comment]
I'm using RapidJSON. It's not much slower than a hand written parser I wrote myself, which is customized to my messages, not as robust as I'd like, and not a general JSON parser, and I don't have to maintain it. Tencent is already working on a version that uses SIMD to make things even faster which is the only idea I have to make my hand coded version faster. 

I'm generally not too worried about the "if you mess up scenario". It's C++ not python. If you are OK with copying and want safe and cuddly, use the string interface and all is fine. If you want serious efficiency, then you can't have safe and cuddly.  If you mess up hopefully you get a segfault. Otherwise you get corrupted messages for a while followed by a segfault or given that it's undefined behavior possibly global thermonuclear war. There are memory fence libraries available for people to run their code with in test to ensure they aren't doing anything non-kosher if they use the efficient interface.

For large chunks I think initially the interface remains the same. You just pass pointers to the aggregated array. Eventually, I think you pass the chunks so the user can pass them directly to a streaming parser because the chunks get thrown away after use as well but I think that should be a version away after the initial interface changes are working.

FYI, even if you are parsing a message with embedded nulls (or some other message termination character), it's always faster to terminate with that character AND have a length. If you know you don't have embedded termination characters then you never check length. If embedded termination characters in the string are possible, you only check the length when you see a termination character.

Unless you want the user to copy the data in the string, even a non-const std::vector< uintt8_t > is better than string. The problem with string is that if messages are small you can have serious issues const casting the pointer returned by c_str because of small string optimization.

**Comment by bsergean** [comment]
Cool. I'm definitely opened to a new interface. I like the small thin object that wrap pointers or iterators and that can make an std::string for you. That helps with user friendliness, even if this is C++ not python.

// Maybe something like that
class MessageData
public:
   MessageData(...) : _data(data), _size(size)

   std::string str() { return std::string(_data, size); }
   uint8_t* data() const { return _data; }
   size_t size() const { return _size; }

private:
   uint8_t* _data;
   size_t _size;
};

I'd love if there was a way to invalidate that data once the callback has been invoked, and all those pointers are no longer valid. Not sure how feasible that is though.

**Comment by bsergean** [comment]
@akapur do you still care about this ?

**Comment by akapur** [comment]
I do. A minor change where I just (unsafely) use the c_str from the string returned seems to be working fine for me. Been really busy with other stuff so haven’t had time to take a look at stuff.

**Comment by bsergean** [comment]
Cool, good to hear. I'm super busy myself ;)

**Comment by bsergean** [comment]
Hey @akapur I'm sorry but the code has evolved a bit, there's zlib / per message deflate compression + fragmented messages receiving + utf-8 TEXT validation + a bunch of other places where I used std::string, and stopping doing this would be annoying...

I'm gonna close this... I think you were happy with your modified/forked version, I hope you still are ; I'm afraid that change would be hard to merge.

ps: there's server support now, and a bunch of other new things since May !
