### ISSUE TITLE
Messages on macOS SSL do not finish sending

### ISSUE THREAD

**Issue by bhackett1024** [machinezone/IXWebSocket#246]
While testing IXWebSocket I'm seeing a problem where sends do not complete, with no indication AFAICT to the API caller.  If writing to the outgoing socket during a send fills up the socket fd and writing to it returns EAGAIN, SocketAppleSSL::writeToSocket returns errSSLWouldBlock and this bubbles up to SocketAppleSSL::send returning an EWOULDBLOCK error.  WebSocketTransport::sendOnSocket recognizes this but returns a true result as if the send succeeded.

I fixed this locally by converting SocketAppleSSL::send to a blocking API (even if it needs to busy-wait to be able to send) per the patch below.

```
diff --git a/ixwebsocket/IXSocketAppleSSL.cpp b/ixwebsocket/IXSocketAppleSSL.cpp
index f58e0c8..429f6cf 100644
--- a/ixwebsocket/IXSocketAppleSSL.cpp
+++ b/ixwebsocket/IXSocketAppleSSL.cpp
@@ -268,12 +268,6 @@ namespace ix
                 errno = ECONNRESET;
                 return -1;
             }
-
-            if (status == errSSLWouldBlock)
-            {
-                errno = EWOULDBLOCK;
-                return -1;
-            }
         }
         return -1;
     }
```

**Comment by bsergean** [comment]
If there's a failure to send (kernel buffer being full is one example), the background thread will make this happen, in WebSocketTransport [code](https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXWebSocketTransport.cpp#L316).

```
        // Make sure we send all the buffered data
        // there can be a lot of it for large messages.
        if (pollResult == PollResultType::SendRequest)
        {
            if (!flushSendBuffer())
            {
                return PollResult::CannotFlushSendBuffer;
            }
        }
```

I cannot take your patch as it would make send blocking which goes against the library design.

What you could do without any change to the library in your send code, if it's ok to do so is busy loop and check the buffereAmount return value. You can search for that in the [code](https://github.com/machinezone/IXWebSocket/blob/master/ws/ws.cpp#L496).

```
        do
        {
            size_t bufferedAmount = _webSocket.bufferedAmount();
            spdlog::info("ws_send: {} bytes left to be sent", bufferedAmount);

            std::chrono::duration<double, std::milli> duration(500);
            std::this_thread::sleep_for(duration);
        } while (_webSocket.bufferedAmount() != 0 && _connected);
```

**Comment by bhackett1024** [comment]
Cool, thanks for the information.  I didn't see any send activity on the background thread; the (non-public) test I'm using creates a client socket, connects to a server using TLS, and uploads about 40 MB of data in 1 MB chunks, but not all the data was actually sent on the outgoing socket fd, even after a long wait.

**Comment by bsergean** [comment]
I've used the library on macOS over TLS to send files larger than that ; I would add the bufferAmount loop I'm talking about, print periodically and see how it goes.
