### ISSUE TITLE
Document correction

### ISSUE THREAD

**Issue by coleged** [machinezone/IXWebSocket#248]
Just built this on MacOS. Apart from a few dependency/revision fixes, all went to plan. Comment on build instruction document.

Install instructions for CMake. You need a 'cd ..' after the 'cmake' and 'make -j' seems to to an install

Document currently says --->
mkdir build # make a build dir so that you can build out of tree.
cd build
cmake -DUSE_TLS=1 ..
make -j
make install # will install to /usr/local on Unix, on macOS it is a good idea to sudo chown -R `whoami`:staff /usr/local

**Comment by bsergean** [comment]
there's a top level makefile that I use for convenience, and the one generated by cmake when you do an out of tree build from the build folder. I think this adds some confusion.
