### ISSUE TITLE
android can not recieve message

### ISSUE THREAD

**Issue by shiliupingGitHub** [machinezone/IXWebSocket#251]
I make a dll for unity3d  ,  It works fine  on windows , But Not ok on android .  the url is  "wss://xxxx:“。   ”   ，  I track the code,  final    I get the error  in  the "IXNetSystem.cpp"  ::poll(fds, nfds, timeout);    the function always return -1  and the errorno  is alaways 4.   how can  I fixed  ,  forgive my pool english

**Comment by shiliupingGitHub** [comment]
ndk  version  is  21b

**Comment by bsergean** [comment]
Given that you are on Android, you need to specify a cacert, I think that's your problem.

Check this out
https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration

**Comment by shiliupingGitHub** [comment]
I  set  cafile = NONE  ,  It works  well  on  windows.  on  android It  looks  like  the  function  "poll"   does  not  work.   it  always  return  -1.     maybe  ndk  problem?

**Comment by shiliupingGitHub** [comment]
just  work  for  the  client  side

**Comment by bsergean** [comment]
poll should work fine on Android as well, it was working with earlier version of ixwebsocket for sure.

returning -1 is ok everyone in a while / have you printed the error messages ?

**Comment by shiliupingGitHub** [comment]
yes ,      errorno   value  is  4,  It  means  system  call  interrupt .   I  don't know  why .   I  just  guess  it  was  ndk  problem

**Comment by bsergean** [comment]
Ah that's interesting.

Usually when the errno is this value, the function needs to be called again. I never ran into this before.

**Comment by shiliupingGitHub** [comment]
and  also  In  your  code  ,  if  the  return  value  is  -1,  you  will  close  the  socket

**Comment by bsergean** [comment]
https://github.com/pytorch/pytorch/issues/4220 <https://github.com/pytorch/pytorch/issues/4220>

Maybe we need to have a thin wrapper that re-run the function a couple of times (not sure how many times) like they do here if the return value is system call interrupt.

**Comment by shiliupingGitHub** [comment]
emm  ,I  makes  a  loop  to wrap  this ,  it  looks  like  return  -1   forever  . so  what  version  ndk  have  you  tested  before

**Comment by bsergean** [comment]
Can you try this ?

$ git diff IXNetSystem.cpp 
diff --git a/ixwebsocket/IXNetSystem.cpp b/ixwebsocket/IXNetSystem.cpp
index 195d129..02c9cd3 100644
--- a/ixwebsocket/IXNetSystem.cpp
+++ b/ixwebsocket/IXNetSystem.cpp
@@ -105,7 +105,15 @@ namespace ix
 
         return ret;
 #else
-        return ::poll(fds, nfds, timeout);
+        // We follow the style from libuv
+        int ret = -1;
+        do
+        {
+            ret = ::poll(fds, nfds, timeout);
+        }
+        while (ret == -1 && errno == EINTR)
+
+        return ret;
 #endif
     }

**Comment by bsergean** [comment]
Hum I don't really remember, 19, 20 I believe.

**Comment by bsergean** [comment]
@tiwariashish86 would know better about ndk versions ... Hi Ashish !

**Comment by shiliupingGitHub** [comment]
emm  .   I  will  use  another vesion  ndk to  test.   thank  you  very  much

**Comment by shiliupingGitHub** [comment]
int ret = -1;
+        do
+        {
+            ret = ::poll(fds, nfds, timeout);
+        }
+        while (ret == -1 && errno == EINTR)
+
+        return ret;


I have tested  , this code solve my problem  , thx

**Comment by bsergean** [comment]
Great. I have released that fix in the latest version of the library.

**Comment by bsergean** [comment]
v11.0.4
