### ISSUE TITLE
WebSocketServer::handleConnection() HTTP status: 400 error: Invalid Upgrade header, need WebSocket, got websocket

### ISSUE THREAD

**Issue by flagarde** [machinezone/IXWebSocket#252]
Hi,

Trying to connect to WebSocketServer I obtained this error WebSocketServer::handleConnection() HTTP status: 400 error: Invalid Upgrade header, need WebSocket, got websocket

Digging into your code it should not happen as you are using 
```cpp
insensitiveStringCompare(headers["upgrade"], "WebSocket")
```

**Comment by bsergean** [comment]
I just changed this code yesterday so maybe I messed up. If you can write a unittest for it and try to fix it it would be appreciated, I have a feeling it will be a simple fix.

**Comment by bsergean** [comment]
I fixed it, thanks for reporting. Please give it a try and tell if I'm lying.

**Comment by flagarde** [comment]
Hello,

It works like a charm !

Thank you for your quick fix.

----- Mail original -----
De: "Benjamin Sergeant" <notifications@github.com>
À: "machinezone/IXWebSocket" <IXWebSocket@noreply.github.com>
Cc: "lagarde" <lagarde@sjtu.edu.cn>, "Author" <author@noreply.github.com>
Envoyé: Mardi 17 Novembre 2020 06:46:51
Objet: Re: [machinezone/IXWebSocket] WebSocketServer::handleConnection() HTTP status: 400 error: Invalid Upgrade header, need WebSocket, got websocket (#252)

I fixed it, thanks for reporting. Please give it a try and tell if I'm lying.

**Comment by bsergean** [comment]
Great. If you are free and willing to say how you are using the library you can put a note or make a PR in the README file (see at the bottom there's a section that does that).

Have a good day !
