### ISSUE TITLE
Client proxy support

### ISSUE THREAD

**Issue by ouwou** [machinezone/IXWebSocket#253]
any chance of supporting connecting through a proxy? ideally HTTP+HTTPS+SOCKS type but hopefully at least HTTP+HTTPS. useful for debugging by proxying through fiddler/charles etc.

**Comment by bsergean** [comment]
I am not familiar with how proxy works.

I tried reading https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_method <https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_method> but I don't really see how it would apply to this library.

Do you have links to other libraries that have implemented this ?

(ps I'm gonna be away from the computer for a bit)

**Comment by lorpus** [comment]
qt's [QWebSocket](https://doc.qt.io/qt-5/qwebsocket.html) does http+socks, [websocketpp](https://github.com/zaphoyd/websocketpp/) does http, and i believe [libwebsockets](https://github.com/warmcat/libwebsockets/) can do it but i haven't tested that one myself. i'm not super familiar with the inner workings of proxies either but looking at [this](https://blogs.oracle.com/pavelbucek/websocket-via-http-proxy) it doesn't seem to be terribly complicated for HTTP proxies
