### ISSUE TITLE
how to run the server!

### ISSUE THREAD

**Issue by flyerSon** [machinezone/IXWebSocket#254]
#include <iostream>
#include <ixwebsocket/IXWebSocketServer.h>
#include <ixwebsocket/IXConnectionState.h>

int main()
{
	uint32_t port = 30000;
	ix::WebSocketServer server(port);
	server.setOnClientMessageCallback([](std::shared_ptr<ix::ConnectionState> connectionState, ix::WebSocket& webSocket, const ix::WebSocketMessagePtr& msg)
		{
			std::cout << "Remote ip: " << connectionState->getRemoteIp();
			if (msg->type == ix::WebSocketMessageType::Open)
			{
				std::cout << "id: " << connectionState->getId() << std::endl;
			}
			else if (msg->type == ix::WebSocketMessageType::Message)
			{
				webSocket.send(msg->str, msg->binary);
			}
		}
	);

	auto res = server.listen();

	if (!res.first)
	{
		std::cerr << "listen error:" << res.second << std::endl;
	}
	else
	{
		server.start();

		std::cout << "wait for here" << std::endl;

		server.wait();
	}

	std::this_thread::sleep_for(std::chrono::seconds(1000));

	
}

win10 vs2019 build and run it ,output error creating socket): Unknown error

**Comment by flyerSon** [comment]
i solve the problem，in IXWebSocketServer.cpp:79line (istd::pair<bool, std::string> SocketServer::listen()function),i add code ,it work

#ifdef WIN32
		WORD wVersionRequested;
		WSADATA wsaData;
		wVersionRequested = MAKEWORD(1, 1);
		if (int err = WSAStartup(wVersionRequested, &wsaData))
		{
			std::string errMsg("SocketServer::listen() WSAStartup error");
			return std::make_pair(false, errMsg);
		}
#endif

**Comment by bsergean** [comment]
// Required on Windows
    ix::initNetSystem();

Will do what you have done in your ifdef WIN32

**Comment by flyerSon** [comment]
yeah，add ix::initNetSystem();，it work. i forget it
