### ISSUE TITLE
after upgrade, no longer working on iOS

### ISSUE THREAD

**Issue by morty346** [machinezone/IXWebSocket#255]
Upgraded from 7.9.2 to 11.0.4
Android, Windows, Mac OS X all working as expected
When building to arm64 iOS When trying to make a HTTP request I get the following:

Cannot connect to url: https://xxx / error : error in handshake : THREADING - Locking / unlocking / free failed with error code 1

The biggest difference seems to be that I had to include the static libs for mbed in the build as well as change a shared_ptr to a weak_ptr. Everything compiles so I believe I did everything correctly (building from Conan)

 Snippets of the offending code (removed a lot of the error checking to keep it brief)
void CInterpreterCloudService::GetClientID()
	{
		std::map<std::string, std::string, CaseInsensitiveLess> headers;
		std::string combined = connection_type + base_url + "api/config";
		
		std::shared_ptr<InterpreterMessage> im = std::make_shared<InterpreterMessage>();
		im->_httpClientMsgCallback = HandleClientIDReponse;

		m_ixWebClient.Send(combined, headers, "", im, RequestType::RT_GET);
	}

void CIXWebAPI::Send(std::string url,
        std::map<std::string, std::string, CaseInsensitiveLess> headers,
        std::string body, std::shared_ptr<InterpreterMessage> im, RequestType RequestType)
    {
            std::shared_ptr<HttpClient> hc = GetClientFromPool();
            
            hc->performRequest(GenerateRequest(hc, headers, body, url, RequestType),
                std::bind(MsgHandler, std::placeholders::_1, im,  url));
       
    }

HttpRequestArgsPtr CIXWebAPI::GenerateRequest(std::shared_ptr<HttpClient> hc,
        std::map<std::string, std::string, CaseInsensitiveLess> headers,
        std::string body, std::string url, RequestType requestType)
    {
        HttpRequestArgsPtr args;
        if (requestType == RequestType::RT_GET)
            args = hc->createRequest(url, HttpClient::kGet);
        else if (requestType == RequestType::RT_POST)
            args = hc->createRequest(url, HttpClient::kPost);
        else if (requestType == RequestType::RT_PUT)
            args = hc->createRequest(url, HttpClient::kPut);

        args->extraHeaders = headers;
        args->connectTimeout = 10;
        args->transferTimeout = 100;
        args->followRedirects = false;
        args->maxRedirects = 50;
        args->compress = false;
        args->verbose = false;
        args->logger = [](const std::string& msg)
        {
            std::cout << msg;
        };
        args->body = body;
        SocketTLSOptions stls;
        stls.caFile = "NONE";
        if (bSecure)
            hc->setTLSOptions(stls);
        return args;
    }

**Comment by bsergean** [comment]
Does it fail in iOS simulator as well ?

Soon I might get a new mac which will be arm based.

It could be a bug in mbedtls ?

> THREADING - Locking / unlocking / free failed with error code 1
> 

That error is likely to come from mbedtls.

**Comment by bsergean** [comment]
Can you use DarwinSSL (aka SecureTransport) when building on iOS ? / the bug will likely not manifest that way.

If you are using the conan integration maybe that's a better question for the conan folks.

**Comment by morty346** [comment]
Is there a way to use the older version of mbed that worked before?

**Comment by bsergean** [comment]
Probably, but you'll get better support if you create a ticket on the conan repo.

Here I believe

https://github.com/conan-io/conan-center-index <https://github.com/conan-io/conan-center-index>

https://github.com/conan-io/conan-center-index/tree/master/recipes/ixwebsocket

**Comment by bsergean** [comment]
You can reference this ticket.

applessl

https://github.com/conan-io/conan-center-index/blob/master/recipes/ixwebsocket/all/conanfile.py#L19

If you set applessl for the options you should be good.
