### ISSUE TITLE
multiple ws connections

### ISSUE THREAD

**Issue by dr3adx** [machinezone/IXWebSocket#257]
Hi,

how can I **dynamically** create several ws connections inside a map or a vector? 

for an example:

```
std::unordered_map<int, ix::WebSocket> websockets;
 ix::WebSocket w1;
 ix::WebSocket w2;
websockets[0] = w1;
websockets[1] = w2;
```

I'm trying to establish multiple websocket connections and have easy access to them but above example gives compiler error "copy assignment operator is implicitly deleted"

Thank you!

**Comment by bsergean** [comment]
Looks like you figured it out on your own.
