### ISSUE TITLE
Facing issues with onMessage events

### ISSUE THREAD

**Issue by Yuhanun** [machinezone/IXWebSocket#258]
Hello,

Currently, I'm using IXWebsocket for a project of mine, however, I'm encountering some issues.

My tests: https://hastebin.com/ayucobidos.cpp
Server.hpp: https://hastebin.com/odoheposet.cpp
Server.cpp: https://hastebin.com/unarowituw.cpp
Interface.hpp: https://hastebin.com/vegogifoyu.cpp

However, it doesn't seem to ever receive a valid message (I'm aware of the race condition in the tests themselves, yes.)

The server itself receives a message from the `ai` socket, for which a different library is used, and works completely fine. However, then the websocket never seems to receive it.

Thank you in advance,
John

**Comment by bsergean** [comment]
I can't see your code on hastebin, could you attach it to the issue or better make a compilable gist ?

Are you using ixwebsocket in server or client mode ?

**Comment by Yuhanun** [comment]
https://github.com/roboteamtwente/roboteam_central_server

Both in server and client mode.

test: https://github.com/RoboTeamTwente/roboteam_central_server/blob/main/test/pair_test.cpp
server hpp: https://github.com/RoboTeamTwente/roboteam_central_server/blob/main/include/server.hpp
server.cpp: https://github.com/RoboTeamTwente/roboteam_central_server/blob/main/src/server.cpp
interface.hpp: https://github.com/RoboTeamTwente/roboteam_central_server/blob/main/include/interface.hpp

**Comment by bsergean** [comment]
Just looked at this: https://github.com/RoboTeamTwente/roboteam_central_server/blob/main/test/pair_test.cpp <https://github.com/RoboTeamTwente/roboteam_central_server/blob/main/test/pair_test.cpp>

My recommendation is to print ALL information coming, on client and server, so you know what's happening.

        webSocket.setOnMessageCallback([this](const ix::WebSocketMessagePtr& msg) {
            std::stringstream ss;
            if (msg->type == ix::WebSocketMessageType::Open)
            {
                log("ws_receive: connected");
                spdlog::info("Uri: {}", msg->openInfo.uri);
                spdlog::info("Headers:");
                for (auto it : msg->openInfo.headers)
                {
                    spdlog::info("{}: {}", it.first, it.second);
                }
            }
            else if (msg->type == ix::WebSocketMessageType::Close)
            {
                ss << "ws_receive: connection closed:";
                ss << " code " << msg->closeInfo.code;
                ss << " reason " << msg->closeInfo.reason << std::endl;
                log(ss.str());
            }
            else if (msg->type == ix::WebSocketMessageType::Message)
            {
                ss << "ws_receive: transfered " << msg->wireSize << " bytes";
                log(ss.str());
            }
            else if (msg->type == ix::WebSocketMessageType::Fragment)
            {
                ss << "ws_receive: received fragment " << _receivedFragmentCounter++;
                log(ss.str());
            }
            else if (msg->type == ix::WebSocketMessageType::Error)
            {
                ss << "ws_receive ";
                ss << "Connection error: " << msg->errorInfo.reason << std::endl;
                ss << "#retries: " << msg->errorInfo.retries << std::endl;
                ss << "Wait time(ms): " << msg->errorInfo.wait_time << std::endl;
                ss << "HTTP Status: " << msg->errorInfo.http_status << std::endl;
                log(ss.str());
            }
            else if (msg->type == ix::WebSocketMessageType::Ping)
            {
                log("ws_receive: received ping");
            }
            else if (msg->type == ix::WebSocketMessageType::Pong)
            {
                log("ws_receive: received pong");
            }
            else
            {
                ss << "ws_receive: Invalid ix::WebSocketMessageType";
                log(ss.str());
            }
        });

        webSocket.start();

**Comment by Yuhanun** [comment]
Okay, i'll do that tomorrow and report back.

**Comment by Yuhanun** [comment]
This is the output:
```
john@a4ffd05a2e41:~/roboteam_suite$ ./build/roboteam_central_server/roboteam_central_server_tests 
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ServerTests
[ RUN      ] ServerTests.websocket_test
Constructing AI thread.
Constructing Modules thread.

Ok packet received: 0

New incoming interface connection: 0 (ping: -1)
ws_receive: connected
Uri: /
Headers: 
Connection:Upgrade
Sec-WebSocket-Accept:CayUhNnVX6yIVhgmECZfaVAEj0c=
Server:ixwebsocket/11.0.4 linux nossl zlib 1.2.11
Upgrade:websocket
/home/john/roboteam_suite/roboteam_central_server/test/pair_test.cpp:79: Failure
Value of: received
  Actual: false
Expected: true
Interface connection closed
ws_receive: connection closed: code 1000 reason Normal closure

terminate called without an active exception
Aborted (core dumped)```

**Comment by bsergean** [comment]
So the client connect to the server, and later disconnect, but it does not receive anything.

Is the server sending something whenever the client connect ?

For the crash you should call webSocket.close() probably.
