### ISSUE TITLE
How to correctly stop/close connection from message callback

### ISSUE THREAD

**Issue by ludekvodicka** [machinezone/IXWebSocket#259]
Hello Benjamin,

I'm again playing with your library (because of a lot of issues with libwebsocket) and trying to integrate your library into my project.

Currently, I'm trying to find a way how to correctly close the connection from the message callback:

```
void onMessageCallback(const ix::WebSocketMessagePtr& msg)
{
	if (msg->type == ix::WebSocketMessageType::Message)
	{
                     websocket.close() / stop() / ...;
	}
}
```

When I tried webSocket.stop(), I get assertion because of thread self-join  ` _thread.join();` in method `WebSocket::stop()`.

Next tried `webSocket.close()` but this leads to auto-reconnection as described in this ticket: https://github.com/machinezone/IXWebSocket/issues/172

Now, I'm trying `websocket.disableAutomaticReconnection(); followed by websocket.close();`. And stop() is executed before destruction of the ix::WebSocket object.

This seems to work ok, but I want to make sure that this is the correct way. I know this is maybe a pretty unusual use-case but I'm using this in unit tests to auto-disconnect after receiving n-messages.

Thank you

**Comment by bsergean** [comment]
Hi Ludek,

Your analysis is right and #172 is a good resource. I should improve the code to make it sufficient to just call close() but I haven't had a chance and the reconnection code can be tricky.

**Comment by bsergean** [comment]
We should improve the doc and you can also search in the unittest and the 'ws' subfolder for use cases.

Another way I frequently to this is using a condition variable, or an atomic and have the 'control' thread take care of calling 'stop()' (search for ws_autoroute). But maybe you just want to close and re-open later ?

**Comment by ludekvodicka** [comment]
Thanks for quick reply. It's perfectly fine for me to turn off the auto-reconnect and call close().

control thread would be also a solution, but I believe it's not necessary in this case. In the real application, there will be no situation where the client will close the connection based on the server message.

It's only for unit tests where we're testing both sides of our component and we're simulating all situations including stops, etc.  Also, we're checking connections to several external WS servers and we want to stop tests after receiving several samples. And the simplest way is to wait for data and then immediately stop the client.

For example, this is one of our unit tests (CIxWebsocketClient is a wrapper around your IxClass to be able to quickly swap between libWebsocket and IXWebsocket during the migration process).

```
AX_TEST_CASE(binnance_connection_twst)
{
	bool bConnected = false;
	bool bDisconnected = false;
	XString strReceived;
	CIxWebsocketClient ws("wss://stream.binance.com", 9443);
	ws.ConnectToEndpoint("/ws/bnbbtc@aggTrade",
		[&](stWebsocketEvent&& event)
		{
			if (event.eventType == EnmWebsocketEventType::Open)
				bConnected = true;
			else if (event.eventType == EnmWebsocketEventType::Data)
			{
				strReceived += event.strData;
				ws.DisconnectEndpoint();
			}
			else if (event.eventType == EnmWebsocketEventType::Close)
				bDisconnected = true;
		}
	);
	while (ws.IsConnected() || ws.IsConnecting() )
		axTimeHelper::Sleep(1);

	TEST_CHECK(strReceived != "");
	TEST_CHECK(bConnected == true);
	TEST_CHECK(bDisconnected == true);
}

```
