### ISSUE TITLE
Use IXWebSocket as ExternalProject, convenience makefile is used instead CMake created MakeFile 

### ISSUE THREAD

**Issue by JTejedor** [machinezone/IXWebSocket#261]
When I attempted to use IxWebSocket as ExternalProject using CMake, due CMake rules are case insensitive, gets convenience makefile in ixWebSocket root dir (in the repository) instead the created by CMake (MakeFile). In my environment is not installed Ninja either. My current version of CMake is 3.18

```cmake
  include(ExternalProject)
  find_package(Git REQUIRED)
  
  ExternalProject_Add(
    ixwebsocket_git_download
    GIT_REPOSITORY "https://github.com/machinezone/IXWebSocket.git"
    GIT_TAG v11.0.4
    CMAKE_ARGS
      -DUSE_TLS=OFF
      -DUSE_ZLIB=ON
      -DUSE_WS=OFF
      -DUSE_TEST=OFF
  )
```
Workaround: Erase the file makefile in update time

```cmake
 ExternalProject_Add(
    ixwebsocket_git_download
    ....
    UPDATE_COMMAND ${CMAKE_COMMAND} -E rm -f ${IXWEBSOCKET_SOURCE_DIR}/makefile
   ....
 )
```
This is just a notification for you to consider if the convenience makefile could be moved or renamed.
Feel free to erase this issue if you consider not relevant.

**Comment by bsergean** [comment]
just renamed the makefile
