### ISSUE TITLE
IXWebsocketServer SSL issue

### ISSUE THREAD

**Issue by ludekvodicka** [machinezone/IXWebSocket#262]
I'm trying to use IXWebsocketServer in SSL mode but I think there is some issue inside it.

I have a valid cert/key (generated only for unit-testing via https://www.selfsignedcertificate.com/), the client is configured with CA_FILE = NONE but I'm receiving the following error:

    Unable to connect to localhost on port 8889, error: OpenSSL failed - error:1408F10B:SSL routines:ssl3_get_record:wrong version number

The same certificate and client is working fine between IXWebsocketClient -> uWebsocketServer, but doesn't work between IXWebsocketClient -> IXWebsocketServer.

The reason why I'm trying to make both servers work is that I'm not able to compile uWebsocketServer under OSX now, so I want to use your server on OSX platform now (but the error message is from my Win dev machine).

This is my server code:

	if (m_ssl.IsValid())
	{
		ix::SocketTLSOptions tlsOptions;
		if (m_ssl.pathCaFile.IsEmpty() == false )
			tlsOptions.caFile = m_ssl.pathCaFile;
		if (m_ssl.pathCertFile.IsEmpty() == false)
			tlsOptions.certFile = m_ssl.pathCertFile;
		if (m_ssl.pathKeyFile.IsEmpty() == false)
			tlsOptions.keyFile = m_ssl.pathKeyFile;
		if (m_ssl.strCipher.IsEmpty() == false)
			tlsOptions.ciphers = m_ssl.strCipher;
		m_pimpl->m_webSocketServer->setTLSOptions(tlsOptions);
	}

	m_pimpl->m_webSocketServer->listen();
	m_pimpl->m_webSocketServer->start();

and this is my client code:

	ix::SocketTLSOptions sslOptions;
	sslOptions.caFile = "NONE";
	m_pimpl->m_webSocket.setTLSOptions(sslOptions);
	m_pimpl->m_webSocket.start();

**Comment by bsergean** [comment]
(Generic answer)
Under OS X if you use the default transport most SSL options aren't supported in server (and even client) mode. You will need to compile with OpenSSL or MbedTLS.
Make sure you clean the headers if you install the library (in /usr/local) because switching from one mode to another could be problematic.

Also tor setting options properly and generating certs:

Look at:
https://github.com/machinezone/IXWebSocket/blob/master/ws/generate_certs.sh

And 
https://github.com/machinezone/IXWebSocket/blob/master/ws/test_ws.sh <https://github.com/machinezone/IXWebSocket/blob/master/ws/test_ws.sh>

**Comment by ludekvodicka** [comment]
Thanks for the reply and provided links. I'm receiving these errors on Windows 64bit too. But I have to check how is the library compiled and if OpenSSL is used or not. But on the client side, everything works fine.

**Comment by ludekvodicka** [comment]
Everything should be set as requested. We're using openssl-1.1.1d and this is our cmake command:

cmake .. -G "NMake Makefiles" -DUSE_TLS=1 -DUSE_OPEN_SSL=1 -DCMAKE_INSTALL_PREFIX=q:\SharedLibraries2019\ixwebsocket32 -DOPENSSL_ROOT_DIR=q:\SharedLibraries2019\openssl32 -DOPENSSL_INCLUDE_DIR=q:\SharedLibraries2019\openssl32\include -DOPENSSL_LIBRARIES=q:\SharedLibraries2019\openssl32\lib -DZLIB_INCLUDE_DIR=q:\SharedLibraries2019\zlib32\include -DZLIB_LIBRARY_DEBUG=q:\SharedLibraries2019\zlib32\lib_debug\zlibd.lib -DZLIB_LIBRARY_RELEASE=q:\SharedLibraries2019\zlib32\lib_release\zlib.lib -DCMAKE_BUILD_TYPE=Debug

I will try to generate certs via your script and let you know

**Comment by ludekvodicka** [comment]
I tried it with certs from generate_certs.sh and passed it to the client and server but without a difference. I'm still receiving the error: `OpenSSL failed - error:1408F10B:SSL routines:ssl3_get_record:wrong version number`.

I'm going to try it on ws test app directly.

**Comment by ludekvodicka** [comment]
And the same error occurs with ws test suite:

server: 
```
q:\ExternalLibraries\librariesWindows\IXWebSocket-11.0.4\debug32\ws>ws echo_server --cert-file .certs\trusted-server-crt.pem --key-file .certs\trusted-server-key.pem --ca-file .certs\trusted-ca-crt.pem --tls
[2020-12-26 09:23:58.402] [info] Listening on 127.0.0.1:8008
SocketServer::run() tls accept failed: OpenSSL failed - error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
SocketServer::run() tls accept failed: OpenSSL failed - error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
SocketServer::run() tls accept failed: OpenSSL failed - error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
SocketServer::run() tls accept failed: OpenSSL failed - error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
SocketServer::run() tls accept failed: OpenSSL failed - error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
```

client:

```
q:\ExternalLibraries\librariesWindows\IXWebSocket-11.0.4\debug32\ws>ws connect wss://localhost:8008
Type Ctrl-D to exit prompt...
Connecting to url: wss://localhost:8008
> d
> Connection error: Unable to connect to localhost on port 8008, error: OpenSSL failed - error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
#retries: 1
Wait time(ms): 100
HTTP Status: 0

Connection error: Unable to connect to localhost on port 8008, error: OpenSSL failed - error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
#retries: 2
Wait time(ms): 200
HTTP Status: 0
```

**Comment by ludekvodicka** [comment]
Ws test app works ok when the cert params are passed to client and server too:

```
ws echo_server --cert-file .certs\trusted-server-crt.pem --key-file .certs\trusted-server-key.pem --ca-file .certs\trusted-ca-crt.pem --tls

ws connect wss://localhost:8008 --cert-file .certs\trusted-client-crt.pem --key-file .certs\trusted-client-key.pem --ca-file .certs\trusted-ca-crt.pem
```

so this has to be something in my app. 

But I would like to ask about the reason why I have to enter all these values also on the client-side. I understand the reason for --ca-file but why is necessary to use client-side key/cert? 

Without client-side key/cert there is the following error:

`> Connection error: Unable to connect to localhost on port 8008, error: OpenSSL failed - error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure`

Thanks

**Comment by ludekvodicka** [comment]
Ok, this was a really stupid error ;-)

Although I filled all certificate paths correctly, I forgot to configure also `tls` bool flag to true. Because of that server library still worked without SSL and this was the reason for the cryptic error: `ssl3_get_record:wrong version number`

**Comment by bsergean** [comment]
glad you figured it out

the CI on windows is not super well setup, if you want to help with the GitHub actions so that we can finally build with TLS and run the unittest that would be great (you can do so in a branch).

**Comment by ludekvodicka** [comment]
I don't have any experience with github actions, but I can check it. Right now I have a lot of work with the current project, but I will try to find some spare time and help.

**Comment by bsergean** [comment]
Looks like this is all good, closing.
