### ISSUE TITLE
Contributing to the  project

### ISSUE THREAD

**Issue by HDenied** [machinezone/IXWebSocket#271]
Hi,

I created a Makefile to build ixwebsocket as a library for OpenWRT and I'd like to make a PR referencing your repo. Would be that ok for you? Would you like I perform a PR here as well? As I need to mention a project maintainer in the documentation who should I mention for this project?

Thanks,
S

**Comment by bsergean** [comment]
Hi @HDenied / you can mention me if you want.

You can make a PR for this project, look in the README file at the bottom.

**Comment by bsergean** [comment]
If you send me a link I'll add it to the README file.
