### ISSUE TITLE
Link errors (unresolved external symbol) on Windows and Visual Studio 2019

### ISSUE THREAD

**Issue by EdwardClements** [machinezone/IXWebSocket#272]
I created a simple DLL using the sources from the ixwebsocket folder and a simple entry point.

I get 25 unresolved externals link errors while building the project.

I have attached the build log below, I can also upload the Visual Studio project if necessary.
[IXWebSocketDLL.log](https://github.com/machinezone/IXWebSocket/files/5952193/IXWebSocketDLL.log)

I have also tried to create a Windows Static Library with the same results.

Can anyone help?

**Comment by bsergean** [comment]
Did you create the project files with cmake ?

**Comment by EdwardClements** [comment]
No, I just created a new static Library project using Visual Studio 2019 using the ixwebsocket sources and the preprocessor defiinitions from the make file:
	WIN32;_DEBUG;_LIB;USE_ZLIB=OFF;USE_TLS=1;USE_WS=1;USE_MBED_TLS=1;_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)

Strangely enough, creating a stand-alone console app using Visual Studio 2019 and using the same ixwebsocket sources builds and runs ok.

**Comment by bsergean** [comment]
I'm glad to hear things are working for you now. There is a CMAKE option to export all symbols (cdecl thing) which we could use, if you want to make a PR or adopt CMake please do so.

Closing as it looks like your problems are resolved.
