### ISSUE TITLE
Asynchronous Push Server

### ISSUE THREAD

**Issue by melton1968** [machinezone/IXWebSocket#274]
I'm trying to writer a server that will occasionally receive a subscription from a client and will then need to asynchronous publish data to the client.  From the examples I have successfully been able to build a server that responds synchronously to client messages in the callback, but am not sure how to send messages outside of that callback. 

Can I simply call send from a different thread? That would be great, but not sure if concurrent writing is allowed.

**Comment by bsergean** [comment]
There is a mutex in the send code path so concurrent writing should be permitted.

See https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXWebSocket.cpp#L487
