### ISSUE TITLE
Error: Conflicting Declaration 'typedef SSIZE_T ssize_t'

### ISSUE THREAD

**Issue by PrinceKomali** [machinezone/IXWebSocket#275]
Hello! First of all this library looks great at first glance; was trying to use libwebsockets and it was incredibly confusing.
Also I am a beginner so this may be a dumb question:
I am running the command `g++ lws.cpp -lixwebsocket -lmbedtls -lmbedx509 -lmbedcrypto` (Didn't bother with output file names). However I get this error:```
<pre><code class="cmd">In file included from C:\LIBS\include/ixwebsocket/IXWebSocketHandshake.h:10,
                 from C:\LIBS\include/ixwebsocket/IXWebSocketTransport.h:17,
                 from C:\LIBS\include/ixwebsocket/IXWebSocket.h:20,
                 from lws.cpp:2:
C:\LIBS\include/ixwebsocket/IXSocket.h:17:17: error: conflicting declaration 'typedef SSIZE_T ssize_t'
 typedef SSIZE_T ssize_t;
                 ^~~~~~~
In file included from C:/MinGW/mingw32/i686-w64-mingw32/include/excpt.h:9,
                 from C:/MinGW/mingw32/i686-w64-mingw32/include/windows.h:65,
                 from C:/MinGW/mingw32/i686-w64-mingw32/include/winsock2.h:23,
                 from C:/MinGW/mingw32/i686-w64-mingw32/include/WS2tcpip.h:17,
                 from C:\LIBS\include/ixwebsocket/IXNetSystem.h:10,
                 from lws.cpp:1:
C:/MinGW/mingw32/i686-w64-mingw32/include/crtdefs.h:47:13: note: previous declaration as 'typedef int ssize_t'
 typedef int ssize_t;
             ^~~~~~~</code></pre>
What does this mean? Am I using the right command? Any help is appreciated

**Comment by bsergean** [comment]
I don't think that mingw is a supported compiler. Can you use clang ?

Can you tell me the version of mingw you are using, your version of windows etc... ?

**Comment by bsergean** [comment]
Try to comment line 14

```
ixwebsocket$ nl IXSocket.h       
     1	/*
     2	 *  IXSocket.h
     3	 *  Author: Benjamin Sergeant
     4	 *  Copyright (c) 2017-2018 Machine Zone, Inc. All rights reserved.
     5	 */
      	
     6	#pragma once
      	
     7	#include <atomic>
     8	#include <functional>
     9	#include <memory>
    10	#include <mutex>
    11	#include <string>
      	
    12	#ifdef _WIN32
    13	#include <BaseTsd.h>
    14	typedef SSIZE_T ssize_t;
      	
    15	#undef EWOULDBLOCK
    16	#undef EAGAIN
    17	#undef EINPROGRESS
    18	#undef EBADF
    19	#undef EINVAL
```

**Comment by bsergean** [comment]
I am trying to build with mingw installed from chocolatey / https://chocolatey.org/

And I'm still getting some errors at this point -> https://github.com/machinezone/IXWebSocket/runs/2104720853?check_suite_focus=true

**Comment by bsergean** [comment]
mingw support is on its way.
