### ISSUE TITLE
Using on Windows with VS2019

### ISSUE THREAD

**Issue by xarthurx** [machinezone/IXWebSocket#276]
Install the library with `vcpkg`, and included the two headers as in the example file.

Compilation got these errors:
![image](https://user-images.githubusercontent.com/1921878/111083241-d08dfc80-850c-11eb-8021-42afda66f801.png)

Something I did wrong?

**Comment by xarthurx** [comment]
There are other errors, but mostly related to `WinSock2.h` and `ws2def.h` located in the `1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\` folder.

**Comment by bsergean** [comment]
Can you try to build as a static library ?

**Comment by xarthurx** [comment]
This problem is resolved in https://github.com/machinezone/IXWebSocket/issues/268.
