### ISSUE TITLE
Restarting socket with TLS

### ISSUE THREAD

**Issue by rossum2** [machinezone/IXWebSocket#277]
I'm trying to create a SMTP server based on this library. It is simple to create SMTP server class without TLS or obsolete SMTPS server based on the ix::Socket class. However to implement RFC-3207 (STARTTLS) one needs to start  an insecure TCP connection and upgrade it to TLS after issuing STARTTLS command. As far as I understand, TLS implementations in the derived classes of the ix::Socket start the secure connection in the connect method. Therefore one cannot start insecurely and reset the connection with TLS later on. 

As far as I understand an optional execution of the tls initialization would do the trick.

Finally, I can contribute the SMTP class to the library, if you are interested.

**Edit:** I first wrote that the initialization is in the constructor, but it is in connect method

**Comment by bsergean** [comment]
Hi @rossum2,

If you want to give it a try and submit a PR I'll look at it, if it's a simple change and it doesn't break anything we can merge it. For the SMTP class if it isn't too large we can include it too. Don't you need a MIME parser, which could bloat the code a bit ?

**Comment by bsergean** [comment]
Good luck with your effort, but SMTP is a bit out of scope.

**Comment by rossum2** [comment]
Hello @bsergean 

Sorry for my late reply. As far as the TLS restart goes it is more or less a simple change however I would recommend adding an abstract class say IXSocketTLS for classes IXSocketOpenSSL IXSocketMbetTLS etc. would inherit with a virtual method StartTLS that would initiate the TLS itself like in the attachment [IXSocketTLS.zip](https://github.com/machinezone/IXWebSocket/files/6190502/IXSocketTLS.zip). It does not break anything since the derived classes can take and optional parameter. 

For the SMTP server, it is not yet ready and will take me some time. However, for the library I imagined only the most ligtweight version where resolving the SMTP commands would be left entirely on the user. The only thing it would really provide is the state accepting commands or data. The MIME parser is not at all necessary. MIME is part of the "data" just as it is in http. There you don't care for it so I see no reason to care for it in this possible contribution. Anyway having SMTP as part of the library or not, is a matter of your choice and if you don't like it I don't want to trouble you with that anymore.

However I would still very much appreciate the possibility to implement it (even outside the library). Forking the library for one simple feature (the start of TLS later than during the connect) seems a bit awkward. Please take a look. If you still don't think it is a good idea to put it there, I'll not bother you with it anymore.

Thanks a lot for your time
