### ISSUE TITLE
Linker Errors in a New Project

### ISSUE THREAD

**Issue by kmcgurty** [machinezone/IXWebSocket#280]
Firstly, I am very new to C++. so I'm sure I'm doing something wrong. I'm on Windows 10, using VS 2019.

I clone the repo > go into the project properties inside VS > add the path to IXWebSocket-master to Include Directories > [run main.cpp](https://github.com/machinezone/IXWebSocket/blob/master/main.cpp) from the example, and I get these linker errors: https://i.imgur.com/ys68iHz.png

Next, I see in the [build instructions](https://machinezone.github.io/IXWebSocket/build/) that you can use vcpkg (which I have also never used before) to install the library. I follow the instructions on their [quick start](https://github.com/microsoft/vcpkg), run `.\vcpkg.exe install ixwebsocket`, then get [this message](https://i.imgur.com/LDwF3qY.png) (which seems like it was successful?). I remove the Include Directories from earlier, restart VS2019, try building main.cpp again, and I'm getting different [linker errors](https://i.imgur.com/ypz49ET.png). This time they seem to be related to SSL?

I've been trying to include this for many hours and have gotten too frustrated with no more ideas. If anyone is able to help, it would be greatly appreciated.

**Comment by bsergean** [comment]
This is one of the function problematic at linktime -> https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certfreecertificatecontext

Can you try to add Crypt32.lib to the link line ?

**Comment by kmcgurty** [comment]
@bsergean You are a legend! For anyone else having this issue, inside Visual Studio you must go into Project > Properties > Linker > Input > Additional Dependencies > edit > add Crypt32.lib

Thank you again!
