### ISSUE TITLE
Question or bug?

### ISSUE THREAD

**Issue by tostc** [machinezone/IXWebSocket#281]
Hi everyone,

I've a question or maybe I've found a bug. In the `HttpClient` class is a method called `del`, where I thought is the delete command of http. But this command sends as http method the verb `DEL` and I don't have found this verb inside the [RFC 2616](https://tools.ietf.org/html/rfc2616#section-5.1.1). Now my question is, is this a typo should it the verb `DELETE` or is this a propriotary extension?

**Comment by bsergean** [comment]
You're right, thanks for the report @tostc !
