### ISSUE TITLE
Bug in ixwebsocket.cpp ?

### ISSUE THREAD

**Issue by millionmonkeys** [machinezone/IXWebSocket#282]
ixwebsocket.cpp:252

`_onMessageCallback(
            ix::make_unique<WebSocketMessage>(WebSocketMessageType::Open,
                                              "",
                                              0,
                                              WebSocketErrorInfo(),
                                              WebSocketOpenInfo(status.uri, status.headers),
                                              WebSocketCloseInfo()));`

It crashes in my code with access violation in debug. Here we have reference to invalid string in WebSocketMessage object. After ix::make_unique ends, temporary string constructed in parametes is out of scope.

**Comment by millionmonkeys** [comment]
I'm reading about temporary objects lifetime and it seems like this code must be valid. But i have "Error reading characters of string" in VS debugger and av in debug here:

```
int main(int argc, char* argv[])
{
    ix::initNetSystem();
    ix::WebSocket ws;
    ws.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg) { std::cout << msg->str.c_str(); });
    ws.start();

    while (ws.getReadyState() != ix::ReadyState::Open);

    return 0;
}
```

VS 2019 x64/x86

**Comment by bsergean** [comment]
Hi @millionmonkeys

I think your problem is that you forgot to call `ws.setUrl("ws://localhost:8080");` // the library does not know where you want to connect to.

**Comment by millionmonkeys** [comment]
Can it  cause access violation? I think there is a dangling reference in WebSocketMessage, after a temporary string is out of scope inside make_unique.

Check it out.

```
#include <string>
#include <iostream>

struct test
{
	test(const std::string& s) : s(s) {}
	const std::string& s;
};
std::unique_ptr<test> construct(const char * s)
{
	return std::make_unique<test>(s);
}
void print(std::unique_ptr<test> t)
{
	std::cout << t->s.c_str();
}
int main(int argc, char* argv[])
{
	print(construct("TEST"));
	return 0; 
}
```
