### ISSUE TITLE
Websocket does not close if driven using one's own thread

### ISSUE THREAD

**Issue by desalema70** [machinezone/IXWebSocket#287]
I run the websocket as a client in my own thread (for reasons) and use "connect" and "run"; when I call "stop" from another thread the whole program hangs on joining that thread because websocket's internal loop (WebSocket::run()) never exits. I checked that "close" sets the correct ready state, and it does. Examining further I see that:

(1) The atomic "_stop" that would otherwise break the loop is not set when not running with websocket's own thread.
(2) The socket I opened is, by default, auto-reconnect; this seems to reset the closing/closed status and keeps it open.

I can circumvent the issue by setting "_stop" outside the joinable() test in "WebSocket::stop"; or if I explicitly disable auto-reconnect. Either solves my issue. However I find this unsettling: if I call "stop" on the websocket, I would expect it to stop regardless of how it was set up wrt auto-reconnect or threading.

**Comment by bsergean** [comment]
I don't see a simple way around this unfortunately. We need to join the thread when stopping, and that's only possible if that is done from the thread that called start / started the thread.

**Comment by desalema70** [comment]
Not sure I understand. All that's needed is to set the _stop flag outside the joinable test. If the thread is not joinable, no biggie, but it solves my problem.

The joinable / join sequence would still be performed when needed.

**Comment by bsergean** [comment]
I could be wrong. If you want to make a PR for this please go ahead, but I think it was done this way for a reason.
