### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by DamyHao** [machinezone/IXWebSocket#288]
Hi,
I have just installed the library with git clone and the steps of the building docs with the demo and test options 

mkdir build # make a build dir so that you can build out of tree.
cd build
 cmake -DUSE_TEST=1 -DBUILD_DEMO=ON ..
make -j
make install

The demo is not working because is not establishing connection with the wss://echo.websocket.org. I'm quite sure that the echo server is up.

All the compiled tests are passed correctly.
I am using Kali Linux 2021.1.

**Comment by DamyHao** [comment]
I have solved the problem by deactivating the ssl on the main.cpp  (demo). I have changed:
wss://echo.websocket.org -> ws://echo.websocket.org

I think this should be clarified on the readme.
Thanks!

**Comment by bsergean** [comment]
In the README and in the main.cpp example, the cmake invocation uses `-DUSE_TLS=1`, which is required to connect to a secure wss:// endpoint.

**Comment by bsergean** [comment]
We could add a warning though when this isn't passed in, if you want to make a PR for that it would be appreciated. Or we can change the error message.

**Comment by bsergean** [comment]
More info in 54db6ec
