### ISSUE TITLE
The define of EINVAL should be removed from the ixwebsocket/IXSocket.h file

### ISSUE THREAD

**Issue by Cheney-W** [machinezone/IXWebSocket#289]
I'm a member of Microsoft VCPKG team. In our internal test, `ixwebsocket` installation failed with following error:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\xloctime(870): error C2065: 'WSAEINVAL': undeclared identifier

After investigation, I found this issue due to the `ixwebsocket/IXSocket.h` file include following contents:
```
Line 23 #undef EINVAL
Line 30 #define EINVAL WSAEINVAL
```
Since [EINVAL](https://docs.microsoft.com/en-us/cpp/c-runtime-library/errno-constants?view=msvc-160#remarks) is an errno constant of the C runtime library, and I have looked up the whole `machinezone/IXWebSocket` repository, there was no call to EINVAL, so I think the above sentences can be removed from the `ixwebsocket/IXSocket.h` file.

**Comment by bsergean** [comment]
Trying to fix with 0f21a20

**Comment by Cheney-W** [comment]
Thanks for your reply! I have tested your commit and the error C2065 has disappeared. I could install this port successfully now.

**Comment by bsergean** [comment]
I just tagged a new version, if you care to make a new port PR in vcpkg for 11.2.6 that would be great, otherwise I'll do it at some point.

**Comment by bsergean** [comment]
https://github.com/machinezone/IXWebSocket/releases/tag/v11.2.6

**Comment by Cheney-W** [comment]
I have submitted a PR: https://github.com/microsoft/vcpkg/pull/17999 for 11.2.6. Much thanks for your efficient response.

**Comment by bsergean** [comment]
Thanks for updating the version on vcpkg !
