### ISSUE TITLE
Hello World does nothing

### ISSUE THREAD

**Issue by oakfr** [machinezone/IXWebSocket#290]
Hello,

I am trying the simple hello world example on my machine, but nothing happens when I run the program.

I am using an Ubuntu machine.

I compiled the code as follows: g++ --std=c++11 xwebsocket.cpp  -lcrypto -lssl -lpthread -lixwebsocket -ldeflate -lpthread -lz -lssl -lcrypto

The compilation succeeded with no warning.

What I am missing?

Thanks!

**Comment by oakfr** [comment]
I had installed the library incorrectly.

**Comment by bsergean** [comment]
Glad you found the problem yourself.
