### ISSUE TITLE
Unsafe locking pattern

### ISSUE THREAD

**Issue by picanumber** [machinezone/IXWebSocket#292]
There is faulty locking logic at least in a couple spots in `IXWebSockets.cpp`.  Take for example the following function:

```cpp
const std::string& WebSocket::getUrl() const
{
    std::lock_guard<std::mutex> lock(_configMutex);
    return _url;
}
```

There is no point in exclusive access when returning a reference:

1. The caller will get a seemingly `const` object but that object can be modified by a different thread, even worse be in an intermediate state while a different thread is modifying it.
2. If there is no chance a different is modifying the object, you don't need to protect it with a lock. In any case the lock only protects `_url` while inside the member function, but any protection goes away after the caller gets the reference. Bottom line is that the lock inside that function does little to nothing.

Since there are reader/writer methods it would make sense to use a `shared_mutex` + `unique_lock` to get less aggressive locking as a first step and then return values instead of references in the functions that retrieve internal state. 

Would a Pull request with such a refactoring be of interest?

**Comment by bsergean** [comment]
Thanks for the report. The lock was put in place to silence thread sanitizer / tsan.

If you want to improve that code I'd be happy to look at your PR, the constraint is to keep the code C++11 compatible. Returning values sounds good.
