### ISSUE TITLE
Cannot Send Messages to Multiple Connected Clients

### ISSUE THREAD

**Issue by sudo-michael** [machinezone/IXWebSocket#30]
I've been trying to send messages to multiple clients connected to a websocket server.
I followed the code used in `ws_broadcast_server.cpp` and `ws_chat.cpp` but ran into this issue. 

If I start the broadcast_server, then connect who chat clients, I am able to send and receive messages just fine with both clients. However, when I connect a third client, I can send message that reach the server, but will not be received by the first two clients.

Steps to reproduce:
```
./ws broadcast_server
./ws chat ws://127.0.0.1 bob 
./ws chat ws://127.0.0.1 joe
./ws chat ws::/127.0.0.1 bobjoe     //!< Connected error
```

Any help would be appreciated.

Thanks

**Comment by bsergean** [comment]
Interesting / maybe the 'clients' are being cached. I tried your flow and for me the third client cannot even reach the server ... odd.

I'll look into this when I get a chance.

Can you try to reproduce the problem with the builtin ws commands ?

```
ws broadcast_server # new terminal

ws chat ws://127.0.0.1:8080 john # new terminal
ws chat ws://127.0.0.1:8080 joe   # new terminal
...
ws chat ws://127.0.0.1:8080 bill # new terminal

**Comment by sudo-michael** [comment]
I reproduced the problem with the built-in ws commands.
![connection_error](https://user-images.githubusercontent.com/26592062/56250989-8ffa7f80-6066-11e9-8832-d7752ac15cfc.PNG)

**Comment by bsergean** [comment]
If you want to debug further you can try to add printf/log statements in SocketServer::run().

I'll have a look too, hopefully this is an easy thing.

**Comment by bsergean** [comment]
Hey I have a fix in progress, can you try to use this branch -> **bug/30_server_connection_problem**

**Comment by bsergean** [comment]
@sudo-michael please pull latest code and give it another try, I really think that the problem should be fixed.

I'm not super happy with the quality of the fix though, I will likely iterate on it to make it better.
