### ISSUE TITLE
Unresolved Symbols Normal VS Project(NOT CMAKE)

### ISSUE THREAD

**Issue by HideakiAtsuyo** [machinezone/IXWebSocket#301]
Hello, i'm here today to ask you to know if it's a problem from me or from IXWebSocket itself

C++14

https://i.imgur.com/ixXv05u.png

Thanks.

**Comment by bsergean** [comment]
Can you try to add *Crypt32* to the list of DLLs / link line ?

**Comment by HideakiAtsuyo** [comment]
> _Crypt32_

Thanks it's working :)
