### ISSUE TITLE
Failing to connect to server from mac

### ISSUE THREAD

**Issue by TuhinKumerN** [machinezone/IXWebSocket#302]
I have build IXWebSocket using openssl (1.1) in Mac

Terminal commands:
cmake .. -DUSE_TLS=1 -DUSE_OPEN_SSL=1
make -j
sudo make install

Than trying to establish web-socket connection with echo server using sample code provided. I added those in a cpp file and compiled it.

sample.cpp
https://github.com/machinezone/IXWebSocket/blob/master/README.md

Terminal commands:
clang++ --std=c++11 --stdlib=libc++ sample.cpp -lixwebsocket -lz -framework Security -framework Foundation
./a.out

That works fine. But than i trying to establish web-socket connection with my server just replacing the server request url in Mac. That failed. 

It showing following log -
# "Connection error: Expecting HTTP/1.1, got HTTP/1.0. Rejecting connection to wss://mypersonalserver.com/test, status: 503, HTTP Status line: HTTP/1.0 503 Service Unavailable"

 I tried using windows machine, that also works fine. But In Mac somehow it fails. I also tried from separate Mac machine.
 
 So any kind of help or clue would be really appreciated. I will provide any further info or details if you need.
 
 Thanks in advance.

**Comment by bsergean** [comment]
I think you have a certificate problem ; when using OpenSSL, you need to specify a ca cert

```
ix::SocketTLSOptions tlsOptions;
tlsOptions.caFile = "/etc/ssl/cert.pem";
webSocket.setTLSOptions(tlsOptions);
```

**Comment by bsergean** [comment]
This 503 error is suspicious though. Is your janus server available to the outside world ?

**Comment by TuhinKumerN** [comment]
I resolved the issue by using subprotocol and caFile = NONE

sample.cpp modified part:

// added
    webSocket.setUrl(url);
    webSocket.addSubProtocol("testserver-protocol");
    ix::SocketTLSOptions opt;
    opt.caFile = "NONE";
    webSocket.setTLSOptions(opt);
    
    
Thank you again.

**Comment by bsergean** [comment]
caFile = NONE is not safe, but it's up to you. It's safer to use a path to a good certificate files.

See https://daniel.haxx.se/blog/2018/11/07/get-the-ca-cert-for-curl/
