### ISSUE TITLE
Unresolved external symbol, IXWebSocketServer (VS Studio 2019)

### ISSUE THREAD

**Issue by tastydev** [machinezone/IXWebSocket#304]
Hey,

i try to implement the `IXWebSocketServer` inside my project but i get unresolved external symbol while compiling and i don´t know whats going wrong.

I included the cloned `IXWebSocket` repo to `additional include directories` as a dependency inside VS Studio.
The IDE is not complaining about anything while coding and autocomplete works too but as soon as i am compiling my binary i get unresolved external symbol errors.

![errors](https://i.gyazo.com/e8da6a808c378b160b22f434692f781c.png)

would appreciate any help

**Comment by bsergean** [comment]
What libraries are you linking to ?

You probably need something like that in your own project CMakefile:

```

if (WIN32)
  target_link_libraries(ixwebsocket wsock32 ws2_32 shlwapi)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)

  if (USE_TLS)
    target_link_libraries(ixwebsocket Crypt32)
  endif()
endif()
```

**Comment by tastydev** [comment]
Hi thank u for replying i am linking to the lib like this, normally it should work i guess:


![lib](https://i.gyazo.com/5060b82293d9a37a2c5cbdc8688e70f3.png)

![libpath](https://i.gyazo.com/fdddf71013386b645449dfa6a9efe76b.png)

![libfile](https://i.gyazo.com/0bfcbbccbf12ad60260113a9a496e486.png)

**Comment by bsergean** [comment]
You need to add the libraries from the cmake blob I sent previously.

**Comment by tastydev** [comment]
> You need to add the libraries from the cmake blob I sent previously.

thank u it´s working now!
