### ISSUE TITLE
functional file not found?

### ISSUE THREAD

**Issue by WindowLocationHashMaker** [machinezone/IXWebSocket#306]
Hi, I've recently installed this library but couldn't get it to work.

My code is the same one from the example in the github (https://github.com/machinezone/IXWebSocket/#hello-world)

Unfortunately, when I try to compile this code:

`clang++ --std=c++11 --stdlib=libc++ main.cpp -lixwebsocket -lz -framework Security -framework Foundation`

it returns an error.

In file included from main.cpp:17:
In file included from /usr/local/include/ixwebsocket/IXWebSocket.h:12:
/usr/local/include/ixwebsocket/IXProgressCallback.h:9:10: fatal error: 'functional' file not found
#include <functional>

I've searched the issues page but found nothing.
I've also googled, and it tells me to use -stdlib=libc++ as a compiler option. As you can clearly see, I've already done that.

Any help would be appreciated. Thanks in advance!

**Comment by WindowLocationHashMaker** [comment]
With some help from friends, I figured it out. The example for compiling this is in fact WRONG.

g++ -std=c++11 main.cpp -lixwebsocket -lz -pthread -lssl -lcrypto

The above is the command you should run. (you can also use clang++ instead of g++)

**Comment by Carlchk** [comment]
Hi, how do u resolve this issue? Are u using the WSL2 to build the example?
