### ISSUE TITLE
Websocket client files ...

### ISSUE THREAD

**Issue by vidcentum** [machinezone/IXWebSocket#309]
Hello: 

Let me first thank you for an excellent networking library. We use Websocket Client functionality in our projects. We would like to include only relevant files (for Websocket client) in the build. Could you please list the file to be included in the build only for Websocket client functionality?

https://github.com/machinezone/IXWebSocket/blob/master/docs/design.md
Can we exclude the following files for HTTP server, Client and Websocket Server? 

```
IXWebSocketServer.cpp 
IXWebSocketServer.h
IXWebSocketProxyServer.cpp
IXWebSocketProxyServer.h

IXHttpServer.cpp
IXHttpServer.h
```
Or is it a better option to keep the server files but do not create any server objects.

Thanks in advance. 

Best Regards
Maruthi

**Comment by bsergean** [comment]
If you exclude the file you are listing it should work ok.

Are you not using cmake ? We could add some config options to skip installing some header files (say with a new  -DCLIENT_ONLY setting)

**Comment by vidcentum** [comment]
Thank you @bsergean . I tried excluding those files and could test in our environment. As of now, the source files are dropped in the build. However, we have plans to integrate as CMake project. Yes, it is good to have -DCLIENT_ONLY (maybe -DWSCLIENT_ONLY, -DHTTPCLIENT_ONLY) to select the capabilities of the library.

Thank you.

Note: I am closing the issue.

Best Regards
Maruthi
