### ISSUE TITLE
fail to parse url("wss://ws.finnhub.io?token=c1i57rv48v6vit20lrc0")

### ISSUE THREAD

**Issue by hongxinGuo** [machinezone/IXWebSocket#310]
I direct included this lib in my project and build with TLS supported. And I received an error message "Unable to connect to ws.finnhub.io?token=c1i57rv48v6vit20lrc0 on port 443, error: 不知道这样的主机" when I try to connect.
I know it is may be some wrong options  when I compile this lib. But I could not find it.
My project at https://github.com/hongxinGuo/StockAnalysis, you can download the Test branch.
I use vs2019 windows10 and OpenSSL.

Thanks,

Guo

**Comment by hongxinGuo** [comment]
I defined IXWEBSOCKET_USE_TLS and IXWEBSOCKET_USE_OPEN_SSL in project property. Is it right?

**Comment by hongxinGuo** [comment]
I deleted the "?token=c1i57rv48v6vit20lrc0", the server connected, but reported "401 unauthorized".

Please tell me where tho add the string "token=c1i57rv48v6vit20lrc0"?

**Comment by hongxinGuo** [comment]
I deleted the "?token=c1i57rv48v6vit20lrc0", the server connected, but reported "401 unauthorized".

Please tell me where tho add the string "token=c1i57rv48v6vit20lrc0"?

**Comment by bsergean** [comment]
Aren't you missing a / separator between the hostname and the url path ?

wss://ws.finnhub.io/?token=c1i57rv48v6vit20lrc0

**Comment by hongxinGuo** [comment]
Thank you for your help. It worked.

The Finnhub example and Issue#285 don't add the '/'.  So I cound not find the right way. :)

You build a wonderful lib. Great work.

Guo
