### ISSUE TITLE
IXWebSocket PingTimeout setting

### ISSUE THREAD

**Issue by bigbang1976** [machinezone/IXWebSocket#311]
Hi,

In my setup I use a ping interval, but for some unknown reason every now and then (occasional once in 24 hrs) a ping is not send which will cause a drop of the connection the next time a ping is due. 
Would it be possible to have some flexibility on the ping timeout? I see a kDefaultPingTimeoutSecs mentioned in IXwebSocket.h but I don't think its implemented. 

Thanks.

**Comment by bigbang1976** [comment]
I might be wrong on this as I did not log the receiving of pong. Will get back to this when I am sure. I might just need a retry ping option ...

**Comment by bsergean** [comment]
Are you being disconnected maybe ?
Sometimes server load balancers get restarted (like once an hour).

**Comment by bigbang1976** [comment]
I found some unexplained connection starts, but will need to have some more logging around this. Will close for now.
