### ISSUE TITLE
found Memory leak 

### ISSUE THREAD

**Issue by hongxinGuo** [machinezone/IXWebSocket#312]
Is it ixWebSocket thread safe?

**Comment by hongxinGuo** [comment]
I found it. It is my fault.

**Comment by hongxinGuo** [comment]
The memory leak occured in the OpenSSLL lib.

**Comment by hongxinGuo** [comment]
the full stack is:
d:\cfiles\projects\winssl\openssl-1.1.1k\crypto\mem.c (233): StockAnalysis.exe!CRYPTO_zalloc()
    d:\cfiles\projects\winssl\openssl-1.1.1k\crypto\rand\drbg_ctr.c (438): StockAnalysis.exe!drbg_ctr_init() + 0x5 bytes
    d:\cfiles\projects\winssl\openssl-1.1.1k\crypto\rand\drbg_lib.c (137): StockAnalysis.exe!RAND_DRBG_set() + 0x8 bytes
    d:\cfiles\projects\winssl\openssl-1.1.1k\crypto\rand\drbg_lib.c (225): StockAnalysis.exe!rand_drbg_new() + 0x30 bytes
    d:\cfiles\projects\winssl\openssl-1.1.1k\crypto\rand\drbg_lib.c (873): StockAnalysis.exe!drbg_setup() + 0x11 bytes
    d:\cfiles\projects\winssl\openssl-1.1.1k\crypto\rand\drbg_lib.c (1141): StockAnalysis.exe!RAND_DRBG_get0_private()
    d:\cfiles\projects\winssl\openssl-1.1.1k\crypto\rand\rand_lib.c (930): StockAnalysis.exe!RAND_priv_bytes()
    d:\cfiles\projects\winssl\openssl-1.1.1k\ssl\ssl_lib.c (3073): StockAnalysis.exe!SSL_CTX_new() + 0x3C bytes
    C:\Users\hxguo\source\repos\StockAnalysis\ixwebsocket\IXSocketOpenSSL.cpp (213): StockAnalysis.exe!ix::SocketOpenSSL::openSSLCreateContext() + 0xE bytes
    C:\Users\hxguo\source\repos\StockAnalysis\ixwebsocket\IXSocketOpenSSL.cpp (728): StockAnalysis.exe!ix::SocketOpenSSL::connect() + 0x15 bytes
    C:\Users\hxguo\source\repos\StockAnalysis\ixwebsocket\IXWebSocketHandshake.cpp (101): StockAnalysis.exe!ix::WebSocketHandshake::clientHandshake() + 0x61 bytes
    C:\Users\hxguo\source\repos\StockAnalysis\ixwebsocket\IXWebSocketTransport.cpp (141): StockAnalysis.exe!ix::WebSocketTransport::connectToUrl() + 0x55 bytes
    C:\Users\hxguo\source\repos\StockAnalysis\ixwebsocket\IXWebSocket.cpp (218): StockAnalysis.exe!ix::WebSocket::connect() + 0x46 bytes
    C:\Users\hxguo\source\repos\StockAnalysis\ixwebsocket\IXWebSocket.cpp (326): StockAnalysis.exe!ix::WebSocket::checkConnection() + 0x2E bytes
    C:\Users\hxguo\source\repos\StockAnalysis\ixwebsocket\IXWebSocket.cpp (367): StockAnalysis.exe!ix::WebSocket::run()
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\type_traits (1610): StockAnalysis.exe!std::invoke<void (__cdecl ix::WebSocket::*)(void),ix::WebSocket *>()
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\thread (56): StockAnalysis.exe!std::thread::_Invoke<std::tuple<void (__cdecl ix::WebSocket::*)(void),ix::WebSocket *>,0,1>()

SSL_CTX* ctx = SSL_CTX_new(_ssl_method);   #213 in the file ixSocketOpenSSL.cpp.

**Comment by bsergean** [comment]
If you close the connection the leak should disappear.

**Comment by hongxinGuo** [comment]
Thank you. I solved this problem by Closing the connection before exit app.
I found another memory leak. It is OK if using the DLL version of OpenSSL lib. There are memory leak after changing to the static lib even if closing the connection before exit app.

**Comment by bsergean** [comment]
Good to know. If you have an idea of how to solve this let me know. Maybe there are some static variables that would need a static 'cleanup' function which could solve this. It pretty unlikely that I'll work on this thought.

I'll close this as it seems things are working for you now.
