### ISSUE TITLE
How to verify server public key on the client side

### ISSUE THREAD

**Issue by ludekvodicka** [machinezone/IXWebSocket#315]
Hi,

is there currently any way how can I verify server public key on the client-side, to protect against man-in-the middle attacks?

If I understand correctly, it's necessary to compare fingerprint of server public key on the client side against public key stored in the client.

What I mean is not to validate key against CA authority, but only validate used server key against public key stored in client.

I found some mentions about `mbedtls_ssl_conf_verify` and also found comment in your code (IXSocketMbedTLS.cpp line 153)

`` // FIXME: should we call mbedtls_ssl_conf_verify ?``

I believe this function should do the job. Here are some examples

mentions: 
- https://tls.mbed.org/discussions/feature-request/accepting-non-self-signed-server-certificates-for-unknown-cas
- https://github.com/ARMmbed/mbed-os-example-tls/blob/master/tls-client/HelloHttpsClient.cpp

Would it be possible to implement it?

Thanks

**Comment by bsergean** [comment]
I'm no security expert, but I believe you can set a public key already on the client side, and that one will be used.

```
  --cert-file TEXT:PATH(existing)
                              Path to the (PEM format) TLS cert file
  --key-file TEXT:PATH(existing)
                              Path to the (PEM format) TLS key file
```

ws tool has those options. There should be more doc here -> https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration

**Comment by bsergean** [comment]
@ludekvodicka I think you figured out a way or you used a different library, I don't think I'll have time to look into this anytime soon. If you want to make a PR for this please go ahead.

**Comment by ludekvodicka** [comment]
Hello, unfortunately, I didn't have time to check it yet. For now, I skipped this validation and leave it for later ;-).

I will keep you updated in case I will find any new info or if I will be able to create PR.
