### ISSUE TITLE
Endless loop in flushSendBuffer, if isReadyToWrite return result timeout

### ISSUE THREAD

**Issue by nejcgalof** [machinezone/IXWebSocket#316]
I have some situations where I have freeze with a particular client. Maybe is some problem with the connection or something like that. I'm currently investigating that, but anyway, IXWebSocket must detect that problem and resolve it without freezing.

I'm finding out, the `WebSocketTransport::flushSendBuffer()` never got out from loop if `_socket->isReadyToWrite(10)` return `PollResultType::Timeout`. 
It will be fine if after a few attempts with timeout results we go out from this loop. 
The connection is successful and this happens when I send large data (image big like 600x600).

I have an additional question if someone knows: why do I have this problem with timeout on flushing on specific windows PC on a specific network switch. Maybe anyone knows for some settings on the network side to prevent that problem with timeout?

**Comment by bsergean** [comment]
@nejcgalof I will close this, please re-open if you have more questions.
