### ISSUE TITLE
[Question] Has this been tested with OpenSSL 3.0.0?

### ISSUE THREAD

**Issue by rh101** [machinezone/IXWebSocket#319]
This section of code is throwing an error:

```
    bool SocketOpenSSL::openSSLCheckServerCert(SSL* ssl,
                                               const std::string& hostname,
                                               std::string& errMsg)
    {
        X509* server_cert = SSL_get_peer_certificate(ssl);
        if (server_cert == nullptr)
        {
            errMsg = "OpenSSL failed - peer didn't present a X509 certificate.";
            return false;
        }
```

The connection is successful, but `SSL_get_peer_certificate` is returning null.  In OpenSSL 3.0.0 `SSL_get_peer_certificate` is deprecated, and maps to `SSL_get1_peer_certificate`.

Has anyone tested OpenSSL 3.0.0 at all, or perhaps have any ideas on why it would be happening?

**Comment by bsergean** [comment]
I have not tested OpenSSL 3.0, last time I checked it was said to still be in alpha/beta release state.

1. But we could get a head-start. Did you try to use SSL_get1_peer_certificate and see what happen ?
2. What distribution are you using ? Is openssl-3.0 the default in some linux distributions ?

**Comment by rh101** [comment]
OpenSSL 3 has been released as of the 7th of September, and a few open source projects have upgraded to using it, which is where I ran into the problem, since I've been testing IXWebSocket with my project.

>     1. But we could get a head-start. Did you try to use SSL_get1_peer_certificate and see what happen ?

The binary distribution is the one being used in the open source project I'm using, so I'm in the process of changing it to the source distribution so I can trace into the OpenSSL code.

>     2\. What distribution are you using ? Is openssl-3.0 the default in some linux distributions ?

It may be a custom compiled version of it for Windows, iOS and Android, but regardless.  The platform I am testing IXWebSocket on is Windows (x64).

I'll let you know what I find.

**Comment by rh101** [comment]
It turns out that the 32bit x86 compiled version of IXWebSocket works with OpenSSL 3.0, but the x64 does not. Still looking into why this is so.

**Comment by rh101** [comment]
So, it turns out that IXWebSocket was linking with the incorrect version of the libraries, all because of this:

```
    if (NOT OPENSSL_FOUND)
      find_package(OpenSSL REQUIRED)
    endif()
```

It was finding both the custom OpenSSL and the system OpenSSL libraries, and adding both to the `OPENSSL_LIBRARIES` list.

It wasn't immediately obvious as to what needs to be done to link against custom OpenSSL libraries, but your comment in this issue was the answer: https://github.com/machinezone/IXWebSocket/issues/175#issuecomment-620231032

**Comment by bsergean** [comment]
Glad you figured it out. I didn't know that openssl-3 had been released.

Maybe we could improve the cmake stuff, if you know of a way to do that and you'd like to make a PR, please be my guess.

Maybe we could add a little note in the documentation, in the BUILD section ?

https://github.com/machinezone/IXWebSocket/blob/master/docs/build.md

**Comment by rh101** [comment]
> Maybe we could improve the cmake stuff, if you know of a way to do that and you'd like to make a PR, please be my guess.

I'll see what I can do.  

Other than that, IXWebSocket works fine with OpenSSL 3.0, or at least I haven't run into any issues as of yet. :)
