### ISSUE TITLE
compilation failure under MINGW64

### ISSUE THREAD

**Issue by ouwou** [machinezone/IXWebSocket#324]
IXWebSocket seems to work perfectly fine under [MSYS2/MINGW64](https://www.msys2.org/) but theres a couple changes i have to make to get it to compile

IXNetSystem.cpp fails due to `snprintf` and `uint16_t` not being found which i fixed by including `cstdio` and `cstdint`

IXNetSystem.h fails due to the [redefinition](https://github.com/machinezone/IXWebSocket/blob/3f1fc6906c64ee97a5b7e5b015ef29120af3481b/ixwebsocket/IXNetSystem.h#L37-L51) of `pollfd`

it seems the github actions set up uses version 8.1.0 of mingw-w64 off choco where the definition is necessary but newer versions seem to define pollfd so it fails to compile. not really sure what the best idea to go about this would be but if you wanna allow 8.1.0 to keep working perhaps you can check the GCC version macros, or i would imagine CMake provides a method to determining if pollfd exists so that it can be defined if it hasnt been already (maybe [this?](https://cmake.org/cmake/help/latest/module/CheckTypeSize.html#module:CheckTypeSize))

**Comment by bsergean** [comment]
I'd be happy to merge a PR if you want to contribute something, but I don't have access to a windows system, I just use github actions to make windows changes ... maybe that macro would work, otherwise we can do an ifdef WINDOWS + gcc-version < xxx.
