### ISSUE TITLE
port, host... in IXWebSocket.hare private with no getters

### ISSUE THREAD

**Issue by flagarde** [machinezone/IXWebSocket#326]
Hello,
Thanks for this nice library.

I try to access the host, port etc of WebSocketServer but there is no getters for them. Even child class cannot access to them because they are private on `IXSocketServer.h`

Would you accept some PR with these getters ?

**Comment by bsergean** [comment]
Thanks for the nice words.

Sure feel free to make a PR for this.

In SocketServer.h we have:

```
        // Member variables
        int _port;
        std::string _host;
        int _backlog;
        size_t _maxConnections;
        int _addressFamily;
```

We can expose those, they are what the constructor takes.
