### ISSUE TITLE
Is TLS supported on Windows?

### ISSUE THREAD

**Issue by natano** [machinezone/IXWebSocket#330]
I'm a bit confused whether TLS is supported on Windows with IXWebSocket.

At https://cpp.libhunt.com/ixwebsocket-alternatives I found this note:
> Following platforms are supported: * macOS * iOS * Linux * Android * Windows (no TLS) 

But if I understand the README and the docs correctly TLS is supported on all the platforms.

Is TLS supported on Windows?

**Comment by bsergean** [comment]
Yes TLS is supported on Windows.

**Comment by natano** [comment]
:+1: Thanks for clarifying!
