### ISSUE TITLE
building dynamic libraries on the Windows platform?

### ISSUE THREAD

**Issue by nahongyan** [machinezone/IXWebSocket#335]
I tried to set BUILD_SHARED_LIBS to open, but the compiled library does not export functions, what should I do? thank you.

**Comment by bsergean** [comment]
Are you on Windows ? I don't have access to a Windows machine unfortunately, so I can't help more.

**Comment by CryptoManiac** [comment]
I wonder why would anybody except maintainers will build shared libraries in 2021.

**Comment by bsergean** [comment]
Can you try @CryptoManiac fix @nahongyan ?
