### ISSUE TITLE
Per message compression: Illegal character CNTL=0xf

### ISSUE THREAD

**Issue by ahausladen** [machinezone/IXWebSocket#340]
If the per message compression is active the websocket client sends an illegal header to the server and the server (in my case Java Jetty) closes the connection with "HTTP/1.1 400 Illegal character CNTL=0xf".

This is caused by using an uint8_t for server_max_window_bits and client_max_window_bits in WebSocketPerMessageDeflateOptions.
A uint8_t is actually a "signed char" and so the byte value is interpreted as a character when building the headers.

Instead of
`  ... ; server_max_window_bits=15; client_max_window_bits=15`
the client sends
`  ...; server_max_window_bits=\xf; client-max_window_bits=\xf`

The ws tool can be used to show this. You can see the defect header with Wireshark.
`ws send ws://localhost:8081/mywebsocket IXWebSocket/ws/ws.cpp`

The ws tool's "receive" mode hides this bug because it uses strtol() to parse the presumed number and just returns zero because \xf is not a digit. The zero is then range-checked to the minimum window bits value (8).

**Comment by bsergean** [comment]
Great find, thanks !

Maybe I was trying to fix a warning, I can't remember why I changed those to a uint8_t.

**Comment by bsergean** [comment]
I think this is fixed now.
