### ISSUE TITLE
Does IXWebSocket run normally using a VirtualBox-ed Linux over Windows 10 ? 

### ISSUE THREAD

**Issue by hgfernan** [machinezone/IXWebSocket#343]
I've just started studying IXWebSocket and it looks very promising. For one thing it seems much simpler than other similar C++ libraries for websockets that I've seen in github.

I would like to  know if if there are satisfied users of IXWebSocket for an environment that is a Linux VM under Windows 10, before investing much time in this.

If there are many pitfalls to it, I will try to use a non virtualized Linux. 

Thanks in advance for any information.

**Comment by bsergean** [comment]
I honestly don't know about this environment, but it's been working quite well on Linux for a while.

The gotcha are with SSL as usual, but if you're on linux there should be default system certificates being used and everything should be ok. Btw on other platforms system certs are used too, things are difficult (but workable, just require some config) mostly on Android.

**Comment by bsergean** [comment]
If you want to make a poll I would look at the closed issues or PR and find users. I just merged a very nice PR for Windows.

**Comment by luastoned** [comment]
I've had no issues under WLS2.

**Comment by bsergean** [comment]
@hgfernan I hope this answer your question. I'm gonna close this as I think we have answered your question.

Thanks for chiming in @luastoned / I wonder if we should add the fact that the library works well under WSL2 somewhere in the docs. If you want to make a PR for that I'd gladly merge it.
