### ISSUE TITLE
When sending large messages, the buffer isnt flushed until there is another message sent

### ISSUE THREAD

**Issue by Dial0** [machinezone/IXWebSocket#345]
Your library is used within an application I use called Aseprite.
There's an extension i use with it to synchronize the image being drawn in blender.
So everytime a change is made to the image in aseprite a message is send to blender.

However as all the messages are large the send buffer is never flushed, which means the image shown in blender is always 1 step behind aseprite.

I tracked down the issue to somewhere in IXWebSocketTransport.cpp, line 888 or so.
There is a comment that says to wake a background thread to clear the buffer, however the "wakeUpFromPoll" just looks to return a bool, and there is a comment somewhere down the call stack that says "Wake up from poll/select by writing to the pipe which is watched by select".

However it would be better in this instance if more data did not need to be written to the pipe to get the buffer to flush.

Im not sure what your thoughts are on this? If its something that can be solved in your library or if its something that can be sold on aseprites side?

Happen to make modifications myself, but not really sure where to start, just looking for some guidance.

Cheers,

**Comment by ahausladen** [comment]
If it happens on Windows and not on Linux/MacOS then that's the same issue as #323 that was fixed yesterday.

**Comment by bsergean** [comment]
What @ahausladen said. I hope you're on Windows and the problem will go away in the latest version.

Do you have a link to the Aseprite project ? I'd like to mention it in the main README.

**Comment by bsergean** [comment]
If you can't update to the latest version, you can try to slow down 'sending' data a bit, by using the send callback. Look at the ws program, this [example](https://github.com/machinezone/IXWebSocket/blob/master/ws/ws.cpp#L2219).

How large are the payload when you send it ?
Also are you enabling zlib compression ? You could try to disable it and see if this helps, if your data is not compressible it might.

**Comment by bsergean** [comment]
@Dial0 I think you figured out what your problem was, so I'm gonna close this issue. Please re-open if you are still unhappy.

**Comment by Dial0** [comment]
Hi,

Sorry I havent had a chance to test the new changes, but looking at the discussion in the other issue it looks like exactly the issue, so I am pretty confident it will be resolved as I was on windows.

The project is https://github.com/aseprite/aseprite.

Ill try the changes when I have time and if there's still an issue ill re-open.

Thanks!
