### ISSUE TITLE
Is this IXWebSocket Client thread safe?

### ISSUE THREAD

**Issue by PasinduKollure** [machinezone/IXWebSocket#350]
The design [documentation](https://github.com/machinezone/IXWebSocket/blob/master/docs/design.md#polling-and-background-thread-work) states, "However concurrent writes need to be protected with mutex" but after looking at the [code](https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXWebSocket.cpp#L515), it looks like the `WebSocket::sendMessage()` uses a mutex before a message is sent. So, is it safe to execute the `WebSocket::sendMessage()` function from multiple threads?

**Comment by bsergean** [comment]
Yes it should be. Maybe the documentation should be updated.

**Comment by bsergean** [comment]
Can you try it and report if you had any issues ? It's been a while since I tried it.
