### ISSUE TITLE
LINK2019 errors

### ISSUE THREAD

**Issue by andrey231** [machinezone/IXWebSocket#351]
I am using Visual Studio 2022, and vcpkg to install the ixwebsocket library and  getting LINK2019 errors while building:

Error LNK2019 unresolved external symbol _mbedtls_x509_crt_verify_info в функции "public: virtual bool __cdecl ix::SocketMbedTLS::accept(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?accept@SocketMbedTLS@ix@@UEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z).	ConsoleApplication1	C:\Users\andre\source\repos\ConsoleApplication1\ConsoleApplication1\ixwebsocket.lib(IXSocketMbedTLS.cpp.obj)	1	

#include <ixwebsocket/IXNetSystem.h>
#include <ixwebsocket/IXWebSocket.h>
#include <ixwebsocket/IXUserAgent.h>

int main()
{
    
    ix::initNetSystem();
    ix::WebSocket webSocket;

    return 0;
}

ixwebsocket.lib
Crypt32.lib
wsock32.lib
ws2_32.lib
shlwapi.lib
%(AdditionalDependencies)

**Comment by bsergean** [comment]
Did you build mbedtls ? / You probably did it automatically by using vcpkg.

Can you try without vcpkg, just using the raw cmake.

If you can find the problem, can you make a PR for the CMakeLists.txt ?

One related location -> https://github.com/machinezone/IXWebSocket/blob/master/CMakeLists.txt#L227
Another one -> https://github.com/machinezone/IXWebSocket/blob/master/CMake/FindMbedTLS.cmake

Maybe the vcpkg needs to be updated.

**Comment by bsergean** [comment]
```
ixwebsocket.lib
Crypt32.lib
wsock32.lib
ws2_32.lib
shlwapi.lib
%(AdditionalDependencies)
```

Can you put mbedtls.lib in there ?
