### ISSUE TITLE
No neat way to customize callback

### ISSUE THREAD

**Issue by eddie0git** [machinezone/IXWebSocket#358]
First of all thank you Benjamin for sharing this code and for the support (in a much nicer way than other developers of good and widely used websocket code we all have looked at).
I have one difficulty in understanding how to use your code from a user point of view and in a neat way, i.e. without touching the base code, so pardon me if the question will seem a bit silly.

Assuming I need to use specific non thread-safe data object within my "core" callback, how is it assumed by code design that I have <const OnMessageCallback& callback> run on a different thread and at the same time I need to instantiate/kill (new/delete) my non thread safe object in that same thread?
I can I only think I could statically create my object within the callback but this is not ideal (and anyhow I cannot easily and directly delete).

Thank you in advance for the hint
Have a nice day

**Comment by bsergean** [comment]
Hi @eddie0git,

Can you try to protect your data with a mutex, before using it ?
Are you familiar with lambdas ? There are many example where you can 'capture' a variable and use it from the lambda / callback.

This file should have many examples: https://github.com/machinezone/IXWebSocket/blob/master/ws/ws.cpp

**Comment by bsergean** [comment]
Here is an example from ws.cpp.

We have 2 variables, and we can use them from the callback, using the [] block (not sure how this is called properly, let's call it a capture block).

```
        std::atomic<bool> success(true);
        std::condition_variable condition;

        webSocket.setOnMessageCallback([&condition, &success](const ix::WebSocketMessagePtr& msg) {
            if (msg->type == ix::WebSocketMessageType::Close)
            {
                spdlog::info("Report generated");
                condition.notify_one();
            }
            else if (msg->type == ix::WebSocketMessageType::Error)
            {
                std::stringstream ss;
                ss << "Connection error: " << msg->errorInfo.reason << std::endl;
                ss << "#retries: " << msg->errorInfo.retries << std::endl;
                ss << "Wait time(ms): " << msg->errorInfo.wait_time << std::endl;
                ss << "HTTP Status: " << msg->errorInfo.http_status << std::endl;
                spdlog::info(ss.str());

                success = false;
            }
        });
```

**Comment by eddie0git** [comment]
Thank you very much for the very quick reply!
As I always see mutex/futex and syncing mechanisms as potentially problematic (down to kernel level) I had in my mind the target of avoiding declaring anything in the main thread (as I can do anything I need in my callback).
My original thought was simply declaring anything right in the callback thread, something like:
`void ixCallback(const ix::WebSocketMessagePtr& msg) {
  static mytype myobj;     static bool init=false
  if (!init) <init myobj>
  ...
  if (msg->type == ix::WebSocketMessageType::Close || msg->type == ix::WebSocketMessageType::Error) <terminate myobj>
...
}
`
However this introduces some overhead and after all makes the code not that elegant.
I was thinking that in the future you might consider introducing two states such as WebSocketMessageType::INIT and WebSocketMessageType::TERMINATE and calling the callback two additional times once before running and once after close/error while winding down.

Have a nice day!
