### ISSUE TITLE
Are the test/ sample codes a good way to start learning IXWebsocket ?

### ISSUE THREAD

**Issue by hgfernan** [machinezone/IXWebSocket#359]
I am very new to IXWebSocket and also to the very idea of websockets, having worked only with them in Python.

Since I shall start working in a project that demands high performance, C++ is a far better language, and after a review of the websockets projects in github, it seems to me that IXWebSocket is the most interesting project.

I've already browsed the doc/ folder and it seems very interesting. However, sample code is also a great way to learn a software package.

Are the sample codes in the folder tests/ a good way to start learning IXWebSocket ? 

Today I dedicated sometime to make the tests compile in g++, and me some points that required some adaptations. Is someone already working in the test/ folder ? Should I submit the patches as a *pull request* when I finish them ?

**Comment by bsergean** [comment]
The unittest and the ws folder contains example code, there is also an example demo, very short and simple.

Are you planning on using this library for client, server, or both ?

**Comment by hgfernan** [comment]
At first, I intend to create websock clients, but eventually, I will run a local IXWebSocket server to understand the behavior of remote servers.

Since I am a beginner in this library and have some teaching experience, I would like to supplement the documentation with more detailed information. I can see that this is a library intended for experienced C++ programmers, but sometimes detailed information can help increase the audience since it can save time even for experienced programmers. 

With the same purpose, maybe I would like to suggest more error messages sometimes.

**Comment by bsergean** [comment]
That's a great point, if you can find a way to make the library more user-friendly to beginners that would be good.

One note though, it isn't true for the most part in server mode, but in client mode there is no logging at this point, since each OS/environment have their own logging, and I didn't want to start adding logging, and fully communicate status through explicit errors that have to be registered.
