### ISSUE TITLE
How to kick a client from the server

### ISSUE THREAD

**Issue by flagarde** [machinezone/IXWebSocket#361]
Hello,

I try to kick a client if it has the same id from the server. What i did 

Server :
```cpp
// The ConnectionState object contains information about the connection
std::shared_ptr<ConnectionState> connection = std::static_pointer_cast<ConnectionState>( connectionState );
if( msg->type == ix::WebSocketMessageType::Open )
{
  // Check if a client with the same name is already connected;
  connection->computeId( getHost() + ":" + std::to_string( getPort() ), Identifier::parse( msg->openInfo.headers["id"] ) );
  if( connection->isTerminated() )
  {
    logger()->error("One client with the name  is already connected !");
    webSocket.close( magic_enum::enum_integer( StatusCode::CLIENT_WITH_SAME_NAME_ALREADY_CONNECTED,"One client with the name  is already connected !");
    return;
  }
...
}
...
```

client
```cpp
 else if( msg->type == ix::WebSocketMessageType::Close )
 {
   if( msg->closeInfo.code == magic_enum::enum_integer(StatusCode::CLIENT_WITH_SAME_NAME_ALREADY_CONNECTED ) )
   {
     disableAutomaticReconnection();
    logger()->critical( fmt::format( fg( fmt::color::red ) | fmt::emphasis::bold, msg->closeInfo.reason ) );
    close();
   }
}
```

but the client is still connected and can send messages.

Do you know if it's possible to kick the client ?

**Comment by bsergean** [comment]
So the client callback 'close case' never get reached right, in your example ?

I can't remember honestly, but one thing I know is that some close() status might be reserved, the spec tells which status close can be user defined.

I would try to modify the ws example, or a unittest to test this behavior. This way if we fix it we can enforce in the unittest that this does never regress in the future.

Also if you can't get this to work, you could try to send a special message to the client (maybe you use json or some other marshalling library like msgpack), to tell it to stop, and have this handled as a normal message.

Also something I often try when I'm stuck, is to use a different language implementation to check that there isn't core bugs in this library (I've used node.js and python as they are simple to write test code like that).

**Comment by flagarde** [comment]
Hi, thank for your quick response.
The program enters in `else if( msg->type == ix::WebSocketMessageType::Close )` clause do the log but it seems the `close` function is never done.

Yes I tried first with a not defined number and found that the ` the spec tells which status close can be user defined.`. That why `StatusCode::CLIENT_WITH_SAME_NAME_ALREADY_CONNECTED` is defened as `4999` that seems ok if I understand correctly `https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.2`. The client is receiving the good number and good description but does not want to close

the unittest would be great. 
I have thought about doing what you propose (send a special message to the client), it would be a good solution but it would be more confusing. At least for me, I would expect all the close and open stuffs been made on the dedicated callback section.

**Comment by flagarde** [comment]
Hello,

I did some basic check it seems addind some delay after disableAutomaticReconnection() works. I tried this before but the delay was too short.. Don't know if this can be done direcly on the library side
