### ISSUE TITLE
[Windows] DNSLookup::resolveCancellable hangs for client

### ISSUE THREAD

**Issue by alive-omi** [machinezone/IXWebSocket#362]
Hi, guys.

I'm using ixWebSocket client for the first time, and it hangs inside the DNSLookup::resolveCancellable at
> auto t = std::make_shared<std::thread>(&DNSLookup::run, this, self, hostname, port);

when calling WebSocket::connect with 10s timeout from the MFC app main thread. From the multithreaded win32 dll, actually. Which is loaded by ::LoadLibrary, no magic here.

Some "magic" is created by the code inside of the DNSLookup::resolveCancellable
>         auto ptr = shared_from_this();
>         std::weak_ptr<DNSLookup> self(ptr);
> 
>         int port = _port;
>         std::string hostname(_hostname);
> 
>         // We make the background thread doing the work a shared pointer
>         // instead of a member variable, because it can keep running when
>         // this object goes out of scope, in case of cancellation
>         auto t = std::make_shared<std::thread>(&DNSLookup::run, this, self, hostname, port);
>         t->detach();

Although, I do understand the comment, I'm not sure the realization is completly OK in MSVC environment.
As a workaround I called DNSLookup::run directly instead of creating a thread, but
1) IDK the reason for the hang
2) the replacement code prolly isn't safe
3) IDK if I can trust the whole ixWebSocket when it hangs right from the start.
There's only one "std::make_shared < std::thread > " occurence in ixWebSocket source code happily.

I'm using MSVC 2017, toolset v141 with Win SDK 10.0.19041.0 specified in vcxproj project settings.

Tried to build my test dll with or without IXWEBSOCKET_USE_TLS / IXWEBSOCKET_USE_OPEN_SSL defs.
Tried different addresses (https/wss/localhost/192.168. etc).

I set the breakpoint right after the DNSLookup::run entry but it never works, so the hang is somewhere at the thread creation.

What are your suggestions? Thanks in advance.

**Comment by bsergean** [comment]
We can't call DNSLookup::run directly, that would defeat the purpose of having dns resolution async and cancellable.

Are you building with cmake + BUILD_SHARED_LIBRARY (forgot the exact name) ?

1. Can you try in your own code to create a thread the same way I do it, but have the thread do something simple (printf something maybe).
2. Can you make the background thread a member variable, to see if it makes any difference ?

**Comment by alive-omi** [comment]
As I've found some C++17 stuff in 'memory' source code
(C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\memory)
[https://www.imagebam.com/view/ME7U4M8](url)

I also tried to replace
> 	auto ptr = shared_from_this();
>     std::weak_ptr<DNSLookup> self(ptr);

with
> auto self = weak_from_this();

But it didn't help. My try&error approach is a bit blindfolded of course.

**Comment by bsergean** [comment]
Sorry I don't really know where to go from there. There is a C++ unittest that runs on Windows (with a few different different compilers, MSVC but also gcc), and the DNS calls are working.

What I would do is try to add a new CI configuration that build the library as a DLL, and execute the unittest.

The CMakeLists.txt has some Windows linking libs, but your app might not link at all if they were missing.

```
if (WIN32)
  target_link_libraries(ixwebsocket PRIVATE wsock32 ws2_32 shlwapi)
  target_compile_definitions(ixwebsocket PRIVATE _CRT_SECURE_NO_WARNINGS)

  if (USE_TLS)
    target_link_libraries(ixwebsocket PRIVATE Crypt32)
  endif()
endif()
```

Also fyi I develop on macOS, so it's hard for me to reproduce windows problem. There were many contributions to make this project works well on Windows, so this isn't a non-supported platform.

**Comment by bsergean** [comment]
Someone reported a crash in dns::lookup.

Maybe it's a recent regression. https://github.com/machinezone/IXWebSocket/issues/364
