### ISSUE TITLE
Is it possible to share the connection Id with the client that is connecting?

### ISSUE THREAD

**Issue by bigbang1976** [machinezone/IXWebSocket#363]
Hi,

Great lib and I use the client a lot. 
Right now I am looking to get to know the server as well for a localhost application. 
I would like to have the connectionId (the connectionstate->getId() from the server) available on the client side when connecting to the ws server.

I don't see how I can do this. Not sure how to send a msg to the individual client when connection is opened. Is it possible?  

If it's possible to add some header from the server side at msg->type ::Open, that would work as well. 

Thanks.

Frank

**Comment by bsergean** [comment]
Adding it manually as a Header is probably the most straighforward way. 

Maybe we could hard-code it for now, but that's a bit of a custom behavior that people who start relying on. What we need is some new callback 'OnConnect at the HTTP handshake level', that a user would have to implement, that would do this (let you add http headers to the handshake, or cancel connection for example).

I haven't had time to implement such things lately, so if you want to try to make a PR for that it would be great.
