### ISSUE TITLE
Install .dll when building shared libraries on windows

### ISSUE THREAD

**Issue by ardanew** [machinezone/IXWebSocket#368]
maybe ixwebsocket.dll needs to be placed in install_dir/bin

possible solution:
add
RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
to
install(TARGETS ixwebsocket

**Comment by bsergean** [comment]
I do my windows development by using Github Actions ... so if you'd like to submit a fix for that it would be good. It's unlikely I'll have the time to do so.

The same problem should happen with unix no ? Maybe we could add some basic install tests.
