### ISSUE TITLE
Is ix::WebSocket thread-safe?

### ISSUE THREAD

**Issue by 96chh** [machinezone/IXWebSocket#371]
```
ix::WebSocketServer server(port);

server.setOnClientMessageCallback([](std::shared_ptr<ix::ConnectionState> connectionState, ix::WebSocket & webSocket, const ix::WebSocketMessagePtr & msg) {
```
Can I use the webSocket in the callback function in another thread?

**Comment by bsergean** [comment]
You can give it a try, there are a bunch of protection for thread safety internally. The websocket might be deleted if you use it 'too late', or after the 'onClose' event has been sent.

To make sure you're doing things right, you can try to build with thread sanitizer.

**Comment by 96chh** [comment]
thx~
