### ISSUE TITLE
Detect absence of internet

### ISSUE THREAD

**Issue by andersfeyling14** [machinezone/IXWebSocket#372]
Hi,

I've read in the documentation for the client api that the OnMessageCallback can be used to detect connection errors. Can it also be used to detect when the internet connection is unexpectedly lost? I tried to run a basic client, and disabling my internet, but an error message was not triggered in the OnMessageCallback method. 

I might be looking at this all wrong though: does it make sense to look in the OnMessageCallback when a connection is disconnected unexpectedly?

**Comment by bsergean** [comment]
Unfortunately there's no easy way to do that from within the library. Other (platform, say iOS) APIs can tell you that but they are not portable, so most libraries like this one will not tell you this.
