### ISSUE TITLE
OpenSSL/BoringSSL related crash

### ISSUE THREAD

**Issue by blitz-research** [machinezone/IXWebSocket#375]
Hi,

I'm trying to use ixwebsocket in a c++ project on linux but I'm getting a SIGSEGV crash when connecting in IXSocketOpenSSL.cpp, line 750-ish:
```
            // SNI support
            SSL_set_tlsext_host_name(_ssl_connection, host.c_str());
```
As far as I can tell, all the relevant structures look OK, and I've tried it with a plain c-string for host param in case the std::string was corrupt but with no luck.

If I comment it out entirely, the program no longer crashes but it never connects.

Any ideas?

Bye!
Mark

**Comment by blitz-research** [comment]
It sounds like this might be due to the fact I'm linking with another library (webrtc) that uses an alternate ssl system (boringssl), and apparently boringssl and openssl don't get along well with each other when used in the same app!

Closing this for now...

**Comment by bsergean** [comment]
We could use some #ifndef BORING_SSL if that exists to discard some lines, but I don't think it's that simple.

I've never tested using ixwebsocket with boring ssl.

**Comment by bsergean** [comment]
That seems relevant https://github.com/apache/incubator-pagespeed-ngx/issues/992

**Comment by bsergean** [comment]
That too / https://stackoverflow.com/questions/66823207/ssl-set-tlsext-host-name-crashes

**Comment by blitz-research** [comment]
Ok, turns out this was really a problem in libwebrtc. It has option to build in openssl mode instead of boringssl but it doesn't quite work right as boringssl is stillcompiled and included in the lib (it's just not used (much)), which is causing linking problems.
Fixed by hacking libwebrtc's build scripts and everything's working together happily now.
