### ISSUE TITLE
Result of X509_NAME_get_index_by_NID misused

### ISSUE THREAD

**Issue by gsproston** [machinezone/IXWebSocket#376]
The IXSocketOpenSSL.cpp file checks the result of `X509_NAME_get_index_by_NID` to be successful if the returned value is not 0. However, it should be checking that the returned value is >= 0, as a value of '0' is valid, and '-1' and '-2' represent error states.

Issue is on line 342 of IXSocketOpenSSL.cpp.

Documentation for `X509_NAME_get_index_by_NID` here: https://man.openbsd.org/X509_NAME_get_index_by_NID.3

**Comment by bsergean** [comment]
Thanks for reporting @gsproston / this should be fixed now. This was only affecting old version of OpenSSL I believe.
