### ISSUE TITLE
how to send message from ixWebSocketServer?

### ISSUE THREAD

**Issue by Amerlef** [machinezone/IXWebSocket#377]
only i want to send message when triggered some events. 
so  i copied the code on https://machinezone.github.io/IXWebSocket/usage/#websocket-server-api  
but i do not known how to get the websocket. i just wanna to use "webSocket.send("something triggered", msg->binary);"

**Comment by bsergean** [comment]
Look at this example code -> https://github.com/machinezone/IXWebSocket/blob/master/ws/ws.cpp#L1172
