### ISSUE TITLE
unix domain socket support

### ISSUE THREAD

**Issue by Young-Flash** [machinezone/IXWebSocket#378]
Thanks for the great project. 
I want to know if websocket server support listenning on the unix domain socket (`AF_UNIX`).
btw, there seems to be no wrapped publish and subscribe methods that can be used directly ?

**Comment by bsergean** [comment]
This library supports Windows which does not really have AF_UNIX (only very recent Windows 10 has it I think), so it will be a bit hard to support this easily.
