### ISSUE TITLE
Shorter and more descriptive thread names

### ISSUE THREAD

**Issue by nejcgalof** [machinezone/IXWebSocket#379]
Because of the limitation in Linux of 16 bytes for thread names I suggest creating shorter names.
`setThreadName("WebSocketServer::" + connectionState->getId());`  In Linux we don't see the most important information -> ID
Maybe the solution is `setThreadName("WSS-" + connectionState->getId());`

`setThreadName("SocketServer::accept");` and  `setThreadName("SocketServer::GC");`, is not descriptive enough if we run multiple servers. Maybe we can add port information or something else for better knowing which server is still running when we diagnose the system. For example: `setThreadName("SS-" + _port)`;`

**Comment by bsergean** [comment]
Sure that looks like a good improvement. Can you contribute a PR ?

**Comment by bsergean** [comment]
Just made 2 changes to improve things here, in master. I used a slightly different naming convention, but it should be smaller. Tell me if helps @nejcgalof

**Comment by nejcgalof** [comment]
Sorry, somehow I dismiss your message. It looks perfect, and this will helps a lot. Thank you.

**Comment by bsergean** [comment]
Great. No worries missing those messages, I have them silenced so I check them every now and them. Good luck with your efforts and using this library !
