### ISSUE TITLE
CMake exported target depends on ZLIB::ZLIB which is not exported

### ISSUE THREAD

**Issue by dechamps** [machinezone/IXWebSocket#382]
See microsoft/vcpkg#24071. Basically, the exported `ixwebsocket::ixwebsocket` CMake target pulls in a dependency on `ZLIB::ZLIB`, but doesn't pull in the zlib package, resulting in downstream CMake projects failing with `Target "…" links to target "ZLIB::ZLIB" but the target was not found`.

**Comment by dechamps** [comment]
I was about to look into it but I see in microsoft/vcpkg#24078 that you're getting help from people way more knowledgeable about CMake than I am :)

**Comment by bsergean** [comment]
Yes but I'm not really sure what I'm doing, and they have helped in the beginning, but probably have other things to do.

If you want to help further please do / I've made a pull request but I won't be actively working on this.

**Comment by bsergean** [comment]
There was another problem, but it should be fixed now. I believe that when a new version will be pushed to vcpkg everything should be good, please tell me if your problem eventually go away @dechamps 

Merci et bon week-end/Vendredi ;)
