### ISSUE TITLE
Problems configuring TLS

### ISSUE THREAD

**Issue by Oudalally** [machinezone/IXWebSocket#386]
[](https://stackoverflow.com/posts/71895782/timeline)I'm attempting to build a simple client/server application in C++ using the IXWebsocket library, using the example code as an example from https://machinezone.github.io/IXWebSocket/usage/

The code works fine when using an unsecured connection but I can't get it working at all when using a secured connection.
The description on that page reads to me as though simply changing the ws:// url to a wss:// url is enough to instruct the application to secure the connection, but I'm clearly missing something.

I have used the generate_certs.sh script to create the various certs and keys, but I'm unsure which need to be applied in the client and server.

My aim is to simply secure the connection, I don't necessarily require trusted clients.

Is there any complete example of this application (the trivial example as shown on that page)? I've looked at the examples in the repo, but as the ws.cpp example includes a lot of different options for the tlsOptions, it's very confusing to read through.

I'm in no doubt that this is an error on my part, not the library. I'm also very keen to stick with this library as it's by far the cleanest approach to websockets I've seen, but I'm really stuck.

I presume that in the server, to use a self signed cert I will need to generate a server cert and key, self sign them, set the tls property in tlsOptions to true, and the CA file to none. If this is the case, do I need to specify a client cert and key in the client application?

The closest I've had to success is when I've had the server TLS options configured as follows:
```
ix::SocketTLSOptions tlsOptions;
tlsOptions.tls = true;
server.setTLSOptions(tlsOptions);
```

In this configuration, with the server listening on port 8443, connecting from the client to wss://localhost:8443 results in the server spitting out `SocketServer::run() tls accept failed: ` to the console, but there is no further detail in the messaging making if very hard to diagnose.

This same message is returned when I have tried to use any combination of certs and keys (I even resorted to using the client key and cert in the server just on the off chance it might give me something else to work with).

My apologies for posting a question on here - I've been on this for over 4 days now and I'm just lost.

To confirm - if I use a ws:// url, it is working absolutely fine. My client can send messages to the server, and get responses back.

Many thanks

**Comment by bsergean** [comment]
I'm sorry you're having such a hard time, ssl it quite complicated to setup. However there is a standalone shell script that create certificates on the fly, and set all the correct options.

Look at the test_ws.sh script under the ws folder.

I would try to build ws (the cli tool) first, replicate what the .sh script does in multiple commands, and then look at the ws.cpp source code.

Looks here https://github.com/machinezone/IXWebSocket/blob/master/ws/ws.cpp#L2519

And look at the member/fields on the tlsOptions struct.

**Comment by Oudalally** [comment]
Thanks for getting back to me.
I have used that script to generate the certs and keys, but what I'm confused about is that the script didn't generate any specific server keys that were self signed.
It did build self signed client keys, but reading up on TLS, I'm confused as to which keys I actually need.

I was told that I'll need a self private key on the server, a self signed cert on the server, and a self signed CA file on the server, but nothing on the client as the the most basic way to get it working - does that make any sense?

I'll have a look at the script again, but I've been using OpenSSL to generate keys and certs the past 3 days, and none of them have worked. Really, I think I am just confused as to which keys I need to populate in the server, and which in the client so I can get a self signed cert working while I'm developing the application.

Once I'm deploying it, we'll be ordering a key and cert from a CA, so that should be easy enough to work with. I'll know which ones need to be plugged in to the server, which need to be trusted on the client, but with self signed certs, I just can't find any combination of certs and keys which will get the TLS to connect.

**Comment by Oudalally** [comment]
>

**Comment by bsergean** [comment]
Great / I added a link to this comment in the top level readme of ixwebsocket. I hope it will help make this less confusing.
