### ISSUE TITLE
vcpkg .in cmakefiles 

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#387]
The cmake file is incorrect, apparently there are some bad characters.

```
@PACKAGE_INIT@

include(CMakeFindDependencyMacro)

if（@USE_ZLIB@）
  find_dependency(ZLIB)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/ixwebsocket-targets.cmake")
```

@Cheney-W / what character set should I use ?

**Comment by Cheney-W** [comment]
Thanks for your reply!
`if（@USE_ZLIB@）`
Here are the parentheses of two Chinese characters, which only need to be changed into English.
`if(@USE_ZLIB@)`

**Comment by Cheney-W** [comment]
This is my mistake. I'm sorry.

**Comment by bsergean** [comment]
Oh so it's the parenthesis that are wrong ?

**Comment by bsergean** [comment]
Here is the PR -> https://github.com/machinezone/IXWebSocket/pull/390/files

And so it was just for the if (@USE_ZLIB@) right ?

**Comment by Cheney-W** [comment]
Yes, just the parenthesis are wrong.
Thanks for your PR.
Yes.

**Comment by bsergean** [comment]
Great, I just made a new tag/release with that fix -> https://github.com/machinezone/IXWebSocket/releases/tag/v11.4.2
