### ISSUE TITLE
Make install not working on termux

### ISSUE THREAD

**Issue by Graphite2213** [machinezone/IXWebSocket#403]
I tried using ixws on termux by following the install steps in the docs, and it all went smoothly until the `make install` step which resulted in an error saying:

```
[100%] Built target ixwebsocket
Install the project...
-- Install configuration: "RelWithDebInfo"
CMake Error at cmake_install.cmake:46 (file):
  file cannot create directory: /usr/local/lib.  Maybe need administrative
  privileges.
```
This error persisted even if i used `sudo`. What should i do next? 

If what `make install` does is simple enough like just moving around a few files i could probably do that manually but i have no idea where the files would go (except for the `ixwebsocket` folder which would go into `clang/14.0.6/include`)

**Comment by flagarde** [comment]
Hi, seems you need to be admin to install on /usr/local/lib. Two solutions : 
1) You are sudoer -> Do sudo make install
2) Change the install path passing CMAKE_INSTALL_PREFIX to cmake
