### ISSUE TITLE
can not connect succes

### ISSUE THREAD

**Issue by liuxiaofeng8888** [machinezone/IXWebSocket#407]
hi  i try connect my company server Ip，but it is error.
this my log:
ixwebsocket/11.4.3 android ssl/mbedtls 2.16.6
Connecting to xxx..
> Connection error: Unable to connect to xxx, error: no error

i use mbedtls as ssl.
LOCAL_MODULE := demo
LOCAL_C_INCLUDES := \
    $(MY_INC_ROOT) \
    $(base-includes) \
    $(YUNOS_ROOT)/third_party/mbedtls \
    $(YUNOS_ROOT)/third_party/mbedtls/include \
    $(YUNOS_ROOT)/third_party/mbedtls/include/mbedtls
how to solve the problem?

**Comment by bsergean** [comment]
1. Can you reproduce with ws the command line tool, on mac or linux ?
2. If this is on Android, are you bundling a ca file with your app / https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration
3. Is this with a wss connection ?

**Comment by liuxiaofeng8888** [comment]
>  it compiled on mac and run on android devices. this is wss connection.


banma-1629@banma-1629deMacBook-Pro Downloads % adb push mydemos/* /data/local/tmp
[   ?] /data/local/tmp/libmbedtls.so
banma-1629@banma-1629deMacBook-Pro Downloads % adb shell
sailfish:/ $ cd /data/local/tmp
sailfish:/data/local/tmp $ 
sailfish:/data/local/tmp $ ./demo                                              
CANNOT LINK EXECUTABLE "./demo": library "libmbedtls.so" not found
xport LD_LIBRARY_PATH=/data/local/tmp:$LD_LIBRARY_PATH                        <
sailfish:/data/local/tmp $ ./demo                                              
ixwebsocket/11.4.3 android ssl/mbedtls 2.16.6
Connecting to wss://speech-vgw-qa.ebanma.com:8443...
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Connection error: Unable to connect to speech-vgw-qa.ebanma.com on port 8443, error: Cancelled
> 
> 
> 
> 
> Connection error: Unable to connect to speech-vgw-qa.ebanma.com on port 8443, error: Cancelled
> Connection error: Unable to connect to speech-vgw-qa.ebanma.com on port 8443, error: Cancelled
> Connection error: Unable to connect to speech-vgw-qa.ebanma.com on port 8443, error: Cancelled
> Connection error: Unable to connect to speech-vgw-qa.ebanma.com on port 8443, error: Cancelled
> Connection error: Unable to connect to speech-vgw-qa.ebanma.com on port 8443, error: Cancelled



and my code is only change the url
/*
 *  main.cpp
 *  Author: Benjamin Sergeant
 *  Copyright (c) 2020 Machine Zone, Inc. All rights reserved.
 *
 *  Super simple standalone example. See ws folder, unittest and doc/usage.md for more.
 *
 *  On macOS
 *  $ mkdir -p build ; cd build ; cmake -DUSE_TLS=1 .. ; make -j ; make install
 *  $ clang++ --std=c++14 --stdlib=libc++ main.cpp -lixwebsocket -lz -framework Security -framework Foundation
 *  $ ./a.out
 *
 *  Or use cmake -DBUILD_DEMO=ON option for other platform
 */

#include "ixwebsocket/IXNetSystem.h"
#include "ixwebsocket/IXWebSocket.h"
#include "ixwebsocket/IXUserAgent.h"
#include <iostream>

int main()
{
    // Required on Windows
    ix::initNetSystem();

    // Our websocket object
    ix::WebSocket webSocket;

    // Connect to a server with encryption
    // See https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration
    //std::string url("wss://echo.websocket.org");
     std::string url("wss://speech-vgw-qa.ebanma.com:8443");
    webSocket.setUrl(url);


    std::cout << ix::userAgent() << std::endl;
    std::cout << "Connecting to " << url << "..." << std::endl;

    // Setup a callback to be fired (in a background thread, watch out for race conditions !)
    // when a message or an event (open, close, error) is received
    webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
        {
            if (msg->type == ix::WebSocketMessageType::Message)
            {
                std::cout << "received message: " << msg->str << std::endl;
                std::cout << "> " << std::flush;
            }
            else if (msg->type == ix::WebSocketMessageType::Open)
            {
                std::cout << "Connection established" << std::endl;
                std::cout << "> " << std::flush;
            }
            else if (msg->type == ix::WebSocketMessageType::Error)
            {
                // Maybe SSL is not configured properly
                std::cout << "Connection error: " << msg->errorInfo.reason << std::endl;
                std::cout << "> " << std::flush;
            }
        }
    );

    // Now that our callback is setup, we can start our background thread and receive messages
    webSocket.start();

    // Send a message to the server (default to TEXT mode)
    webSocket.send("hello world");

    // Display a prompt
    std::cout << "> " << std::flush;

    std::string text;
    // Read text from the console and send messages in text mode.
    // Exit with Ctrl-D on Unix or Ctrl-Z on Windows.
    while (std::getline(std::cin, text))
    {
        webSocket.send(text);
        std::cout << "> " << std::flush;
    }

    return 0;
}

**Comment by liuxiaofeng8888** [comment]
Run it with ./demo on mac. it work well,but compile arm version push to android devices,it does not work as the problem.

**Comment by bsergean** [comment]
Copy the firefox cacert.pm on your android device. https://curl.se/docs/caextract.html

Then set the tlsOptions.caFile to point to it.

https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration
