### ISSUE TITLE
Server examples

### ISSUE THREAD

**Issue by Igi54** [machinezone/IXWebSocket#408]
Hello, thank you very much for this library. It is very intuitive. However I have not found (except one) examples how to implement servers. In the server example is written "// All connected clients are available in an std::set. See the broadcast cpp example." I cannot find the broadcast example. I need to implement ws server which can send a "private" message to a client. I mean I have several client. Each client sends ID in its payload (I use my own subprotocol). The server should be able send a message to a particular ID. Not broadcast. Is it possible with this library? Thank you in advance.

**Comment by bsergean** [comment]
Yes it should be able to do that with the library. Check the ws subfolder it should have such examples

Broacast example:
https://github.com/machinezone/IXWebSocket/blob/master/ws/ws.cpp#L2791

https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXWebSocketServer.cpp#L174

That one is a bit more complex, maybe you can use it as an inspiration for your need.
https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXWebSocketProxyServer.cpp

**Comment by Igi54** [comment]
Thank you for your reply. Even I do not know how to do it. Probably I did not describe my problem correctly. I need in whatever time send a message to a client. It means not to a client which is sending me (to a server) a message right now but to someone else. So I need an access to the collection of the clients. How can I get a list or particular object of a client?

**Comment by bsergean** [comment]
You should probably use an std::map to associate IDs with websocket clients.

Each time a new client connect, record its id in the map as the key, and its websocket object as the value.
