### ISSUE TITLE
 CPU utility is  too high

### ISSUE THREAD

**Issue by liuxiaofeng8888** [machinezone/IXWebSocket#411]
400%cpu 121%user  10%nice  81%sys 183%idle   0%iow   4%irq   2%sirq   0%host
  PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS                                                                                                                                                                                          
 4680 shell        20   0  11M 2.0M 1.5M S  100   0.0   7:02.65 demo
32676 u0_a189      20   0 1.6G 170M  59M S 83.3   4.5  23:32.87 cn.alios.voiceservice
 5177 u0_a182      16  -4 2.1G 149M  73M S  8.6   3.9   0:08.36 com.xunmeng.pinduoduo
 1629 u0_a90       20   0 4.8G  68M  43M S  3.6   1.7   2:30.81 com.ustwo.lwp
 4748 shell        20   0  35M 3.0M 1.7M R  3.0   0.0   0:11.06 top
  506 system       -2  -8 288M  12M 8.1M S  2.0   0.3  10:31.96 surfaceflinger
 5101 root         20   0    0    0    0 S  1.3   0.0   0:00.62 [kworker/u8:5]
  929 system       18  -2 8.0G 322M 247M S  1.3   8.5   5:21.26 system_server
  525 root         RT   0    0    0    0 D  1.3   0.0   2:33.75 [mdss_fb0]
26043 root         20   0    0    0    0 S  1.0   0.0   0:05.91 [kworker/0:5]
  672 system       RT   0 2.0G 3.9M 2.5M S  1.0   0.1   0:43.33 android.hardware.sensors@1.0-service
25136 root         20   0    0    0    0 S  0.6   0.0   0:43.88 [kworker/u8:8]
  770 shell        20   0 148M 4.0M 2.3M S  0.6   0.1   0:36.47 adbd --root_seclabel=u:r:su:s0
  508 system       -3  -8 151M 4.2M 3.2M S  0.6   0.1   2:43.89 android.hardware.graphics.composer@2.1-service
  354 root         RT   0    0    0    0 S  0.6   0.0   0:29.94 [nanohub]
  276 root         RT   0    0    0    0 S  0.6   0.0   0:11.26 [spi6]
 4638 root         20   0    0    0    0 S  0.3   0.0   0:02.91 [kworker/0:1]
 4327 root         20   0    0    0    0 S  0.3   0.0   0:03.61 [kworker/0:0]
 2013 u0_a182      20   0 1.8G  71M  45M S  0.3   1.8   0:03.88 com.xunmeng.pinduoduo:titan
 1872 root         20   0    0    0    0 S  0.3   0.0   0:12.90 [kworker/u8:2]
26054 shell        20   0  33M 1.9M 1.3M S  0.3   0.0   0:02.75 logcat -v long -v epoch
 2896 u0_a176      20   0 6.7G 132M  68M S  0.3   3.5   0:41.87 com.tencent.mm
 1990 root         18  -2    0    0    0 S  0.3   0.0   0:14.61 [VosMCThread]
 1784 radio        20   0 5.3G  68M  34M S  0.3   1.8   0:09.42 com.android.phone

hi. i test the demo.the  CPU utility is  too high,what can do for reducing it?

**Comment by bsergean** [comment]
It looks like you keep connecting and disconnecting. Can you put printf / debugging logs to see what's going on ?
Do you have a CPU profiler on Android ?

**Comment by liuxiaofeng8888** [comment]
> 
This is my code,i just changed the server ip. And sleep(200) instead of while loop.
/*
 *  main.cpp
 *  Author: Benjamin Sergeant
 *  Copyright (c) 2020 Machine Zone, Inc. All rights reserved.
 *
 *  Super simple standalone example. See ws folder, unittest and doc/usage.md for more.
 *
 *  On macOS
 *  $ mkdir -p build ; cd build ; cmake -DUSE_TLS=1 .. ; make -j ; make install
 *  $ clang++ --std=c++14 --stdlib=libc++ main.cpp -lixwebsocket -lz -framework Security -framework Foundation
 *  $ ./a.out
 *
 *  Or use cmake -DBUILD_DEMO=ON option for other platform
 */

#include <ixwebsocket/IXNetSystem.h>
#include <ixwebsocket/IXWebSocket.h>
#include <ixwebsocket/IXUserAgent.h>
#include <ixwebsocket/IXWebSocketSendData.h>

#include <iostream>
#include <string>

int main()
{
    // Required on Windows
    ix::initNetSystem();

    // Our websocket object
    ix::WebSocket webSocket;

    // Connect to a server with encryption
    // See https://machinezone.github.io/IXWebSocket/usage/#tls-support-and-configuration
    std::string url("wss://speech-vgw-qa.ebanma.com:8443"); //wss://echo.websocket.org");
    webSocket.setUrl(url);

    std::cout << ix::userAgent() << std::endl;
    std::cout << "Connecting to " << url << "..." << std::endl;

    // Setup a callback to be fired (in a background thread, watch out for race conditions !)
    // when a message or an event (open, close, error) is received
    webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
        {
            if (msg->type == ix::WebSocketMessageType::Message)
            {
                std::cout << "received message: " << msg->str << std::endl;
                std::cout << "> " << std::flush;
            }
            else if (msg->type == ix::WebSocketMessageType::Open)
            {
                std::cout << "Connection established111" << std::endl;
                std::cout << "> " << std::flush;
            }
            else if (msg->type == ix::WebSocketMessageType::Error)
            {
                // Maybe SSL is not configured properly
                std::cout << "Connection error: " << msg->errorInfo.reason << std::endl;
                std::cout << "> " << std::flush;
            }
        }
    );

    // Now that our callback is setup, we can start our background thread and receive messages
    webSocket.start();

    // Send a message to the server (default to TEXT mode)
    //webSocket.send("hello world");
     //webSocket.sendUtf8Text(IXWebSocketSendData(text, strlen("hello world")));

    // Display a prompt
    std::cout << "> " << std::flush;

    std::string text;
    // Read text from the console and send messages in text mode.
    // Exit with Ctrl-D on Unix or Ctrl-Z on Windows.
    // while (true)
    // {
    //     webSocket.send(text);
    //      //webSocket.sendUtf8Text(IXWebSocketSendData(text, strlen(text)));
    //     std::cout << "> " << std::flush;
    //     sleep(2);
    // }

          sleep(200);

    return 0;
}

**Comment by liuxiaofeng8888** [comment]
> It looks like you keep connecting and disconnecting. Can you put printf / debugging logs to see what's going on ? Do you have a CPU profiler on Android ?

if i used / while (true)
// {
//     webSocket.send(text);
//      //webSocket.sendUtf8Text(IXWebSocketSendData(text, strlen(text)));
//     std::cout << "> " << std::flush;
//     sleep(2);
// }
it work well,CPU utility is not high

**Comment by liuxiaofeng8888** [comment]
> It looks like you keep connecting and disconnecting. Can you put printf / debugging logs to see what's going on ? Do you have a CPU profiler on Android ?

By the way,how to open the debug switch? i only get the below log:
ixwebsocket/11.4.3 android ssl/mbedtls 2.16.6
Connecting to wss://speech-vgw-qa.ebanma.com:8443...
> Connection established111
>

**Comment by bsergean** [comment]
There is no logging in the library, if this is what you call the debug switch. Just callbacks with info that you can implement.

**Comment by Pandi1981** [comment]
Hi Mate,
I am also facing same issue %CPU is going very high almost used all the cpu....Please let me know what changes happened in the code level....
Please share me your code change ....
