### ISSUE TITLE
Cannot create socket due to too many open files

### ISSUE THREAD

**Issue by NukoOoOoOoO** [machinezone/IXWebSocket#412]
As the image goes.![img](https://i.imgur.com/IMyRV2D.png)

The last time I check connection count is around 352, I am not sure what the maximum connection will be if that matters

**Comment by bsergean** [comment]
Which platform are you using ?
There is a settings to bump this at the OS level if you are hitting this limitation (check the ulimit man page). It could also be that your code is leaking connections.

**Comment by NukoOoOoOoO** [comment]
> Which platform are you using ?

Arch linux 5.18.16-arch1-1

Here is the settings
```
~ ❯ ulimit -Hn
524288
~ ❯ ulimit -Sn
1024
```

>  It could also be that your code is leaking connections.

I'm not sure what causes leakage, if storing connections to a container but not removing when a client disconnect from the server, then I think I know why. 
Also, I found that Close event won't get fired if a client disconnect from the server for some reasons (I can't really reproduce it on develop environment because it happens rarely)

**Comment by bsergean** [comment]
There is a ping/pong mechanism you could try on the client side to keep the connection opened, if your client supports it. It's part of the websocket spec.

**Comment by NukoOoOoOoO** [comment]
The problem seems to be fixed after using ping/pong mechanism, will reopen the issue if it still happens
