### ISSUE TITLE
TLS full example

### ISSUE THREAD

**Issue by Igi54** [machinezone/IXWebSocket#413]
Hello, would it be possible to add an example how to use crypted mode? I do not need "official" SSL certificate. I just need crypted communication between a client and a server. Client does not use a web browser, all is directly in my app. I found almost the same question on the stackoverlow https://stackoverflow.com/questions/71895782/how-to-enabled-tls-in-ixwebsocket-for-simple-client-server-application
Thank you in advance.

**Comment by bsergean** [comment]
Look at the ws subfolder for example code, there's also a test_ws.sh script in there with some steps, if you want to run your own server.

What is your platform ?
There are limitation on macOS if you need to supply your own cert, but it should work well with other platforms (using OpenSSL or MbedTLS).
