### ISSUE TITLE
arm cross compilation - not able to find <stdlib.h> or <math.h> with $make -j

### ISSUE THREAD

**Issue by mgsanava** [machinezone/IXWebSocket#419]
I was successful to complete build process and test a sample program on an Ubuntu 18.04 machine with the following commands:
```
cmake -DUSE_TLS=1 -DUSE_OPENSSL=1 .. 
make -j
make install 
```
Later, I tried to cross compile the same for an arm development board ([imxul processor](https://www.phytec.in/product/system-on-modules/phycore-imx-6ul-download/)) using a
[Toolchain](https://www.phytec.in/software/board-support-packages/yocto-buildsystem/bsp-seite/?bsp=BSP-Yocto-i.MX6UL-PD19.1.0) that was provided by vendor (Phytec).
I've imported the environment in a terminal and then issued the commands above.
 _cmake_ command was successful.
 _make -j_ command has thrown tens of errors as shown below although _stdlib.h_ is present in the same path as _cstdlib_
 It could find the file _cstdlib_ but failed to find _stdlib.h_ which is in the same path.

I'm really not sure if this a problem with toolchain but posting here as I couldn't find help elsewhere. And, sorry for the lenghty post, you may ignore most of pasted error log. Most of these error messages are repeated.
Please let me know if I need to supply more information.

> cstdlib:75:15: fatal error: stdlib.h: No such file or directory
>  #include_next <stdlib.h>
>                ^~~~~~~~~~
> compilation terminated.

In my terminal _echo $PATH_ for arm is:

> /opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/usr/bin/qt5:/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/usr/bin:/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/usr/sbin:/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/bin:/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/sbin:/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/usr/bin/../x86_64-phytecsdk-linux/bin:/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/usr/bin/arm-phytec-linux-gnueabi:/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/x86_64-phytecsdk-linux/usr/bin/arm-phytec-linux-musl:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**_Complete error message for "make all":_**

**_gmk@dell-G15-5511:~/phytec_project/ocpp_test/github_machinezone_arm/build$_** make all
[  2%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXBench.cpp.o
In file included from /opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/ext/string_conversions.h:41:0,
                 from /opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/bits/basic_string.h:6349,
                 from /opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/string:52,
                 from /home/gmk/phytec_project/ocpp_test/github_machinezone_arm/ixwebsocket/IXBench.h:10,
                 from /home/gmk/phytec_project/ocpp_test/github_machinezone_arm/ixwebsocket/IXBench.cpp:7:
/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
CMakeFiles/ixwebsocket.dir/build.make:62: recipe for target 'CMakeFiles/ixwebsocket.dir/ixwebsocket/IXBench.cpp.o' failed
make[2]: *** [CMakeFiles/ixwebsocket.dir/ixwebsocket/IXBench.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ixwebsocket.dir/all' failed
make[1]: *** [CMakeFiles/ixwebsocket.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**_Complete error message for "make -j":_**

**gmk@dell-G15-5511:~/phytec_project/ocpp_test/github_machinezone_arm/build$** make -j
[  7%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXConnectionState.cpp.o
[  7%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXCancellationRequest.cpp.o
[  7%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXBench.cpp.o
[ 10%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.o
[ 13%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXExponentialBackoff.cpp.o
[ 15%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGetFreePort.cpp.o
[ 18%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGzipCodec.cpp.o
[ 21%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttp.cpp.o
[ 23%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpClient.cpp.o
[ 26%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpServer.cpp.o
[ 28%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXNetSystem.cpp.o
[ 31%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptFactory.cpp.o
[ 34%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptPipe.cpp.o
[ 36%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterrupt.cpp.o
[ 39%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSetThreadName.cpp.o
[ 42%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocket.cpp.o
In file included from /home/gmk/phytec_project/ocpp_test/github_machinezone_arm/ixwebsocket/IXExponentialBackoff.cpp:9:0:
/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/cmath:45:15: fatal error: math.h: No such file or directory
 #include_next <math.h>
               ^~~~~~~~
[ 47%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptEvent.cpp.o
[ 47%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHandshake.cpp.o
[ 50%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHttpHeaders.cpp.o
compilation terminated.
[ 52%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketTLSOptions.cpp.o
CMakeFiles/ixwebsocket.dir/build.make:158: recipe for target 'CMakeFiles/ixwebsocket.dir/ixwebsocket/IXExponentialBackoff.cpp.o' failed
make[2]: *** [CMakeFiles/ixwebsocket.dir/ixwebsocket/IXExponentialBackoff.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 76%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketFactory.cpp.o
[ 78%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.o
[ 55%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketConnect.cpp.o
[ 57%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketServer.cpp.o
[ 63%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUuid.cpp.o
[ 63%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketCloseConstants.cpp.o
[ 65%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUdpSocket.cpp.o
[ 71%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUrlParser.cpp.o
[ 73%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.o
[ 81%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketProxyServer.cpp.o
In file included from /opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/ext/string_conversions.h:41:0,
                 from /opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/bits/basic_string.h:6349,
                 from /opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/string:52,
                 from /home/gmk/phytec_project/ocpp_test/github_machinezone_arm/ixwebsocket/IXSetThreadName.h:7,
                 from /home/gmk/phytec_project/ocpp_test/github_machinezone_arm/ixwebsocket/IXSetThreadName.cpp:6:
/opt/phytec-yogurt/BSP-Yocto-i.MX6UL-PD19.1.0/sysroots/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/usr/include/c++/7.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
CMakeFiles/ixwebsocket.dir/build.make:86: recipe for target 'CMakeFiles/ixwebsocket.dir/ixwebsocket/IXCancellationRequest.cpp.o' failed
make[2]: *** [CMakeFiles/ixwebsocket.dir/ixwebsocket/IXCancellationRequest.cpp.o] Error 1
CMakeFiles/ixwebsocket.dir/build.make:110: recipe for target 'CMakeFiles/ixwebsocket.dir/ixwebsocket/IXConnectionState.cpp.o' failed
make[2]: *** [CMakeFiles/ixwebsocket.dir/ixwebsocket/IXConnectionState.cpp.o] Error 1
[ 97%] Building CXX object CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketOpenSSL.cpp.o
CMakeFiles/ixwebsocket.dir/build.make:254: recipe for target 'CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpClient.cpp.o' failed
make[2]: *** [CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpClient.cpp.o] Error 1
CMakeFiles/ixwebsocket.dir/build.make:518: recipe for target 'CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketServer.cpp.o' failed
make[2]: *** [CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketServer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ixwebsocket.dir/all' failed
make[1]: *** [CMakeFiles/ixwebsocket.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bsergean** [comment]
It looks like a problem with the toolchain ...

**Comment by mgsanava** [comment]
> It looks like a problem with the toolchain ...

Right. It also couldn't find math.h as well. I will use a different toolchain version and check.
Is there anything that I can do to tell toolchain the file paths?

**Comment by bsergean** [comment]
I have never worked with custom toolchain (maybe on Android without knowing), sorry I can't help. Google will be your best chance here ...

**Comment by bsergean** [comment]
I think the toolchain was broken here, will close.
