### ISSUE TITLE
how to build ws correctly ?! (spdlog issue)

### ISSUE THREAD

**Issue by Hedgezzz** [machinezone/IXWebSocket#439]
I have the following steps to build ws :

in IXWebSocket-master/ws  directory  

mkdir Step1_build
cd  Step1_build
cmake ../
cmake --build .

IXWebSocket-master/ws/ws.cpp:36:10: fatal error: spdlog/sinks/basic_file_sink.h: Nosuch file or directory
 #include <spdlog/sinks/basic_file_sink.h>

My Question :: 

Is it possible not to install spdlog and still can build ws ?!
it sounds ws is a great to me .

**Comment by Hedgezzz** [comment]
I figure it out , while build it 
just use 
cmake -DUSE_TLS=1 -DUSE_WS=1 ..
works fine to me

**Comment by bsergean** [comment]
Ah sorry about that. Good that you found a workaround.
