### ISSUE TITLE
How to do httpclient post right ?!

### ISSUE THREAD

**Issue by Hedgezzz** [machinezone/IXWebSocket#440]
I have the following code ::

string req="https://testnet.binancefuture.com/fapi/v1/order?symbol=BTCUSDT&side=BUY&type=LIMIT&timeInForce=GTC&quantity=1&price=21002.2&recvWindow=60000&timestamp=1676439415772&signature=28ba85cfdb2b44cf12d89281c6ef7704a4211224b6b92c81763ec394b2e8db87" ;

    HttpClient httpClient;
    HttpRequestArgsPtr args = httpClient.createRequest();
    WebSocketHttpHeaders headers;
    headers["X-MBX-APIKEY"] = "XXXXXXXXXXXXXXXXXXXXX";
    args->extraHeaders = headers;

        HttpResponsePtr response;
        std::string ixurl = "https://testnet.binancefuture.com"; 
        response = httpClient.request(ixurl, "POST",req, args,0);
        auto body = response->body;
        cout << body << endl ;

this source would core dump ,  what should I do to make this work ?!

BTW ,  the following works in curl ::

curl -H "X-MBX-APIKEY: XXXXXXXXXXXXXXXXXXXXX" -X POST "https://testnet.binancefuture.com/fapi/v1/order?symbol=BTCUSDT&side=BUY&type=LIMIT&timeInForce=GTC&quantity=1&price=21002.2&recvWindow=60000&timestamp=1676439415772&signature=28ba85cfdb2b44cf12d89281c6ef7704a4211224b6b92c81763ec394b2e8db87"

**Comment by bsergean** [comment]
can you catch the crash in a debugger ?

**Comment by Hedgezzz** [comment]
look like I use the following post function can work perfectly :

    auto response = httpClient.post(url,args->body, args);
