### ISSUE TITLE
Change the root dir of ixwebsocket-config.cmake to CMAKE_CURRENT_BINARY_DIR

### ISSUE THREAD

**Issue by Numendacil** [machinezone/IXWebSocket#452]
Currently, the [CMakeLists.txt](https://github.com/machinezone/IXWebSocket/blob/dc7b986e1092e59195085b708033723f4912b98f/CMakeLists.txt#L290) of this project uses `CMAKE_BINARY_DIR` as the root directory for the configuration file, which causes ixwebsocket-config.cmake to be added in the root dir of build tree (defaults to `./build` or `./out/build/xxx/` for Visual Studio on Windows), even if it is included as a submodule with `add_subdirectory`.

Since we are not actually using this file in the build tree (only to be copied when cmake install is called), I believe that it is better if we use  `CMAKE_CURRENT_BINARY_DIR` instead of `CMAKE_BINARY_DIR` so that the file is placed in a separate subdirectory under ./build when used as a subproject, since on some build systems the call to `find_package(ixwebsocket QUIET)` will search in the root of ./build and, upon finding ixwebsocket-config.cmake, wrongly took it to be the installed config file and raise an error since it is unable to find ixwebsocket-targets.cmake. The use of  `CMAKE_CURRENT_BINARY_DIR` is the [default behavior](https://cmake.org/cmake/help/latest/command/configure_file.html) for `configure_file` if a relative path is given for the output file.

**Comment by bsergean** [comment]
I'm not a cmake expert, so we could try your fix. Do you mind making a PR for it ?

A good thing would be to see if this would work with vcpkg afterwards.
