### ISSUE TITLE
HTTPServer questions?

### ISSUE THREAD

**Issue by blitz-research** [machinezone/IXWebSocket#476]
Hi,

I've got ix::WebSocketServer goind nicely but am a bit confused by ix::HttpServer.

All the HttpServer examples I've seen don't appear to do anything, they just create a server and listen. How does this differ from creating a WebSocketServer?

I would like to use HttpServer to create a static file server that runs on the same port as the websocket server. Does HttpServer support this? Are there any examples of this anywhere?

The only way I can think of (and am about to try) is to add an onConnectionCallback and do all the static file I/O myself, is this the general idea?

[edit]
OK, it looks like there's a default connection handler in there that servers static files from the current directory, is this correct? It would be nice if this could be souped up with mount points etc...
[/edit]

Bye!
Mark

**Comment by blitz-research** [comment]
OK, problem more or less solved: I wrote a custom HttpServer::ConnectionCallback based on the default one in ix, adding a bunch of tweaks eg: for a static mount point and special response headers.

I also reused my WebSocketServer::ConnectionCallback which means the HttpServer object actually ends up with two OnConnectionCallbacks which is a little ugly, not sure if these should be named differently:

g_server->ix::HttpServer::setOnConnectionCallback(&myHttpServerConnectionCallback);
g_server->ix::WebSocketServer::setOnConnectionCallback(&myWebSocketServerConnectionCallback);

...but overall it wasn't too bad and my static file and websocket servers are now both running on the same port!

Bye,
Mark

**Comment by bsergean** [comment]
Yes someone added this support a few months ago, glad that you got it working.
