### ISSUE TITLE
Source code release v11.4.4 contains an error in IXSocketMbedTLS.cpp line 52

### ISSUE THREAD

**Issue by stupidaria** [machinezone/IXWebSocket#479]
`bool SocketMbedTLS::loadSystemCertificates(std::string& /* errorMsg */)`

errorMsg variable name commented out for some reason...

**Comment by bsergean** [comment]
I think this is fixed in the master/latest branch.

**Comment by Longwater1234** [comment]
@bsergean Can you please kindly make a new release of the fix ?

**Comment by bsergean** [comment]
Here we go @Longwater1234 !

**Comment by bsergean** [comment]
Closing this, I think we're good now.
