### ISSUE TITLE
UWP App undefined method PathMatchSpecA

### ISSUE THREAD

**Issue by rh101** [machinezone/IXWebSocket#492]
![image](https://github.com/machinezone/IXWebSocket/assets/8603230/8544d25c-f7b8-49a0-a046-4880afdcf80d)

`PathMatchSpecA` is in `shlwapi.h`, but that entire code is disabled when compiling a Universal Windows application (WinRT/C++):

![image](https://github.com/machinezone/IXWebSocket/assets/8603230/c7241ae9-b185-4cf5-9276-e4b85a96982b)

Due to this check:
![image](https://github.com/machinezone/IXWebSocket/assets/8603230/de04ff56-5e98-427c-9eef-b47288e1d662)

I noticed that `SocketOpenSSL::checkHost()` is only used if `OPENSSL_VERSION_NUMBER < 0x10100000L`, and it's a private method, so not called from anywhere outside of `SocketOpenSSL`.  In my case it's also not being called at all given that the OpenSSL version number is greater than `0x10100000L`, so as a work-around, I've just changed it to this:
```
    /**
     * Check whether a hostname matches a pattern
     */
    bool SocketOpenSSL::checkHost(const std::string& host, const char* pattern)
    {
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
        return true;
#else

#ifdef _WIN32
        return PathMatchSpecA(host.c_str(), pattern);
#else
        return fnmatch(pattern, host.c_str(), 0) != FNM_NOMATCH;
#endif

#endif
    }
```

Can you see any issue with doing this?

**Comment by bsergean** [comment]
I think you're doing the right thing. Do you want to make a Pull Request for this ?

**Comment by rh101** [comment]
> I think you're doing the right thing. Do you want to make a Pull Request for this ?

Sure, I'll enter a PR soon with a few other changes I had to make in order to allow it work with C++/WinRT.
