### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by Dimon4eg** [machinezone/IXWebSocket#55]
Why IXW doesn't have CHANGELOG?

**Comment by bsergean** [comment]
I have not written any script to populate one automatically from tickets or git commits. I don't really want to have to write that manually. (that being said the git commits comments are a bit ugly).

**Comment by Dimon4eg** [comment]
Why git commits?
Just write manually what fixed, which features added, what changed

**Comment by Dimon4eg** [comment]
No need to write about each git commit, it's not very informative.
Better to write manually main features, fixes, changes.

For example look here:
https://github.com/heroiclabs/nakama-cpp/blob/master/CHANGELOG.md

**Comment by bsergean** [comment]
Thanks for the example, I agree that a Changelog is helpful.

**Comment by bsergean** [comment]
Just added one, still incomplete but I'll document things there. 

https://github.com/machinezone/IXWebSocket/blob/master/CHANGELOG.md

**Comment by Dimon4eg** [comment]
Great!
Now IXW looks very solid :1st_place_medal:
