### ISSUE TITLE
Use existing cross-platform socket library

### ISSUE THREAD

**Issue by Dimon4eg** [machinezone/IXWebSocket#56]
During supporting Windows for IXW, I've made part of same work which is already done and well tested in this project:
https://github.com/halx99/yasio/blob/master/yasio/xxsocket.h

> A lightweight & stable cross-platform support library with a focus on asynchronous socket I/O, support win32 & linux & apple & android
This lib has been used by project http://hongjing.qq.com/ and run at millions of devices.

Also we can use his asio for async operations:
https://github.com/halx99/yasio/blob/master/yasio/yasio.h

Currently IXW doesn't have `poll` or similar method which I need to avoid multi-threading issues: IWX executes callbacks from internal threads.
The `yasio` has `dispatch_events` for this.

I think better to use it to save time and avoid headache.
I believe after using it all tests will pass on Windows.

**Comment by bsergean** [comment]
Thanks for bringing this up. My first feeling is that I prefer not using something external of that scope, but I may change my mind one day. At this point in time I prefer on keeping on using our socket abstraction. And our code also runs on million of devices :)

If a user cannot live with callback executed in a background thread, he should use a queue + condition variables. We do that ourself with lua callbacks (we have a binding for this library) which needs to execute on the main thread.

Maybe we could have an API for that ; the server code actually does not use a separate thread, but it is blocking the thread. I prefer not complicating the current design right now and supporting this, to keep  the API simple.

**Comment by Dimon4eg** [comment]
I understand your point.
One main difference IXW does not fully support Windows.
Also IWX uses raw socket in many places, I think better to use existing well tested and cross platform xxsocket for that.

**Comment by bsergean** [comment]
Thanks for the link to this library, we can use it as a reference next time we have a problem.

I prefer to keep our (simple) socket code as it is right now as it does the job. Btw thanks for all your work to making the windows experience better, even if it is still far from being perfect.
