### ISSUE TITLE
Using INADDR_ANY in SocketServer::listen()

### ISSUE THREAD

**Issue by jaket466** [machinezone/IXWebSocket#74]
I'm setting up a WebSocketServer on a Linux-based OS, which I am connecting to from both a local client and a client on another computer. I've found that I can only make the second connection if I explicitly set the server's IP address to that of one the machine's network interfaces - if I try to use the loopback address, the incoming connection isn't detected. My goal is to be able to make this connection using the loopback address for my server.

After a bit of reading and tinkering, I've made this work by changing line 94 in IXSocketServer.cpp to set s_addr to INADDR_ANY. The comments before that line mention existing problems with the osx firewall that explain why we default to localhost instead. This implies that there are no known issues with using INADDR_ANY on a Linux-based machine, so I'm guessing this is safe to do in my case. Is it worth setting the s_addr differently depending on the OS while the osx firewall issue remains unresolved?

**Comment by bsergean** [comment]
Hey Jake,

Have you tried to use '0.0.0.0' for the binding hostname ? This is what I'm doing on a Linux server to accept connections coming from anywhere.

```
$ ws echo_server --help
Echo server
Usage: ws echo_server [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --port INT                  Port
  --host TEXT                 Hostname
```

You could try to run the ws command line tool on your Linux box: `ws echo_server --host 0.0.0.0`

**Comment by bsergean** [comment]
https://www.howtogeek.com/225487/what-is-the-difference-between-127.0.0.1-and-0.0.0.0/

First link on Google, there might be better other links.

**Comment by jaket466** [comment]
I haven't tried that before now, but using 0.0.0.0 does work as well. That gives me some more options that don't require changing the IXWebSocket code, which is nice. 

I wasn't sure if using INADDR_ANY was worth doing by default, so I figured I might as well raise a ticket for it in case other people ran into this. Feel free to close this if you think there's no action needed here.

Thanks for the quick reply!

**Comment by bsergean** [comment]
No worries, it was a good thing to ask. And now google will crawl that page and that conversation will hopefully will useful to some folks.

Keep the questions coming !
