### ISSUE TITLE
Add error when invalid hostname is passed in SocketServer

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#78]
We could use a simple regexp like this one:

https://www.regextester.com/23

**Comment by Dimon4eg** [comment]
Why we should do this validation?

**Comment by bsergean** [comment]
I had a coworker who tried to pass in a url to the socker server, it did fail and he wasn't too sure about it. We don't necessarily have to use a regexp.

It's a nice to have feature for user-friendliness.

**Comment by Dimon4eg** [comment]
Instead of remote error you will tell him local error: Invalid hostname.
Do you think it will be more clear for him?

**Comment by bsergean** [comment]
yes local error invalid hostname is a good way.

**Comment by bsergean** [comment]
Spring cleanup, we don't really need this, closing.
