### ISSUE TITLE
Missing features for nakama-cpp

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#83]
Hey @Dimon4eg and @Kumamon38 

I noticed that you guys have adopted cpprest in nakama-clients, which looks like a very solid library. I understand that you need 'the job done' and will use the right library. 

Do you mind elaborating real quick on why you couldn't use IXWebSocket, and the holes it had ?

I would guess:

* Good windows support
* Missing TLS on windows
* Other bugs
* Other feature I can't think about ?
* cpp-rest also has a oauth, http client, tasks, etc...

In the future I'd like to change that lib so that it can be more easily adopted by anyone. Thanks for any input, and all the bug fixes you guys have contributed !

**Comment by Dimon4eg** [comment]
Hey @bsergean

For us following are missing in IXW:
* good Windows support (including SSL)
* good cross platform HTTP client with SSL support

But I like IXW and would like to use instead cpprest because it smaller, doesn't have boost dependency and as result binary is smaller that is important for mobile apps.

**Comment by bsergean** [comment]
Thanks, good to know. I'll think about that. I need to get a Windows VM or laptop to research how I can hook up SSL. I like the 'zero-dependencies' SChannel thing ; I should see how curl uses it.

The HTTP client should work with SSL but its interface might not be the best (it returns a big tuple), and it is blocking, it does not have a callback. It has been tested a bit but not too much, mostly with the `ws curl` command, and by using it in our games as a fallback. I use it in daemon tools that send data to Sentry through HTTP POST.

**Comment by Dimon4eg** [comment]
Nice to hear that.
Thank you!

**Comment by bsergean** [comment]
Hey I have added early support for SSL on Windows using mbedtls, which needs to be static linked like zlib. It is a relatively small C library so it shouldn't be too bad for the memory footprint.

*Disclaimer is that certificate verification is off*. I need to find a user friendly way to bundle CA certificates (what firefox does) or use the system certificates. Note that on Android there's a related problem ; a path to a CA cert file needs to be passed in with SSL_CERT_FILE (usually this isn't necessary on Linux).

**Comment by bsergean** [comment]
I meant binary size, not memory footprint. It's quite fast to compile.

**Comment by bsergean** [comment]
https://github.com/ARMmbed/mbedtls

**Comment by bsergean** [comment]
Hey @Dimon4eg I just added an async API for the http code fyi. There's unittest and some reference to the new way to use it in the README.

PR -> https://github.com/machinezone/IXWebSocket/pull/90

```
//
// Asynchronous Request
//
bool async = true;
HttpClient httpClient(async);
auto args = httpClient.createRequest(url, HttpClient::kGet);

// Perform the request asynchronously.
bool ok = httpClient.performRequest(args, [](const HttpResponsePtr& response)
    {
        // This callback execute in a background thread. Make sure you uses appropriate protection such as mutex
        auto statusCode = response->statusCode; // access results
    }
);
```

Note that I could do a better job at cancelling requests when the client goes away. I'll make a note of that.

**Comment by Dimon4eg** [comment]
Cool!
Will try it.
Thank you 👍

**Comment by bsergean** [comment]
Thanks ! I've inspired myself from https://github.com/spotify/NFHTTP for the API.

Some stuff I still need to do:

1. I need to make sure the new SocketMBedTLS is super thread safe.
2. I need to setup that CACert thing.
3. I need to see how I can add cancellation.

Ideally I would setup and make a branch of nakama-client and see what else is needed so that the API is compatible with your requirements.

**Comment by Dimon4eg** [comment]
The NFHTTP looks interesting but it has `boost` and `cpprest` dependencies :disappointed:

**Comment by bsergean** [comment]
Yeah NFHTTP is not lightweight in the 'dependency' sense, but I was trying to find a descent async API and reused the one they have. I looked at cpprest and it looks very mature, but I didn't have anything like their 'task' api so I went with something simpler.

**Comment by Dimon4eg** [comment]
Ah, ok.
I like their idea to use native HTTP from platform.

**Comment by bsergean** [comment]
Hey guys I think that this can be closed, not sure if you'll have the need or will to use IXWebSocket again but I consider that the 'missing' features are mostly there.

Cheers !
