### ISSUE TITLE
Using IXWebSocket on Raspberry

### ISSUE THREAD

**Issue by EhsanVahab** [machinezone/IXWebSocket#85]
Hi dear @bsergean ,
Thanks for your great and light project to use Websocket technology.
I have a simple and maybe clear question.
is it possible to use IXWebSocket  on Arm board family specially Raspbian OS?

**Comment by bsergean** [comment]
Hi @EhsanVahab, thanks for the nice words about that library.

I think it is possible. I have actually built this library on Debian and Ubuntu, and Raspbian sounds like a Debian on Rasberry Pie.

```
apt-get -y install g++ 
apt-get -y install libssl-dev
apt-get -y install libz-dev
apt-get -y install make
apt-get -y install cmake
```

Then git clone this repo over there, enter the top level folder and run `make ws`. If you have compile error paste them in this ticket and I'll look at them.

**Comment by bsergean** [comment]
I just looked and there's a raspbian based on debian stretch, I'm almost certain that I built IXWebSocket on debian stretch.

**Comment by EhsanVahab** [comment]
Thanks for quick response dear @bsergean 
I've gotten a raspberry device and installed IXWebsocket on without any problem.
