### ISSUE TITLE
Error during WebSocket handshake: 'Upgrade' header is missing

### ISSUE THREAD

**Issue by tonylin0826** [machinezone/IXWebSocket#9]
When using chrome as websocket client, it failed with the following message. 

![image](https://user-images.githubusercontent.com/5596402/51165746-3bffc380-18dc-11e9-9ebb-51553916f3e5.png)

Seems like the server didn't send the correct header.

**Comment by bsergean** [comment]
It should be good now that to your fix !

I added fdbd213fa28cf9b1420f9c96c33342af115cfa2e to properly handle the Connection header. Tell me if this is giving you trouble with Chrome.
